### ISSUE TITLE
export traffic to pcap file

### ISSUE THREAD

**Issue by cauqp3ex** [mitmproxy/mitmproxy#1016]
first off all , i am sorry about my language .
i try to sniffing https traffic using client certificate  via mitmproxy.
i want to show same traffic on wireshark but no way to export it to pcap file .
is there any way to get a pcap file that contains https decrypted traffic through mitmproxy .

**Comment by dufferzafar** [comment]
I don't think mitmproxy currently supports exporting the traffic to PCAP format. This feature is already being discussed on issue #408

**Comment by mhils** [comment]
The recommended way to do this is to (1) [log the TLS master secrets](http://docs.mitmproxy.org/en/stable/dev/sslkeylogfile.html) with mitmproxy and (2) use a normal PCAP tool for packet capture.

**Comment by jfunction** [comment]
btw the link for step 1 is now dead - should probably be [this](https://docs.mitmproxy.org/stable/howto-wireshark-tls/)

**Comment by muzuiget** [comment]
I write a simple addon script to implement this feature.

https://github.com/muzuiget/mitmpcap

**Comment by dc401** [comment]
I know this is an old thread and thank you to muzuiget for writing the add on script. 
I'm also leaving an alternate option that is not discussed is [PolarProxy ](https://www.netresec.com/?page=PolarProxy)which is a stand alone that does the same thing. It's a creative commons license. This is so that others may benefit from any internet searching for this type of functionality.

**Comment by moneypython** [comment]
@dc401 thank you for this link.  I ended up using PolarProxy.  It's a bit disappointing that mitmproxy doesn't support better integration with industry standard tools like wireshark.  I need to do more binary tcp analysis for my projects.
