### ISSUE TITLE
Q: Why no mitmproxy-0.16.tar.gz 

### ISSUE THREAD

**Issue by petrrr** [mitmproxy/mitmproxy#1064]
I am realizing that for version 0.16, there is no `tar.gz` source distfile on PyPI any more.  

Why is that?
Does this reflect an intended change in the way the software is published/distributed?

##### Steps to reproduce the problem:

1. N/A no real problem yet.
2. 
3. 

##### What is the expected behavior?
MacPorts so far used these `tar.gz` distfiles from PyPI to install `mitmproxy`. So we would need to understand if these will be published there in future. 

##### What went wrong?
N/A

##### Any other comments?
I would need to understand the background, of the missing distfile (the one we use for installation), so that we can appropriately solve the issue with upgrading mitmproxy to 0.16. in a way that it works in future. TNX!

---
Mitmproxy Version: 0.15 vs. 0.16
Operating System: OS X (Macports)

**Comment by mhils** [comment]
Thanks for the feedback, @petrrr! There were two reasons why we removed the `tar.gz` files:

1. Old pip versions (hello, Ubuntu 12 LTS) will use these instead of wheels and break with cryptic error messages. Not providing `tar.gz` results in human-readable errors.
2. We did not know of anyone actually using them.

So, my understanding is that wheels just work better 99.9% of the time. Is there any reason why you can't use these? Alternatively, would you be able to use `.zip` snapshots from GitHub?

**Comment by petrrr** [comment]
Thanks for your quick reply. In the first place, I wanted to understand what happened and how to best solve the issue. Macports does not use pip directly. For sure we could use the source distfiles on GitHub instead. Not sure yet how we could use wheels, I'd need to look into this. 

In any case, I understand that you intentionally changed from `tar.gz` to wheels for any future releases. So we have to take care of this change on our side. This info is sufficient for us. So I am closing this issue. Thanks!

**Comment by mhils** [comment]
Thanks, you are welcome!
