### ISSUE TITLE
Please do not eat CPU

### ISSUE THREAD

**Issue by smurfix** [mitmproxy/mitmproxy#1112]
##### Steps to reproduce the problem:

1. strace -f libmproxy-using-python-script
2. die

##### What is the expected behavior?

No connections = nothing to do = 100% idle.

##### What went wrong?

Doing nothing every millisecond or two is Just Plain Wrong.

```
[pid 27773] gettimeofday({1462307648, 659308}, NULL) = 0
[pid 27773] gettimeofday({1462307648, 659481}, NULL) = 0
[pid 27773] gettimeofday({1462307648, 659707}, NULL) = 0
[pid 27773] gettimeofday({1462307648, 659916}, NULL) = 0
[pid 27773] gettimeofday({1462307648, 660072}, NULL) = 0
[pid 27773] select(0, NULL, NULL, NULL, {0, 1000}) = 0 (Timeout)
[pid 27773] gettimeofday({1462307648, 661472}, NULL) = 0
[pid 27773] select(0, NULL, NULL, NULL, {0, 2000}) = 0 (Timeout)
[pid 27773] gettimeofday({1462307648, 663799}, NULL) = 0
[pid 27773] select(0, NULL, NULL, NULL, {0, 4000} <unfinished ...>
[pid 27776] <... select resumed> )      = 0 (Timeout)
[pid 27776] select(6, [5], [], [], {0, 100000} <unfinished ...>
[pid 27773] <... select resumed> )      = 0 (Timeout)
[pid 27773] gettimeofday({1462307648, 668192}, NULL) = 0
[pid 27773] select(0, NULL, NULL, NULL, {0, 1497}) = 0 (Timeout)
[pid 27773] gettimeofday({1462307648, 669999}, NULL) = 0
[pid 27773] gettimeofday({1462307648, 670124}, NULL) = 0
[pid 27773] gettimeofday({1462307648, 670270}, NULL) = 0

```

---

Mitmproxy Version: HEAD
Operating System: Debian testing

**Comment by mhils** [comment]
My idle mitmdump clocks at 0.15% CPU usage on a Core i5, which I think is fine. I'm not sure if I understand your issue?

**Comment by Kriechi** [comment]
@smurfix could you please share your python script so we can see how you are using mitmproxy?
I guess you are not using `libmproxy` anymore, since it got renamed a while a ago and you said you are on git-HEAD?

**Comment by smurfix** [comment]
Yeah, force of habit since I restarted an old project and tried strace to find a problem.

My script does not affect the outcome. "strace -f mitmdump" will do just fine.

@mhils My point is that if the system is idle, mitmproxy has nothing to do, thus should consume no CPU and allow the system to enter deep sleep. Saves much more power than the minuscle 0.15% suggests.

**Comment by mhils** [comment]
This is partially due to Python 2's terrible implementation of Condition.wait (see #443). Other than that, having a central event loop is a key part of mitmproxy - I don't see a good way around this at the moment. I'm happy to accept patches that try to address this, but <0.2% idle performance is currently fine for the project.

**Comment by smurfix** [comment]
Well, the event loop does two things -- (a) check should_exit, (b) read from the event queue.
If you replace shutdown() with "write a please-exit event to the event queue", you no longer need a timeout to switch between the two.

I'll put that on my to-look-at list.

**Comment by cortesi** [comment]
@smurfix Hi Mattias - thanks for taking an interest here. We may gain something by signalling exit through the event queue - it might be cleaner, and in fact, that portion of the project should be tightened up more generally (explicitly restricting allowed events, preventing direct access to the event_queue from other portions of the codebase, etc.). However, Max's point about Python2's Wait implementation still applies - because that's how Queues are monitored for new messages in Python. All of this should improve when we've moved to Python3 (under way), where we have some better primitives to work with.
