### ISSUE TITLE
Interaction between -r and -a

### ISSUE THREAD

**Issue by thiagoarrais** [mitmproxy/mitmproxy#1117]
I don't know what is the expected behavior here, but I've found out that doing this results in _very_ large flow files:

1. Start some webserver
`python -m SimpleHTTPServer 8000`

2. Start a reverse proxy to that server. Append flows to some (non-existent) file
`mitmproxy -a /tmp/somewhere.flows -p 8080 -R http://localhost:8000`

3. Make some requests to said proxy:
`curl -s http://localhost:8080 > /dev/null`

4. Stop the proxy

5. Check the size of the flows file:
`stat -c "%s %n" /tmp/somewhere.flows` => `23059 /tmp/somewhere.flows`

6. Start a new proxy instance. Append flows to same file. But, this time, try to read from it too.
`mitmproxy -r /tmp/somewhere.flows -a /tmp/somewhere.flows -R http://localhost:8000`

7. Do not issue any requests. Just wait for a few seconds (the process hangs)
8. Kill the proxy process

9. Check the size of the flows file again:
`stat -c "%s %n" /tmp/somewhere.flows` => `21942730 /tmp/somewhere.flows`

10. Wow!

I did this expecting to be able to work with the previous captured flows (filter them, repeat requests, etc.) while still recording the new interactions. Do you think this is a valid use case?

Tested with mitmproxy 0.17 and master.

**Comment by mhils** [comment]
I think this expected behaviour. We don't want to have all flows in memory, so we read iteratively. If you append one flow for each flow that has been read, you end up in an infinite loop. 
If you just want to record new interactions, `-a` is append only, you don't need to re-read the existing ones. If you want to filter an existing file, `-r existing -w new` does the job just fine. If you want to concat two files, you want to use `-r foo -a all`.

**Comment by thiagoarrais** [comment]
I guess that's right. Maybe `mitmproxy` should just refuse to start when in and out files are the same?

**Comment by mhils** [comment]
This is implemented now, thanks.
