### ISSUE TITLE
Inline Scripts: Better Logging (was: First-class print() support.)

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1124]
Currently, the recommended way to do logging in inline scripts is `context.log`. It would be nice if `print()` would just work out of the box and log to the event log. Not sure what's the best way to do this (override, print, redirect sys.stdout, ...?), that needs some experimentation. :smiley:

**Comment by KostyaEsmukov** [comment]
Celery, for example, simply overrides `sys.stdout`/`sys.stderr` to achieve this.

See:
https://github.com/celery/celery/blob/aee706ad5a743e3a51ed40f827bc02e61947902d/celery/app/log.py#L196

**Comment by MatthewShao** [comment]
I try this out by replacing `print` to `context.log` in the namespace.
On [https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/script/script.py#L76](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/script/script.py#L76), change it to:
```
self.ns = {'__file__': os.path.abspath(self.args[0]), 'print': self.ctx.log}
```
so that in the script, we can simply write `print(message)` to do the logging.
This is a simple way to achieve the goal, but I don't know how does it compare to overriding `sys.stdout`.
@mhils How's this sounds? If you think this is OK, I would like to give a PR.

**Comment by mhils** [comment]
cc @dwfreed: how does this play with your logging stuff?

**Comment by cortesi** [comment]
I'm doubtful of the wisdom of over-riding the built-in print statement - it's clever but may be too surprising. Printing to screen and logging are two different things, and there are times when one wants to distinguish between them - e.g. while troubleshooting issues, while developing unit tests, etc. The current logging situation needs to be improved, my suspicion is that once we've done that the benefit won't be enough to pay for the downsides of appropriating print.

**Comment by MatthewShao** [comment]
No matter we override `print()` or redirect `sys.stdout`, our aim is to use the `print()` to call `context.log()` in our scripts, right?  As @cortesi metioned, we should reconsider about the trend off in this case. @mhils Any idea?

**Comment by cortesi** [comment]
Just to be concrete about this, here's what I'm proposing:

- We make the logging interface more pleasant to use and unify it across the codebase. We have had some discussions about this, and we're reasonably sure we know what to do.
- We encourage users in all contexts to log explicitly through the logging API. We're actively working on integrating the inline script and handler interfaces. I don't want to encourage using print() for logging in one context but not the other. 
- When scripts are run in the proxy context, we need to decide what to do with stdout/stderr. They must be captured, since we don't want them to interfere with things like the mitmproxy console interface. From there we can either just ignore them, or we can insert them into the logs with log level WARNING. Why WARNING? I don't want people to feel that print() is the correct way to display ordinary output to users in the event log. I don't have a very clear preference here, but I lean slightly towards ignoring.
- Finally, when scripts are outside of the proxy context, say in unit tests, stdout/stderr are uncaptured, and print and log are distinct. It's a common unit testing pattern to perform an operation and then inspect the event log buffer to see what's happened. Printing something like debugging output shouldn't interfere with that.

**Comment by mhils** [comment]
>  From there we can either just ignore them, or we can insert them into the logs with log level WARNING.

I have a clear preference for `WARNING`, because text that just doesn't appear is hard to debug.

**Comment by cortesi** [comment]
I'm afraid the subtleties of German humour escape me here, so I'll just clarify what I meant. ;) 

We have 3 log levels for add_event at the moment **debug**, **info** and **error**. The **info** level is what's used for normal script output. None of these are quite right for captured stdout/stderr output, and in particular, what I meant above is that it should certainly not use **info**. We should add a **warning** level, as is conventional in most of these tiered log systems, and captured output should go there. So:

- **debug**: only shown if explicitly enabled by the user
- **info**: normal script output (shown in white)
- **warning**: things that should be noted but aren't terminal (shown in orange/yellow)
- **error**: something went wrong (shown in red)

**Comment by mhils** [comment]
Just dumping this here, because it's very related: https://docs.python.org/3.5/library/contextlib.html#contextlib.redirect_stdout

**Comment by cortesi** [comment]
The situation has changed since this discussion. Scripts and built-in addons are now unified, and 
I'd like code in both contexts to be the same. I don't want magic prints in our main codebase, so we should also discourage them in scripts. On balance, the "right thing" here is to intercept prints in inline scripts and turn them into WARNs in the logs. 

I'm going to close this ticket, which has become a bit bloated, and open a concrete action ticket instead.
