### ISSUE TITLE
Intermittent Travis failure

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1186]
##### Steps to reproduce the problem:

1. Make a commit
2. Observe that Travis fails sometimes
3. Rebuild
4. Observe that it succeeds sometimes

##### What is the expected behavior?

Consistent error results

##### What went wrong?

Inconsistent error results

Mitmproxy Version: -master
Operating System: I've only seen it affect the Xcode 7.1 build

<img width="903" alt="screen shot 2016-06-01 at 5 18 46 pm" src="https://cloud.githubusercontent.com/assets/22544/15699196/4dde7dfe-281f-11e6-88bc-45546346152b.png">

**Comment by mhils** [comment]
This affects a ton of pathod tests, most of them are currently marked as `pytest.skip`.There seems to be a race condition where `.last_log()` doesn't have the latest result yet, but `.get()` already returned.

**Comment by cortesi** [comment]
Oh - we should probably hunt down the issue rather than skipping the tests. :)

**Comment by mhils** [comment]
I suspect this is the same terrible race condition I initially had with the TCP tests.
A connection thread writes a result to the client so that the client can continue immediately.
However, after returning, the connection thread emits one more log event into pathod's queue. Back in the test, just `.join()` ing the queue isn't sufficient, because we may access that before `.log()` is even called in the thread.

(all of the above is just a possible cause for the test, but we have the issue in any case)

**Comment by cortesi** [comment]
This is now fixed.
