### ISSUE TITLE
pathoc -n seems broken

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1221]
##### Steps to reproduce the problem:

> pathoc -n 2 google.com get:/
07-06-16 12:22:24: >> 'GET':/
<< 302 Found: 261 bytes

##### What is the expected behavior?

Two requests printed.

##### What went wrong?

Only one request is printed.

---

Mitmproxy Version: -master
Operating System: osx

**Comment by mhils** [comment]
This is caused by [this line](https://github.com/mitmproxy/mitmproxy/blob/20bcfbb5d03fd463449412dc3a626b2958a862ca/pathod/pathoc.py#L493), where 0da3e51e1c08eed2c8054d4a71bc591268b19af1 made `args.requests[0]` a generator that is exhausted after the first pass. While looking into this, I realized that `pathoc get:/:x10` is similar to `pathoc -n 10 get:/`, with the major difference being that the former does everything on the same connection. We probably want to document that somehow.
