### ISSUE TITLE
Consider binding to localhost by default

### ISSUE THREAD

**Issue by colemickens** [mitmproxy/mitmproxy#1293]
I think users might be surprised if their box starts running an open proxy by nature of running `mitmproxy`. I propose changing the default to act like `mitmproxy -b 127.0.0.1` instead.

**Comment by mhils** [comment]
I generally welcome this proposal, but unfortunately this would break transparent mode by default, without providing any useful error message out of the box. 
I see three options:

- When `-T` is specified, we bind to `0.0.0.0` by default. This would probably cater for 95% of the cases, but it's a bit inconsistent.
- Actually bind to `0.0.0.0` and enforce the client IP in mitmproxy. This way we could display an error message in mitmproxy. I don't really like this approach though.
- Decide to keep everything as-is. A lot of services are listening on 0.0.0.0 by default. We may want to explore displaying client ips != localhost more prominently in the UI.

**Comment by colemickens** [comment]
Sorry, I now realize this was the conversation going on in Slack, I didn't pick up on the context properly.

I was just about to say "maybe it could make it obvious it's listening on all devices" and then I realized that it doesn't just say the port in the bottom-right, it actually says "*:9000" or in my case now "127.0.0.1:9000", so I ought to have put it together sooner. (Normally this wouldn't have been an issue thanks to external firewalls, but I just happened to have `mitmproxy` listening on a port that I also use to do testing with various things that I actually need to be able to hit from outside from time to time.)

I don't really like option #2 just from a cleanliness/separation-of-concerns standpoint either and I appreciate the consistency concern in #1.

#3 might help... At least if I'd known those requests came from off box I wouldn't have had the minor panic at seeing unknown traffic (that I thought was originating on box). But it may not be worth the effort to implement or design a new indicator.

Given all this, I guess feel free to close it unless you think option #3 is worth pursuing, and even then it might make sense as a new issue. Thanks for the time and response.

**Comment by javabrett** [comment]
I'm usually all-for conservative approaches when it comes to security, but in this case I think it is reasonable that, in deliberately starting a known proxy-server including the word proxy in its binary name, you should be willing to accept that by-default this will install an open-proxy server.  Hopefully it is sufficient that there is already a mechanism to restrict the address/adapter binding if desired.

My 2c worth.

**Comment by colemickens** [comment]
Agreed. I'm going to close this. Thanks for the thoughts @javabrett and @mhils .

**Comment by KOLANICH** [comment]
Soon after I have started mitmproxy I found it connected by differrent external ip addresses. I want to tell you that mitmproxy is just a free open source replacement for fiddler and fiddler by default disallows remote connection. Why the f*ck do you do in other way? Are you somehow related to the ones who scan the networks for open mitmproxies? I know that they targeted mitmproxies because it seems they have disabled tls cert checks.

**Comment by mhils** [comment]
I will ignore the im- and explicit insults and just tell you for the record that we do not scan networks for open proxies or gain any other personal benefit out of the bind-all behavior. As you may have seen, some users have already voiced their opinion that they favor the current implementation. If you feel strongly against this, please open a PR that e.g. uses the "clientconnect" hook to immediately close external connections as a proposal. You are welcome to contribute to the discussion in a civil way or remain silent. 

Thanks,
Max

**Comment by KOLANICH** [comment]
>we do not scan networks for open proxies or gain any other personal benefit out of the bind-all behavior.

I have asked not wheter or not you scan, but are some of the repo policymakers related somehow to people doing such things (including emploees of Shodan-like companies).

>If you feel strongly against this, please open a PR that e.g. uses the "clientconnect" hook to immediately close external connections as a proposal. You are welcome to contribute to the discussion in a civil way or remain silent.

Thank you for the info. It will take some time (I'm not very familiar with the project source and I'm a bit busy for now). Does #2428 solve the problem?

**Comment by mhils** [comment]
> I have asked not wheter or not you (or some repo policymakers) scan, but are some of the repo policymakers related somehow to people doing such things (including emploees of Shodan-like companies) because the defaults encourage such kind of activity.

Again, we are not. Using mitmproxy with external devices is a common use case, so we listen on all interfaces by default. We are really not alonw with this - the same behavior is exhibited by Burp, Squid, Apache, and others. The fact that we do this is permanently displayed at the bottom right just after startup. I understand you concern that this is surprising to some users, yet changing the behaviour without compromising core use cases is difficult.

> Does #2428 solve the problem with allowing remote connections?

As discussed above, this is not a suitable fix.

Given that you do not seem to be very pleased with mitmproxy overall, you may want to explore [alternatives](https://alternativeto.net/software/mitmproxy/).

**Comment by KOLANICH** [comment]
>Using mitmproxy with external devices is a common use case

I know. But it doesn't mean that this should be enabled by default.

>We are really not alonw with this - the same behavior is exhibited by Burp, Squid, Apache, and others.

Maybe. But it shouldn't.

>The fact that we do this is permanently displayed at the bottom right just after startup.

do you mean that little blue icon with port on it?

>I understand you concern that this is surprising to some users, yet changing the behaviour without compromising core use cases is difficult.

Again: mitmproxy starts accepting remote connections by default. Most of people who came for "free open source Fiddler" don't expect this. Some malicious people exploit that fact. That transforms that feature into a vurnerability.

>As discussed above, this is not a suitable fix.

Sometimes the changes breaking compatibility have to be done. Fixing vulnerability is the such case. I think it is more important to remove that vuln than preserve compatibility. It is just a one time fix for the people using mitmproxy, they will only need to remember this fact and fix their scripts and/or configs. 

Also I think we need more mitigations.
1 By default restrict the subset of addresses which can connect to the proxy to local ones.  By the local ones I mean in the same LAN (can it be checked by obtaining mac addr and comparing it to the switch's mac addr?).
2 Send the info about the original source of request to deter abuse.
3 When starting user interface if remote connections are allowed and no has been authentication set up before actually launching proxy make the user to confirm (in a big red window) that he understand that his proxy may be discovered and abused within seconds because remote connections are allowed.

**Comment by mhils** [comment]
I could be convinced to accept a PR that adds a mitmproxy addon which does the following:

- On `clientconnect`, check if any of these is true:
  - the source IP is from the same local subnet (IPv6)/private IP space (IPv4) 
  - the user has disabled the addon (there needs to be an option)
  - proxy authentication is enabled
- If so, unconditionally accept the request.
- If not, close the connection. Display a warning message in mitmproxy with concrete instructions to disable this measure . Send the same message to the client as well.

I'd be open to accept such a change, but if @Kriechi or @cortesi think that the current behaviour should stay, I'm not going to fight it. As I said before, I think the current behaviour is okay and the fact that we're far from the only ones doing this seems to confirm this.
