### ISSUE TITLE
HAR Export

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1320]
We used to have a [har_extractor.py](https://github.com/mitmproxy/mitmproxy/blob/811b72cd304a8c75efaf706fd57cfbe9494cd3d9/examples/har_extractor.py) inline script which converted a mitmproxy dump to a har file. Unfortunately, that script depends on the `harparser` library, which is Python 2 only. It'd be great to add support for HAR export again, ideally without depending on `harparser`.

**Comment by dufferzafar** [comment]
@mhils Can't we just port harparser to 3? It's a single file: https://github.com/JustusW/harparser/blob/master/harparser.py

**Comment by mhils** [comment]
@dufferzafar: That would work as well. Looking at the code, I believe it's probably easier and cleaner to just do the HAR stuff manually in the script.

**Comment by mkagenius** [comment]
I just tried har_extractor in python3 .. It worked! But there was couple of issues:

* queryString for param `id=aflon` was coming as 

```json
"queryString": [
            {
              "name": "i",
              "value": "d"
            }
          ],
```
(due to missing iteritems()  / items() .. i guess this was never working even in python 2)

* Cookies were coming as 

```json
"request": {
          "cookies": [
            {
              "name": "__cfduid",
              "value": "d"
            },
            {
              "name": "user",
              "value": "m"
            }
          ],
```

values have only one letter due to `v[0]` .. probably because it earlier used to an array? 

Both of these changes are supposed to be in `har_extractor.py`. If you want I can send a pull request. Rest of the fields looks fine on a cursory look.
