### ISSUE TITLE
Add Import/Export for HAR files

### ISSUE THREAD

**Issue by dufferzafar** [mitmproxy/mitmproxy#1477]
Once we get HAR dumping support (#1464) I think we should make it an integral part of mitm rather than keeping it as a external example:
- Allow user to export flows as HAR selectively. Just like we do for saving flows (`w` key.)
- Allow reading of HAR files. This will complete a bridge to/from other tools like browsers and other proxies.

**Comment by mhils** [comment]
Being able to read from multiple places would be awesome, that'd also be highly beneficial for pcap2mitm. The way to implement this is probably similar to what we do for contentviews and addons.

**Comment by dufferzafar** [comment]
@mhils: Can you please explain the "contentviews and addons" part a bit more, I’m not exactly sure how this relates to them?

**Comment by dufferzafar** [comment]
_Paraphrasing some discussion I had on this on Slack with @mhils:_

The best thing would be to have HAR support in FlowReader:

FlowReader/FlowWriter should be ABCs that define the reading/writing API then MitmFlowReader/HarFlowReader as implementations.

Then we could have a `make_reader(filename)` or something along those lines that returns the proper thing depending on the file extension.

For now we just want to focus on HAR & not PCAP (though that is something nice too) but pcap2mitmproxy is GPLed so we can't include it right now.

**Comment by cortesi** [comment]
I think we should keep our core FlowReader and FlowWriter concepts separate from exporters and importers. 

Exporters are the more complicated case, and there are many semantic ways in which they don't fit with our generalised FlowReader/Writer scheme. HAR, for example, has to be terminated after the last flow has been written to make it valid JSON. I don't think we should build the termination concept into our core, because there streaming flows one by one independently is the key attribute. I can also imagine a range of exporters that do things like, for instance, calculate summaries over multiple flows (in fact, I'm working on beasts like this right now) that only write data after all flows are consumed.  A further issue is that many exporters will only support exporting a single flow - i.e. curl command export. This again doesn't quite fit with flowreader/writer. 

What I'd really like is a way to register exporters and importers a la contentviews, as Max described. Addons should easily be able to add custom exporters/importers, and, in fact, it might be a useful discipline to choose to implement the built-in exporters using the addons mechanism. For exporters, we should have an API that allows the exporter to indicate if it supports multiple-flow export, or only single-flow export.

**Comment by worldmind** [comment]
+ official mitmproxy image must contain the har_dump.py

**Comment by abitrolly** [comment]
From @mhils comment https://github.com/mitmproxy/mitmproxy/issues/3377#issuecomment-772498082 to not lose it.

1. Move the HAR addon out of `contrib` into `mitmproxy/addons/har_export.py`.
2. Instead of writing the HAR file to disk in `done()`, write a `har.export` command similar to `safe.file @shown foo.mitm`: 

https://github.com/mitmproxy/mitmproxy/blob/578514d4f2193468f25ab2c3a5de6e8f445a1c40/mitmproxy/addons/save.py#L63-L77

3. `typing.Sequence[flow.Flow]` can be used for multiple flows.

**Comment by zanieb** [comment]
Looks done in https://github.com/mitmproxy/mitmproxy/pull/6368 and https://github.com/mitmproxy/mitmproxy/pull/6335?

**Comment by mhils** [comment]
Thanks @zanieb! 🍰
