### ISSUE TITLE
Improve mitmdump's memory usage

### ISSUE THREAD

**Issue by Schamper** [mitmproxy/mitmproxy#1519]
##### Steps to reproduce the problem:

1. Start mitmdump/own proxy similar to [this example](https://github.com/mitmproxy/mitmproxy/blob/master/examples/flowbasic). Note that in the "own proxy" the flow was also deleted, similar to mitmdump.
2. Start browsing (a lot).
3. Observe memory usage growing steadily with each request, reaching multiple GBs within a couple minutes, never coming back down.

##### What is the expected behavior?

Memory usage should ideally stay relatively the same over time.

##### What went wrong?

Memory is being held hostage somewhere.

##### Any other comments? What have you tried so far?

I'm also using a modified version of the `har_dump` script, but it doesn't matter if I have it enabled or disabled, suggesting the issue is somewhere in mitmproxy.

Tried inspecting heap memory using `guppy`, but I've never really used it so I didn't get very far with it. Printing the summary using guppy/other similar memory inspection libraries show that an insanely high number of `dict` and `str` objects are kept in memory, which seem to never stop growing. 

I've tried digging into the source of mitmproxy but I'm not too familiar with it so I'm not able to pinpoint where the issue might be. 

---

Mitmproxy Version: master (0.18)
Operating System: Ubuntu 16.04

**Comment by dufferzafar** [comment]
We have quite a few similar memory related issues: #1036, #844, #620, #484.

**Comment by cortesi** [comment]
We DO have memory leaks we need to deal with, but in this case the problem is us being unclear about what the proxy module is actually doing. By default, flow.State will accumulate ALL flows in memory without ever purging anything. This is something we want for interactive proxies like mitmproxy console (though we plan to shed this to disk in sqlite real soon now), but it's a perverse behaviour for the proxy example linked above and for mitmdump itself (which does extra work to explicitly purge flows from memory). 

I suggest the following:

- We rename flow.State to flow.InMemoryState (or similar).
- We implement flow.NullState which doesn't do any un-necessary accumulation in memory. Everything gets consistently purged as soon as we no longer need it. 
- We modify mitmdump to use NullState, and modify the example scripts to do the same. 

This work would also involve clarifying exactly what the minimal State interface should look like to prepare us for the shift to sqlite.

**Comment by cortesi** [comment]
There's been some significant progress on this issue:

- We've added debug functionality that dumps a record of objects in memory so we can track object leaks.
- We've implemented the stub state functionality, and saw a huge reduction in leaked state objects.
- We've capped the size of the in-memory certificate store, which previously grew infinitely.

I'm pretty confident that these three changes together eliminate all the mitmdump-related memory leaks that we ourselves are responsible for. I still observe (much slower) memory growth over time, so I suspect that one or more of the libraries we depend on has issues too. We'll track those down as part of the next release cycle.
