### ISSUE TITLE
Mitmproxy CLI tools

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#1526]
Similar to #1521, I'd like to open a discussion about the mitmproxy command line interface tools:
At the moment we have three core applications:
- `mitmproxy` - a curses-based terminal UI / "frontend" to inspect, manipulate HTTP flows, etc.
- `mitmdump` - basically only the proxy part of `mitmproxy`, without any interaction or "frontend"
- `mitmweb` - serves a similar use case as `mitmproxy`, but through a HTTP-JS "frontend"

Since the main project is called `mitmproxy`, as well as the GitHub organisation, and the main repository, it was always a bit unintuitive how the actual binaries are called.

Therefore I'd like to propose that we change the naming of the three main applications (i.e. the words we type into our terminal to start one of the three "frontends") to:
- `mitmproxy` - same as before, starts the curses-based UI
- `mitmproxy dump` behaves as the old _mitmdump_
- `mitmproxy web` behaves as the old _mitmweb_

Now, in this case the first argument would determine the frontend to be started. By default (i.e. without a first argument) the curses-based frontend should be started. However, we could also change that, if we detect we are running without a tty (or the screen is too small) and simply fallback to _dump_ mode. 

Or maybe instead of introducing a new argument, we could use `mitmproxy-dump` and `mitmproxy-web` as binary names. This probably requires one or two more keystrokes to autocomplete though.

For backward compatibility we should still ship the old binaries as well -and add a notification about the rename, so users can adapt their aliases / workflows / scripts.

What do you think?
I'm open for other naming conventions or even completely different names. 😄 

/cc @mitmproxy/devs

**Comment by cortesi** [comment]
Let's think this through. Our options are: 

1. Keep the status quo: mitmproxy (console), mitmweb and mitmdump. Awkward, but reflects the reality that right now mitmproxy console is by a wide margin what most people use. 
2. Be logically consistent. Because console mode is not supported on some platforms, just having it as the default doesn't really work. This gives us "mitmproxy console", "mitmproxy web" and "mitmproxy dump". I don't like the guessing of looking at the tty to determine what to fire up, so I'd like to be explicit. So just running mitmproxy would list the tools and exit. 
3. Rename the mitmproxy binary to better reflect the fact that the project is not just about the terminal. All the options here are a bit ugly: "mitmconsole", "mitmterm"?
4. mitmproxy-console, mitmproxy-web, mitmproxy-dump. I don't like this one. 


There are a few other benefits I can think of for option 2:

- Producing a single binary would cut distribution sizes by two thirds. Not certain how significant this is at the moment, but would be a nice side-effect. 
- This opens ops the possibility of adding more commands. For instance "mitmproxy convert" to convert from mitmdumps to other formats is something I've occasionally wanted. Very soon now, we're going to have the ability to upload mitmdumps for viewing online (I just need to clear time to work on this), so "mitmproxy share" might be another one.

Let's wait for other folks to chip in on this, but tentatively I think the proposal makes sense. We can't make this sort of change often, though, so let's proceed cautiously.

**Comment by mhils** [comment]
Another aspect we should consider here is that we ideally ship mitmweb with
an Electron/cefpython wrapper further down the track. At that point, the
whole "web" naming does not even make sense to the user anymore and we'd
have to introduce new changes again. It may make sense to wait until we
have a clear picture of that (which platforms, portable binaries or
installers, ...?) before we start renaming stuff.

What I would dislike about option 2 is that it bloats up *every* current
console command. This would also require a command line interface for
invoking any of the tools (unless we ship installers/do $x to have useful
shortcuts). As anecdotal evidence, I've seen OSX users that aren't too
accustomed to CLI apps and just double-click on the mitmproxy binary. Not
our core audience, but we should keep in mind that this is just the tip of
the iceberg if we support Windows properly with mitmweb.

I'd like to throw in option 1b for consideration: De-emphasize the mitmweb
binary name (I could imagine having an installer that creates a "mitmproxy
ui" shortcut linking to mitmweb) and continue living with mitmproxy and
mitmdump.

Right now, I would lean towards figuring out mitmweb's distribution target
audience and user share first, even though that may still take a bit.

**Comment by cortesi** [comment]
I'm pushing this one out beyond 1.0 - we don't need to make a decision now. I agree that making "normal" invocations harder is something to be concerned about - on Unixen we can go some way towards getting the benefits of multiple binaries with symlinks and then looking at the invocation binary name. I also feel that whatever the future of mitmweb, it should remain an option to run it outside of Electron. This is useful when, for instance, running on a headless device and debugging remotely.
