### ISSUE TITLE
Question: speeding up Construct

### ISSUE THREAD

**Issue by arekbulski** [mitmproxy/mitmproxy#1536]
Would this project benefited if Construct was moved to using Cython? I am the maintener.

**Comment by mhils** [comment]
Thanks for getting in touch! :smiley: 

In my opinion this would be one of the "nice to have" features, but for mitmproxy it's not actually a big issue - we usually do two TLS handshakes afterwards, which is way more costly.

I see that this move may make sense for construct in general to some extend. From our point of view, it would be very welcome if Cython compilation stays optional or construct provides precompiled wheels for all major platforms. Be warned though that the latter is often a pain in the ass, and it may make sense to focus on other features first. :smiley:

I'm closing this for now, if anyone else wants to chime in, please do!

**Comment by arekbulski** [comment]
Remember that cython is only implementation details. Construct classes and methods remain python methods. Nothing changes for you except speed and added requirement package.

**Comment by mhils** [comment]
> Nothing changes for you except speed and added requirement package.

So, the problem here is that we have a lot of users who `pip install mitmproxy`. If that breaks on Linux, OSX or Windows (or requires more steps), that'd be a major inconvenience for us and we'd probably stay on an older construct version/vendorize it.

We can't expect a compiler on Windows, so the two options you have is (1) make compilation optional or (2) provide precompiled wheels.
 
Does that make sense? :blush:

**Comment by arekbulski** [comment]
That is a good explanation. No gcc on windows. I may create a new release major for that and still maintain previous one.
