### ISSUE TITLE
Only show requests coming to interested 

### ISSUE THREAD

**Issue by hoangphuoc25** [mitmproxy/mitmproxy#1741]
Is there anyway to log only requests coming to an URL of my interest? Currently there's an option to do exactly the opposite of that (`--ignore`). Our app sends a lot of requests to third party services for ad/app tracking and I just want to see what requests the app sends to our server.

**Comment by cortesi** [comment]
Hi there. What you want is filter patterns, which allow you to show or save only precisely what you specify. The filter expressions are documented here:

http://docs.mitmproxy.org/en/stable/features/filters.html

So, for mitmproxy console, you'd pass this this with the -f flag. For mitmdump, it's the first command argument.

In future, could you please ask usage questions of this sort in the forums rather than the bug tracker:

https://discourse.mitmproxy.org/

**Comment by hoangphuoc25** [comment]
Thanks for quick response

**Comment by Kriechi** [comment]
I'll open this again - because this isn't mentioned in the `mitmdump -h` help text.

**Comment by dwfreed** [comment]
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/cmdline.py#L845 just needs a help

**Comment by paliitr** [comment]
@Kriechi @dwfreed Is the issue related to having the filter command docs in the help option from commandline?

**Comment by Kriechi** [comment]
Ah sorry - I forgot to close this issue when we merged https://github.com/mitmproxy/mitmproxy/pull/1792.
