### ISSUE TITLE
mitmproxy update breaks global state

### ISSUE THREAD

**Issue by escitalopram** [mitmproxy/mitmproxy#1744]
I have an application where I need to count incoming requests, and I use global variables for that, like

    myVariable=0
    
    def responseheaders(flow):
        #do something asynchronously and update myVariable

Which stopped working when I updated to 0.18.x, because it initializes myVariable over and over for each request :(

In case this is not a bug, what would the new designated facility to keep global state instead of global variables be?

**Comment by cortesi** [comment]
You don't give a complete example, so I can't quite tell where things are going wrong. The old, and awkward way to do this is like so:

```python
var=0
def responseheaders(flow):
    global var
    var += 1
    print(var)
```

However, our addons mechanism has recently had a big facelift, and you can now do something much nicer by using an addon class:

```python
class Addon:
    def __init__(self):
        self.count = 0

    def responseheaders(self, flow):
        self.count += 1
        print(self.count)


def start():
    # We boot into an addon returned from start
    return Addon()
```

In future, would you mind asking questions like this on our excellent forum so others can benefit from the answers, rather than having them disappear into the ether when we close the ticket:

https://discourse.mitmproxy.org/

**Comment by mhils** [comment]
> Which stopped working when I updated to 0.18.x, because it initializes myVariable over and over for each request :(

If it actually re-initializes with `myVariable=0` "all the time", that's a bug. In this case, we'd need a complete example to reproduce. :-)

**Comment by escitalopram** [comment]
Ok, I tried to create a minimal example, but it works as supposed. Probably it was a problem transitioning from python 2.7 to 3.
