### ISSUE TITLE
Cannot open example.com

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1754]
##### Steps to reproduce the problem:

1. `curl -x localhost:8080 example.com`
2. Receive 400 - Bad Request response

##### Any other comments? What have you tried so far?

39589404209a9980c0a07137f367f70c103e3113 is the first bad commit

##### System information

Mitmproxy version: master

**Comment by mhils** [comment]
I believe this is due to [this](https://github.com/mitmproxy/mitmproxy/commit/39589404209a9980c0a07137f367f70c103e3113#diff-1a48d22b11223fa300cac1e75cbcfafcL178). @cortesi, why is that out?

**Comment by cortesi** [comment]
Let's start using pathoc for these self-contained reproductions - I've noticed that our versions of curl often do different things. In this case, my curl promotes the URL silently to http://example.com, and things work. I see what you see with pathoc:

    > pathoc localhost:8080 get:google.com
    >> 'GET':google.com
    << 400 Bad Request: 207 bytes

I took that out because a) changing the first_line_format attribute deep in the proxy core seems like categorically the wrong thing to do, b) removing it didn't break any unit tests, and c) I don't see the rationale for this. Maybe you can fill me in?

**Comment by mhils** [comment]
> c) I don't see the rationale for this. Maybe you can fill me in?

If a HTTP proxy receives a `GET http://example.com/ HTTP/1.1` request line, it is expected to forward this as `GET / HTTP/1.1`. IIRC this is not in any of the RFCs, but a lot of servers (e.g., example.com) fail when presented with an absolute-form request.
