### ISSUE TITLE
macOS Sierra brew install error

### ISSUE THREAD

**Issue by askie** [mitmproxy/mitmproxy#1795]
macOS Sierra brew install :

brew install mitmproxy

error:

==> Installing mitmproxy
==> Downloading https://mitmproxy.org/download/mitmproxy-0.14.0.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "mitmproxy"
Download failed: https://mitmproxy.org/download/mitmproxy-0.14.0.tar.gz

**Comment by Kriechi** [comment]
Please update your brew and taps. mitmproxy 0.18.2 is the most recent version.
We recommend using the provided binaries on macOS: http://docs.mitmproxy.org/en/stable/install.html#installation-on-mac-os-x
We are not involved with the homebrew formula for mitmproxy.

**Comment by krokofant** [comment]
@Kriechi As of now it's written as the primary install method for macOS so I don't understand where this recommendation comes from. Care to elaborate?

**Comment by Kriechi** [comment]
Which recommendation?
The way we create mitmproxy releases has changes significantly in the last months.

**Comment by krokofant** [comment]
The recommendation to install it via the binaries instead of with homebrew.

I was looking to install the latest version 🚀  which isn't yet added to the homebrew-formula. I thought I might provide a PR to update that formula but the dependencies threw me off. I thought about creating an issue here asking for help with this at which point I read your comment about:

> We are not involved with the homebrew formula for mitmproxy

Along with

> We recommend using the provided binaries on macOS

... which lead me to be confused as to how to go about things.

**Comment by Kriechi** [comment]
Yes - as it says. We are not maintaining the homebrew formula, but the nice folks from the homebrew community usually have an update ready within a day or two of our release.

AFAIK the actual formula file is kinda auto-generated, so there is a tool in homebrew-land which takes care of extracting our dependencies and transforms that in a formula template (of some sort). For more details please ask somebody in the homebrew community.
