### ISSUE TITLE
flow.request.urlencoded_form does not work with Unicode parameters in Python 3

### ISSUE THREAD

**Issue by rofreg** [mitmproxy/mitmproxy#1858]
##### Steps to reproduce the problem:

1. Save the following as `test_script.py`:
```
import mitmproxy
import json

def request(flow):
  if flow.request.urlencoded_form:
    mitmproxy.ctx.log(str(flow.request.urlencoded_form))
  else:
    mitmproxy.ctx.log("No form parameters found")
```
2. Launch `mitmdump` with `mitmdump -s test_script.py`
3. Point your browser to `https://secure.splitwise.com/login`, and try to log in with any username or password (don't worry, you don't need an actual account)

The expected behavior is for `flow.request.urlencoded_form` to return a list of form parameters that includes `('utf8', '✓')` (or `(b'utf8', b'%E2%9C%93')`). Instead, `flow.request.urlencoded_form` returns no parameters at all, because it throws an exception trying to process the Unicode `✓` symbol that is included in the form.

##### Any other comments? What have you tried so far?

A semi-working fix is to update [this line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/http/request.py#L363) to the following:
```
return tuple(mitmproxy.net.http.url.decode(str(self.content)))
```
It appears that `mitmproxy.net.http.url.decode` chokes when trying to process a parameter of the `bytes` type, but it succeeds when processing a parameter of the `str` type. Unfortunately, this also changes the type of the returned tuples from `bytes` to `str`, which probably isn't backwards-compatible with existing usage of mitmproxy. Not sure if there's an easy way to fix that – I plan to keep investigating, but if anyone has suggestions or expertise, I'd appreciate the help!

##### System information

```
Mitmproxy version: 0.19
Python version: 3.5.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.1 ('', '', '') x86_64
```

/cc @jhottenstein

**Comment by mhils** [comment]
Thanks for the excellent report!
The root cause of this is the following:
```python3
>>> import urrlib
>>> urllib.parse.parse_qsl("foo=bar&baz=%E2%9C%93", keep_blank_values=True, errors='surrogateescape')
[('foo', 'bar'), ('baz', '✓')]

>>> urllib.parse.parse_qsl(b"foo=bar&baz=%E2%9C%93", keep_blank_values=True, errors='surrogateescape')
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    urllib.parse.parse_qsl(b"foo=bar&baz=%E2%9C%93", keep_blank_values=True, errors='surrogateescape')
  File "C:\Python35\lib\urllib\parse.py", line 628, in parse_qsl
    value = _coerce_result(value)
  File "C:\Python35\lib\urllib\parse.py", line 94, in _encode_result
    return obj.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 0: ordinal not in range(128)
```

This seems surprising to me, but who am I to judge. :-)

After looking around a bit, your proposal of returning text instead of bytes seems to be the way to go (see: http://stackoverflow.com/a/4073451/934719). While we could implement our own parse_qsl that just works on bytes, browsers apparently always use mutipart/form-data for binary files (see linked SO page), so text is the more elegant API anyway. If you want to send a PR that changes the default behaviour, briefly notes this in the doc string and dass a quick test, I'd be happy to merge that right away! :smiley:

Minor nitpick: If you send a PR: please use `self.content.decode()` instead of `str(self.content)` - that makes clear that there always is a strict ascii decode operation.

Thanks again!

**Comment by mhils** [comment]
I'll quickly take this over to have it in 1.0!

**Comment by rofreg** [comment]
Awesome, thank you! Looking forward to 1.0, and I hope to contribute in the future :)
