### ISSUE TITLE
[web]: body filter expressions are not working

### ISSUE THREAD

**Issue by wdormann** [mitmproxy/mitmproxy#1915]
##### Steps to reproduce the problem:

1. Run mitmweb
2. In one of the "Start" boxes, start to type each of the filter expressions.   e.g. "~b asdf"

##### Any other comments? What have you tried so far?

I realize that mitmweb is beta, but the documentation indicates "We consider it stable for all features currently exposed in the UI", so maybe this is an oversight.  Filter expressions that cause the error: "SyntaxError: Expected filter expression but "~" found" include:
~b
~bq
~bs
~dst
~http
~marked
~src

##### System information

Mitmproxy version: 1.0.1
Python version: 3.5.2
Platform: Linux-3.13.0-100-generic-i686-with-debian-jessie-sid
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: debian jessie/sid

**Comment by mhils** [comment]
Thanks! It seems like these got out of sync, this needs to be fixed.

**Comment by s4chin** [comment]
Adding the missing filters as reference:
- [ ] `~b`
- [ ] `~bq`
- [ ] `~bs`
- [ ] `~dst`
- [ ] `~http`
- [x] `~marked`
- [ ] `~src`
- [ ] `~tcp`

**Comment by mhils** [comment]
Thanks. As mentioned on Slack, let's keep the body filters out for now and do the others first. :)

**Comment by keymandll** [comment]
Gents, so no chance I could get ~bs filter working still?

**Comment by mhils** [comment]
Unfortunately it's not really trivial as we do not transmit body contents to the front end - see https://github.com/mitmproxy/mitmweb/issues/10.

I'm closing this here as this issue is actually tracked in https://github.com/mitmproxy/mitmweb/issues/10!

**Comment by pravic** [comment]
I am not sure whether I should open a new issue here, in mitmproxy/mitmweb or do not open it at all (because of the comment above).

Anyway, right now an attempt to use a body filter will navigate browser to another location with an empty page.

To rephrase, 

1. Open some flow
2. Click on Highlight field, type `~b` (you will get an error about an expected filter expression)
3. Try to type something, e.g. `~b body`. You will immediately be redirected to `http://127.0.0.1:8081/#/flows?h=~b%20s` which is completely empty [*].
4. The back button (in browser) does not work, 

[*] Well, not really empty but it looks empty. The page source is

```html
<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>mitmproxy</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/vendor.css"/>
<link rel="stylesheet" href="/static/app.css"/>
<link rel="icon" href="/static/images/favicon.ico" type="image/x-icon"/>
<script src="/static/static.js"></script>
<script src="/static/vendor.js"></script>
<script src="/static/app.js"></script>
</head>
<body>
<div id="mitmproxy"></div>
</body>
</html>
```

And there was an error which can be seen in the browser console:

> ReferenceError: True is not defined
    at t (app.js:206)
    at app.js:47
    at Array.map (<anonymous>)
    at e.value (app.js:47)
    at d (vendor.js:123)
    at c (vendor.js:123)
    at x (vendor.js:123)
    at u (vendor.js:123)
    at p (vendor.js:123)
    at h (vendor.js:123)

**Comment by arya6000** [comment]
https://github.com/mitmproxy/mitmweb/issues/10 has been archived. Are there still plans to add the filter?
