### ISSUE TITLE
support reverse proxy to a unix socket

### ISSUE THREAD

**Issue by vikstrous** [mitmproxy/mitmproxy#1936]
For debugging docker things I use the following method in 3 shells right now:

```
socat tcp-listen:3000,bind=127.0.0.1,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock
```
```
mitmproxy -R http://localhost:3000 -p 3001
```
```
export DOCKER_HOST=127.0.0.1:3001
docker service ps 53pr4a3e2zkj
```

It would be really cool if mitm proxy supported acting as a reverse proxy to a unix socket. That would remove the need for the socat. I imagine it working like this:

```
mitmproxy -R unix:///var/run/docker.sock -p 3001
```

**Comment by mhils** [comment]
Thanks for the suggestion. What would we need to do to support this? :)

**Comment by Kriechi** [comment]
Is opening the socket like this enough?
```python
url = 'unix:///var/run/docker.sock'
if url.startswith('unix://'):
    s = socket.socket(socket.AF_UNIX)
    s.connect(path)
    # use socket as usual: s.send(...)

**Comment by vikstrous** [comment]
Yeah, it should be pretty simple IMO

**Comment by mhils** [comment]
The relevant bits are [here](https://github.com/mitmproxy/mitmproxy/blob/86174eb6adfb83de6ba4dfbcff73ee9cb18ac4aa/mitmproxy/net/tcp.py#L746).
We'd be happy to accept a well-written PR for this, but we're focusing on other things currently. I'm closing this for now - if it turns out there's significant interest from others, we're happy to reconsider that decision.

**Comment by kyle-cackett** [comment]
I'm in search of a reverse proxy capable of sending http requests to a Unix socket and am considering taking this bit of work on.

@mhils It looks like the code has changed substantially since 2017 and that the method and file referenced in the comment above no longer exists. Do you have any updated pointers that may help me to implement this feature today?

**Comment by mhils** [comment]
We now use asyncio, the relevant bits are around here: https://github.com/mitmproxy/mitmproxy/blob/a51dc10d8b97d46c77d11a4bbb4d0c393b2c8a39/mitmproxy/proxy/server.py#L153

**Comment by colin-higgins** [comment]
Did anything ever come of this? The issue was closed but I don't see relevant code?
