### ISSUE TITLE
Trying to run libmproxy code for Python 3

### ISSUE THREAD

**Issue by Parth-Vader** [mitmproxy/mitmproxy#2061]
The file had been using libmproxy (version 0.10) :- 
   

    from libmproxy import controller, proxy
   
    class HTTPSProxy(controller.Master, Thread):

    def __init__(self, port):
        password_manager = http_auth.PassManSingleUser('scrapy', 'scrapy')
        authenticator = http_auth.BasicProxyAuth(password_manager, "mitmproxy")
        cert_path = os.path.join(os.path.abspath(os.path.dirname(__file__)),
            'keys', 'mitmproxy-ca.pem')
        server = proxy.ProxyServer(proxy.ProxyConfig(
            authenticator = authenticator,
            cacert = cert_path),
            port)
        Thread.__init__(self)
        controller.Master.__init__(self, server)
`

I want to run the code with python3, so I installed `mitmproxy v0.18.2` and replaced `libmproxy` with `mitmproxy`.
How can I implement `libmproxy.controller` and `libmproxy.proxy` with `mitmproxy`?

I'm using Ubuntu 16.04.
Also. doing `mitmproxy --version` gives `ImportError: No module named 'mitmproxy.tools'`.

**Comment by Kriechi** [comment]
Please use the latest release of mitmproxy: `v2.0.0`.
As you can imagine, things changed significantly since `v0.10` - so this might not be as easy as just renaming a few imports...
Also make sure to uninstall all older versions and maybe also remove `netlib` if you still have that installed, netlib was integrated into the mitmproxy package.

**Comment by Parth-Vader** [comment]
@Kriechi Thanks for the advice.

If possible, can you please tell what are new implementations of `libmproxy.controller` and `libmproxy.proxy`?

I have looked at the `docs` but couldn't identify it.

**Comment by mhils** [comment]
I recommend to rewrite whatever you have to use our new scripting API:
http://docs.mitmproxy.org/en/stable/scripting/overview.html

Subclassing controller.Master is not recommended.

On Sat, 25 Feb 2017, 12:12 Parth Verma, <notifications@github.com> wrote:

@Kriechi <https://github.com/Kriechi> Thanks for the advice.

If possible, can you please tell what are new implementations of
libmproxy.controller and libmproxy.proxy?

I have looked at the docs but couldn't identify it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mitmproxy/mitmproxy/issues/2061#issuecomment-282477324>,
or mute the thread

**Comment by WHK102** [comment]
Howto implement in python script without mitmproxy command?, i have an application that at the time of starting the proxy service starts the mitmproxy through the libmproxy library, when I migrate to python3 I will have to call a mitmproxy from a fork taking care with the different types of operating systems.

The main idea of using libraries in python is not having the need to call a system command like cat, sed, grep, etc.
