### ISSUE TITLE
Mitmproxy asking for a UTF console

### ISSUE THREAD

**Issue by karthikbhata97** [mitmproxy/mitmproxy#2218]
##### Steps to reproduce the problem:

1. Run mitmproxy on the machine with non UTF console environment

Error message:
```
Error: mitmproxy requires a UTF console environment.
Set your LANG enviroment variable to something like en_US.UTF-8
```

##### Any other comments? What have you tried so far?
For the first timers it is a bit confusing (I have en_IN language)
Because one can't view anything (say options, version etc)
Maybe choosing one from the existing UTF languages on the machine would be nice.
Need your suggestions.

##### System information

Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment]
Not sure why we do this at all, this decision predates me. @cortesi?

**Comment by Kriechi** [comment]
We accept any UTF encoding - `en_US`, `en_IN`, or anything else.
https://github.com/mitmproxy/mitmproxy/blob/020e5a5c95f7de093e89c046ff4e34d2d02dcd93/mitmproxy/tools/main.py#L23-L36

Unfortunately we cannot setup this for you, the user has to configure the terminal & environment properly.

**Comment by techathena** [comment]
I figured a lot of new users who are not familiar with the code are finding it an issue when they try installing mitmproxy without the same,especially new Linux users who are not very familiar with the variables might find it strange.So adding a simple note or instruction in the installation docs would help a lot .Would be great if this issue is assigned to me since I am working on it .
