### ISSUE TITLE
Transparent mode failure: Runtime Error (could not resolve original destination) OS Sierra

### ISSUE THREAD

**Issue by pgeorgan** [mitmproxy/mitmproxy#2308]
##### Steps to reproduce the problem:

1. Followed these steps [http://mitmproxy.org/doc/transparent/osx.html](url)
2. `mitmproxy -T --host`
3. 

##### Any other comments? What have you tried so far?

Everything has worked smoothly up until this point. Traffic is not reaching its original intended target, so all my apps are acting as if they have no internet connection when I attempt to snoop their traffic. 

`sudo pfctl -s nat` 
No ALTQ support in kernel
ALTQ related functions disabled
nat-anchor "com.apple/*" all
rdr-anchor "com.apple/*" all
rdr on en1 inet proto tcp from any to any port = 80 -> 127.0.0.1 port 8080
rdr on en1 inet proto tcp from any to any port = 443 -> 127.0.0.1 port 8080

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.1
Platform: Darwin-16.5.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.4 ('', '', '') x86_64

**Comment by mhils** [comment]
Did you configure your devices to use an HTTP proxy?

**Comment by pgeorgan** [comment]
If you mean did I follow this [http://jasdev.me/intercepting-ios-traffic](url), then yes.

**Comment by mhils** [comment]
If you have configured your clients to use mitmproxy, you do not need to run mitmproxy as a transparent proxy. Simply running `mitmproxy` (without the `-T` and iptables rules) should work. http://docs.mitmproxy.org/en/stable/modes.html

**Comment by pgeorgan** [comment]
I guess I'm a bit confused then. I have run it without the `-T` option, but then all I see are `GET` requests and nothing else. Additionally, all my iOS apps fail to load. When I run `mitmdump`, I keep getting

`XXX.XXX.X.X:XXXXX: clientconnect
XXX.XXX.X.X:XXXXX: CONNECT graph.facebook.com:443
 << Cannot establish TLS with client (sni: graph.facebook.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)",)
XXX.XXX.X.X:XXXXX: client disconnect`

**Comment by pgeorgan** [comment]
P.S. for the record I am not explicitly executing any `iptable` commands, as I am not using Linux.

**Comment by pgeorgan** [comment]
Am currently looking for port-forwarding solution here [https://apple.stackexchange.com/questions/230300/what-is-the-modern-way-to-do-port-forwarding-on-el-capitan-forward-port-80-to/230331#230331](url)

Perhaps mitmproxy.org's instructions were just a guideline. Though, the solution being offered in that link is substantially more involved.

**Comment by mhils** [comment]
For the most simple use case, you want to do this: http://docs.mitmproxy.org/en/stable/modes.html#regular-proxy - no iptables or port redirection involved.

The error message you are seeing ` 'sslv3 alert certificate unknown'` - hints that your client does not trust the proxy's interception certificate. This could either be because you did not install it or because the app employs certificate pinning: http://docs.mitmproxy.org/en/stable/certinstall.html#certificate-pinning

**Comment by mdavids** [comment]
I seem to have the same problem. In transparent mode (-T), mitmproxy 2.0.2 on OSX does not go into SSL-mode. This results in an 'SSL protocol error' on the clientside. I need transparent mode though. Because without it, it goes into 'proxymode', resulting in: "expected: authority or absolute, got: relative", which makes sense because the client has no proxy-server configured but is diverted to mitmproxy in another way. So it does relative GETs. 

So, why doesn't -T result in an SSL-connection? Would be interesting to know...

**Comment by mhils** [comment]
> does not go into SSL-mode

It usually does - this works fine for me on Windows and others on OSX. Can you please open a new issue with some more details on your configuration? In particular, which client devices/applications have you tried?
