### ISSUE TITLE
Improve mitm.it

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2313]
We should do a better job at our magic cert install page `mitm.it`:

1. Add additional OSes/software to the list, e.g. Firefox.
2. Open more specific instructions when an Icon is clicked. For example, the Apple instructions should be shown after clicking on "Apple", and should also include the info from the docs: https://github.com/mitmproxy/mitmproxy/pull/2312

**Comment by Ritiek** [comment]
@mhils +1 on this. Do you mind if I take on this?  I don't have much experience with web development so it might take me a week or so but I am ready to give a shot, if you're okay with that.

**Comment by mhils** [comment]
Hey, sure! Please go ahead and take your time. :-)

**Comment by Ritiek** [comment]
I tried going through the code base but I am not sure how one can add support for more OSes and softwares.. Any ideas?

**Comment by Kriechi** [comment]
We probably need to differentiate between OS and browser:

* Safari on macOS uses the macOS keychain. So installing our CA in the system is enough.
* Chrome on macOS uses the macOS keychain. So installing our CA in the system is enough.
* Firefox on macOS has its own CA store and needs to be installed with Firefox-specific instructions.
--------------------------
* Chrome on Windows?
* Firefox on Windows?
* Edge and IE use the Windows CA store. So installing our CA in the system is enough.
--------------------------
* Chrom/ium on Linux?
* Firefox on Linux?
--------------------------
* Chrome on Android?
--------------------------
* Safari on iOS?

**Comment by 7mp** [comment]
Should we add an extra note for iOS 10.3 users since they need to do some extra work [to trust the root certificate installed by the profile](https://www.thesslstore.com/blog/trust-manually-installed-root-certificates-in-ios/)? 

To paraphrase the linked article:

1. After certificate installation, open **Settings**.
2. Navigate to **General** and then **About**.
3. Select **Certificate Trust Settings**.
4. Each root that has been installed via a profile will be listed below the heading **Enable Full Trust For Root Certificates**. Toggle `mitmproxy` on.

**Comment by mhils** [comment]
Generic answer: If you think that improves mitm.it, go for it! In your specific case, that definitely seems to hold true. I'd also be happy about a PR that adds a dedicated iOS button. 😃 

https://github.com/mitmproxy/mitmproxy/tree/master/mitmproxy/addons/onboardingapp/templates
