### ISSUE TITLE
Attempting a Connecting on Snapchat through iOS 10.2 throws TLS error. I assume its SSL?

### ISSUE THREAD

**Issue by DominikMC** [mitmproxy/mitmproxy#2434]
##### Steps to reproduce the problem:

1. Connect to mitmproxy through your phone.
2. Install Certificate through Safari
3. Attempt to open Snapchat causing failure.

##### Any other comments? What have you tried so far?

I'm brand new to project so maybe I might have missed something. So far I've gotten everything up and running (most connections work through safari). Here is a log from the console:
```
Proxy server listening at http://0.0.0.0:8080
192.168.1.6:53270: clientconnect
192.168.1.6:53270: CONNECT app.snapchat.com:443
 << Cannot establish TLS with client (sni: app.snapchat.com): TlsException("(-1, 'Unexpected EOF')",)
192.168.1.6:53270: clientdisconnect
192.168.1.6:53271: clientconnect
```
Thanks for any help beforehand!

##### System information
```
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.3
Platform: Windows-10-10.0.15063
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 10 10.0.15063  Multiprocessor Free
```

**Comment by mhils** [comment]
If other HTTPS sites work, you are presumably running into [Certificate Pinning](http://docs.mitmproxy.org/en/stable/certinstall.html#certificate-pinning). Is that the case?

**Comment by YngveMolnes** [comment]
Snapchat is indeed pinning public keys. If you decompile the app and just search for them with either grep og ag you can find them.

**Comment by mhils** [comment]
Thanks, @YngveMolnes!

**Comment by dylib** [comment]
@mhils: Hello, regarding Certificate Pinning on iOS — In the documentation it says:

> If you want to intercept the pinned connections, you need to patch the application manually. For Android and (jailbroken) iOS devices, various tools exist to accomplish this.

I'm not aware of any jailbreak iOS 11 (?). If you have any information that might set me on the right path toward that goal it would be extremely helpful. While trying to debug iOS apps that use certificate pinning it's completely killed any possible means for that happening. 

~ Thank you!

**Comment by DominikFX** [comment]
@dylib As of today, with no iOS 11 jailbreak, I did manage to find a way to intercept and decrypt Snapchat traffic and take down their certificate pinning. I have not put much work into this but to accomplish this I downloaded an android emulator called "MEmu" and rooted it. To open it up further I installed Xposed (took a few tries) and with it a package called "SSLUnpinng". I set up Charles Proxy and connected the Emulator to intercept the traffic. I got up all the way to a point where everything, including SSL traffic, is decrypted but shortly ran into a problem where the client would not let me log in since it would send a "google device validation" request and consider the device as unauthorized. I have left the process at where it is right now for a while but I do plan on getting back to working on it. 

Hope this helps you in some type of way and please do let me know if you find out anything more or have questions in general. 

Thank you.

**Comment by YngveMolnes** [comment]
@DominikMC what kind of data did you get? I was able to get tons of analytics data as json and some protobuf-requests. Snapchat sure did a decent job.
