### ISSUE TITLE
Feature: warn/confirm if file exists when using `-w`

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#2555]
I just ran `mitmproxy -w existing-file` and `existing-file` was overwritten with a 0 byte file. I guess it's my fault that I lost the session I recorded earlier, but I also believe mitmproxy (and ever other CLI) should catch user errors if possible. I don't know if this can be added in a backwards-compatible manner, because existing scripts might launch mitmproxy and don't expect a confirmation message when a file already exists. Anyway, I thought I'd ask what you think (basically I'm just sad I lost the file and wanted to share my loss :D).

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.3
Platform: Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 17.04 zesty

**Comment by mhils** [comment]
Thanks for the feedback - I agree that loosing data is unfortunate, but my understanding is that what we do is pretty much the consensus among UNIX command line tools and prompting would be unexpected. For example, `tcpdump -w existing-file` would also blindly overwrite files. Do you have any examples of notable tools that behave differently in that regard?

**Comment by Prinzhorn** [comment]
> Do you have any examples of notable tools that behave differently in that regard?

I'd probably have to bend backwards to find one. I personally will use `-a` from now on, at least this will prevent the "arrow up + enter" mistake I made. I do have two suggestions though:

1. Make the `STREAMFILE` optional and by default create a file in the cwd with the current timestamp if none exists. E.g. like `mitmproxy-flows-20170901102532546`.
2. Only create/start writing to the file once the first flow arrives. This will also prevent a 0 byte file when you just start mitmproxy and stop it right away without actually using it.

Anyway, these are feature request of lowest priority and won't bring back my beloved flow. It had already grown to 40MB before it left our world. RIP, see you in /dev/null.

**Comment by Prinzhorn** [comment]
For anyone who is interested, I learned my lesson and in addition to my daily backup I now let Back In Time back up the most critical files every five minutes. I have a SanDisk Ultra Fit USB stick which is always mounted.

**Comment by mhils** [comment]
Sorry again. 😢 

Regarding your first feature request, that is tricky as `mitmdump -w foo` could then be interpreted as either "write to a file called foo" or "write to `mitmproxy-flows-20170901102532546` and set the flow filter to foo". I'd be very open to a PR that runs strftime on the filename though. If that's something that you think would be useful, please feel free to open a new issue so that we don't loose track. 😃 

Regarding the second request: Tricky again, as we want to error immediately if we cannot write the file. 

In more positive news, mitmproxy will get a new `save` command, so that you can save selected flows from within mitmproxy with the next release. This allows you to skip `-w` entirely and just save on demand. 😃

**Comment by Prinzhorn** [comment]
Sounds great! As I said above I keep acting like `-w` does not exist and stick with `-a` as it does not have any drawbacks :+1:
