### ISSUE TITLE
Consider marking some commands as "internal"

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2696]
Playing with the command list a bit, I feel that our command list UX could benefit from not showing some commands by default. I feel a new mitmproxy user will be overwhelmed with many internal commands for which they have no immediate use.

Of course, we can add a `show_internal_commands` option for advanced users.

**Comment by cortesi** [comment]
I'm afraid I'm going to resist this one pretty firmly. I dislike the kind of UX that hides complexity under an "Advanced" tab. Also, the command list is *not* intended to be a palette of commands for users to choose from when they're unsure of a keybinding or don't want to manually type a command. Instead, it's a canonical list of all our commands, which users should look at when they want to understand what a key binding does better, want to make their own keybindings, or want to know the syntax for a manual command. 

We can entertain the idea of an actions palette that does what you want. Each action would be a compound command and a description (like a key binding, but without being bound to a key). The actions palette would be presented to the user as an overlay, so that actions would execute in the context of the current window (unlike commands, where the execution context is the command list, which you found confusing). These could be context-dependent using exactly the same mechanism as key bindings, and, in fact, the UI for configuring these could be shared with the key bindings. I'm not sure if adding this would be an additional complexity we might not need, but it's better than trying to bend the commands palette into something it's not.

**Comment by mhils** [comment]
>  Also, the command list is not intended to be a palette of commands for users to choose from when they're unsure of a keybinding or don't want to manually type a command.

Ok - your "not intended to" part is a pretty accurate description of how I perceived it. 😛 My gut feeling would be that many users would interpret it that way initially. Anyways, I follow you overall reasoning. Can we change the Command list window header and the help text to make this a bit more clear? Maybe "[View] Command Reference"?

Action palette: I have to admit that I have a weak spot for that kind of UI, but I don't think we have a pressing need at the moment. Let's focus on shipping 3.0 first and maybe revisit it later.

**Comment by cortesi** [comment]
I've changed the title of the Commands section to "Command Reference", and added a tracking ticket for an Actions pane. Lets discuss during the next cycle.
