### ISSUE TITLE
Docs: Explain New iOS "Certificate Trust Settings"

### ISSUE THREAD

**Issue by jimhigson** [mitmproxy/mitmproxy#2706]
It took a while to work this out and I can't  - installing the certificate on ios (don't know since what version) isn't from http://mitm.it isn't enough - you also need to enable full trust for the root certificate for it to actually work. Otherwise, Safari will ask if you want to go to a site every time and mitmproxy will report handshake errors with the client not trusting it's certificates - it looks like pinned certs but it isn't.

It would be great if you could update the docs with the following. Ideally, this would be mentioned in the html of the page at http://mitm.it or at least somewhere in the mitmproxy docs like maybe [here](http://docs.mitmproxy.org/en/stable/certinstall.html)

On the ios Device need to :

* Install the mitm root cert as usual from http://mitm.it
* Open the **Settings** app
* Tap **General**
* Tap **About**
* Scroll to bottom. Tap **Certificate Trust Settings**
* Turn on the switch for `mitmproxy`

**Comment by mhils** [comment]
Thanks - this is very useful feedback because it addresses a real pain point. In fact, we have already added instructions to mitm.it that will be part of the next release ([src](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/onboardingapp/templates/index.html)). For http://docs.mitmproxy.org/en/stable/certinstall.html, I'd be super happy if someone could send a PR that replaces the linked instructions in the iOS/macOS section with something more useful.

**Comment by jimhigson** [comment]
Sure, I can make a PR. Will close here and open a PR.
