### ISSUE TITLE
Can't run mitmproxy after adding a command without type annotations

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2787]
##### Steps to reproduce the problem:

1. Open `mitmproxy/tools/console/consoleaddons.py`
2. Add arbitrary command without type annotations. For example:
```
    @command.command("console.mycommand")
    def mycommand(self, flow):
        pass
```
3. Try to run mitmproxy. 

Nothing happens. Absolutely. No exceptions, no UI. 

##### Any other comments? What have you tried so far?
If you add a command with type annotations
```
    @command.command("console.mycommand")
    def mycommand(self, flow: flow.Flow) -> None:
        pass
```
everything will work ok.

##### System information

Mitmproxy: 3.0.0.dev0004 (commit 68c32d8) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by kira0204** [comment]
I will look into this ASAP

**Comment by kira0204** [comment]
This is causing the error

https://github.com/mitmproxy/mitmproxy/blob/8dfb8a9a7471e00b0f723de66d3b63bd089e9802/mitmproxy/command.py#L34-L41

I need to look into why are we checking type annotations at runtime before proposing any solution :)

**Comment by cortesi** [comment]
So, the type annotations here are for dynamic command invocations. In the case of the return type, we ensure that the data returned from an addon's command matches the contract of the type annotations. This is a key part of ensuring safety in the command system, and making sure that everything remains composable without weird behaviour. 

We can go two ways here: either require a return type specification and give a proper error if it doesn't exist, or assume a return type of None. I lean (lightly) towards requiring an explicit annotation, since we absolutely require annotations on arguments.

**Comment by kira0204** [comment]
So I was thinking and came up with two solutions
1. Let this `NotImplementedError` stay and catch this [here]() and throw `SyntaxError: missing type annotations in consoleaddons.py`.
2. Instead of `NotImplementedError`, use this `SyntaxError: missing type annotations in consoleaddons.py`,which might not be a pretty way
