### ISSUE TITLE
What happened to Construct?

### ISSUE THREAD

**Issue by arekbulski** [mitmproxy/mitmproxy#2797]
I am the Construct maintainer (but also participate in Kaitai) and wanted to inquire, what happened to Construct? The way I understand, its no longer used in mitmproxy, superseded by Kaitai?

**Comment by mhils** [comment]
Hi @arekbulski!

Thanks for your fantastic work on Construct. I'm sorry to say that we are indeed not using Construct anymore. This doesn't really have anything to do with Construct itself -  this is a side-effect of our efforts to reduce the number of dependencies we have in order to simplify maintenance. We have cut out quite a few dependencies over the last year: lxml, cssutils, jsbeautifier, configargparse, Flask, html2text, watchdog, Pillow, protobuf, and probably some more I'm not remembering. Coming to Construct and Kaitai, it basically boiled down to which was easier to replace for us. As we used Construct for parsing TLS ClientHello packets only and Kaitai for a variety of image formats and protobufs, it was easier for us to replace the little Construct code we had. Please don't let that discourage you, I think there's nothing you could have done better. 🙂 

Cheers,
Max

**Comment by arekbulski** [comment]
Yeah, that is just fine. I was just wondering. :)
PS how do you do that smiley?

**Comment by mhils** [comment]
Glad to hear that. Really nothing personal, we just hate to have too many deps. 
The smiley is `:slightly_smiling_face:` 😃
