### ISSUE TITLE
[Testing]test_xss_scanner.py fails without external communication

### ISSUE THREAD

**Issue by kira0204** [mitmproxy/mitmproxy#2867]
##### Steps to reproduce the problem:

1.  Test your setup by typing `tox` without any internet connection

##### Any other comments? What have you tried so far?

The obvious solution to this problem would be to mock the external communication that is happening [here](https://github.com/mitmproxy/mitmproxy/blob/baf4b5dc03c3b87fbef6e5df422eb7654594978f/examples/complex/xss_scanner.py#L108-L114). This will also make the build slightly faster

##### System information
```
Mitmproxy: 3.0.0.dev1212 (commit 6687d3f) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial
```

**Comment by fristonio** [comment]
Hey, **I would like to work on this issue**. What I got from the description is, during the test when we don't have an internet connection, and we try to get the hostname of a claimed url we still get the `gaierror` exception. When we have a working internet connection, `gethostbyname` waits for a timeout to occur if url is unclaimed, due to which the test slows down. 

The solution you suggested was to mock the external communication for **testing purposes only**. I think that it would be a great idea because as of now tests are slow. But I wonder what would be the best way to mock the communication.
Is there a way we can know we are in a testing environment in `test_xss_scanner.py` If yes then we can have an array storing some URLs we assume to be claimed and during testing can check from that array only rather than using `gethostbyname`. Or we can provide an optional parameter to the `find_unclaimed_URLs` holding this array to check from.

I'm new to the community so not familiar with the protocols here.
Any suggestion from your side would be appreciated.

**Comment by kira0204** [comment]
Hi, We can mock the external communication here by using the stdlib `unittest`, patch the function `gethostbyname`, once that is patched, we can set the `return_value` of it. Let's keep `xss_scanner.py` untouched :)

**Comment by fristonio** [comment]
Thanks a lot, I don't have much experience in unit testing. I didn't know about patching and mocking implementation in testing.
I have submitted a Pull Request for this please have a look [Pull 2909](https://github.com/mitmproxy/mitmproxy/pull/2909)
