### ISSUE TITLE
Revamp versioning strategy for bugfix releases.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2900]
A very unfortunate property of the Python Versioning Conventions in [PEP440](https://www.python.org/dev/peps/pep-0440/#developmental-releases) is that ".devNNNN" releases come before the actual release, e.g. 3.0dev1 is seen as a predecessor to 3.0 ("the first development release *towards* 3.0). As such, when creating dev releases, we kind of have to know the name of the next version.
To conform with PEP440, we currently update `mitmproxy/version.py` immediately after a release so that the development snapshots use that. For example, immediately after the 3.0.0 release, we bumped the version to 4.0.0, so that our snapshots are now correctly labled 4.0.0dev1, 4.0.0dev2, etc. 

Unfortunately this makes a 3.0.1 bugfix release a bit weird. We currently have two options:

1. Have a 3.0.x branch, change the version there to 3.0.1 and cherry-pick commits we want to include.
2. Downgrade the version to 3.0.1 + tag it, then immediately bump it again in a second commit.

The latter option (which we did for 3.0.1) is a bit ugly. I was thinking of implementing a "if tagged: use tag as version info; else: use version.py" logic to make this nicer. Alternatively, we can decide to either accept the status quo of the second option or commit ourselves to always branch out for that.

@mitmproxy/devs: thoughts?

**Comment by dwfreed** [comment]
Maintenance branches tend to work better, because then you don't have to worry about when you can merge new features into the master branch, and you can stage a series of bugfixes (possibly over time for minor things) before making a bugfix release.

**Comment by cortesi** [comment]
This ties in to the new CI snapshot generation strategy I just committed. Basically all tags get snapshotted and placed in the root directory of snapshots.mitmproxy.org under the tag name. Branches on the main repo get snapshotted, and placed in the `/branches` directory on the same server.

I suggest the following:

- The master branch always has a "dev" suffix.
- When we do a major release (say v4), we create a major version maintenance branch (v4), which then results in snapshots at `/branches/v4`
- We then update the version in the maintenance branch, and tag the release - say v4.0.0. This results in snapshots at `/v4.0.0/` on the snapshots server.

All our release processes can now refer to the snapshots server, which is behind a CDN, rather than uploading assets elsewhere.
