### ISSUE TITLE
Performance difference between mitmproxy and mitmdump

### ISSUE THREAD

**Issue by pulkitsharma07** [mitmproxy/mitmproxy#3018]
Hi,

I am building a tool to benchmark different mitm proxies. On initial runs, I am seeing difference between the performance of mitmproxy and mitmdump (v3.0.3).
You can find the entire report here: https://github.com/pulkitsharma07/proxybench#reporting

For the HTTPS Stress (over HTTP/2) test, which opens https://www.httpvshttps.com/, mitmproxy is 5 times slower than mitmdump. In other benchmarks too mitmproxy is slower than mitmdump.

I need to understand, am I doing something wrong on my end ? or is this an expected behaviour ? 
I am launching both proxies similarly with the `--listen-port` argument.

Thanks.

**Comment by mhils** [comment]
Very cool test - thanks for sharing! 😃 We actually started out building some performance measurements a few weeks ago: https://github.com/mitmproxy/mitmproxy/tree/master/test/bench.

> I need to understand, am I doing something wrong on my end ? or is this an expected behaviour ?

This is not expected behaviour, but may very well be an issue with our current architecture. @cortesi will probably be very interested in looking into this, he is in the process of replacing our eventloop with something asyncio-based to increase performance. If this works as planned, it should tackle exactly our problem here.

For reference, the expected behaviour is as follows:

1. For a few requests, mitmproxy, mitmdump and mitmweb should exhibit similar performance characteristics. Mitmdump is of course a bit more lightweight than its companions, so it probably beats the others by an edge.
2. For long-running sessions, mitmproxy's and mitmweb's RAM usage will increase, whereas mitmdump forgets about connections once they are finished.


Regarding your test setup: I do like that your tests are very practical, but there are many factors that can introduce noise: temporal network latencies, packet loss, HTTP edge caching, or DNS caches. If you want dependable results, I'd suggest to at least randomize test order and most importantly do multiple test runs and report on standard deviation.


Please don't hesistiate to get in touch if you have further questions, we're quite interested in the results here. :-) Thanks again!

**Comment by pulkitsharma07** [comment]
Thanks for the suggestions @mhils , I have added them to the TODO list, There are lot of things which I need to incorporate in the benchmark to make sure the results are reliable and immune to noise.

I would love if you (and others) can provide more suggestions/contribute to make the benchmark better. I want to get it to state that it is reliable enough to be incorporated into continuous integration tools.

**Comment by cortesi** [comment]
Hi there! First, let me say how much I appreciate you putting together a benchmark for interactive proxies. A comparison like this is invaluable to us, and we look forward to competing aggressively with our excellent peers.

I've just put together a PR that, in my testing, more or less eliminates the disparity that you're seeing. The changes here are deep, and still cooking, but will be in the next release we have scheduled for May. If you like, you can take a look at my high-level results here:

https://github.com/mitmproxy/mitmproxy/pull/3029
