### ISSUE TITLE
spoof_source_address cannot work alone

### ISSUE THREAD

**Issue by samiux** [mitmproxy/mitmproxy#3047]
The mitmproxy version is 3.0.4

The python version is 3.6

The iptable rule :

sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --match multiport --dport 80,443 -j REDIRECT --to-port 8080

The command to run :

mitmdump -p 8080 -s /etc/myscript/myscript.py -m transparent -q -k --certs *.mysite.com=/etc/mycert/mysite.pem --set spoof_source_address=true

The result :

502 Bad Gateway

ProtocolException('Server connection to ('192.168.20.100', 443) failed: Error connecting to "192.168.20.100": [Errno 99] Cannot assign requested address',)

The findings :

When "spoof_source_address" is used alone, it will crash with the captioned error.  

When "spoof_source_address" used with "upstream_bind_address" and "upstream_bind_address" not blanks, it will running smoothly.

If "upstream_bind_address" is blanked with "spoof_source_address", it will also crash with the captioned error.

Can "spoof_source_address" work alone?  In my understanding, "spoof_source_address" will show the original source client IP address.  Am I right?

**Comment by mhils** [comment]
What you are seeing here is kind of expected: 
https://github.com/mitmproxy/mitmproxy/blob/4cb96dedd0143cf9b6278d3622457e1e485b3090/mitmproxy/proxy/protocol/base.py#L120-L128

> Can "spoof_source_address" work alone?

Yes

> In my understanding, "spoof_source_address" will show the original source client IP address.

"Show"? Not really. If spoof_source_address is enabled, mitmproxy will send packets to the upstream server using the original client IP instead of its own. This requires a relatively complicated network setup where you have to make sure that traffic coming back from the server also goes through your proxy. 

If you don't know exactly if you need this feature, you don't. You can always view the client's address in mitmproxy without this. If you do need this functionality, you have to figure out why your OS gives mitmproxy a "Cannot assign requested address" error, we can't help you with your Linux configuration. Sorry.

**Comment by e1d1s1** [comment]
It works if you stick to v2.0.2.
