### ISSUE TITLE
add_signal_handler is strictly UNIX only. 

### ISSUE THREAD

**Issue by fenilgandhi** [mitmproxy/mitmproxy#3061]
https://github.com/mitmproxy/mitmproxy/blob/4e126c0fbaafffd23e1a80926de6a99c897f9af0/mitmproxy/tools/main.py#L124
According to the `asyncio`  documentation for [Python 3.6](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.add_signal_handler) , `add_signal_handler` is supported for UNIX system only. I haven't experienced or tested this issue but it maybe a potential risk since mitmproxy supports multiple platforms. 

If someone has a Windows OS and/or some knowledge about asyncio maybe you could verify this.

**Comment by fenilgandhi** [comment]
Although not the best solution , but the best workaround is to add a simple coroutine with call_later of 0.1. Somehow this works well in Windows and CTRL+C can terminate the loop.
[https://stackoverflow.com/questions/24774980/why-cant-i-catch-sigint-when-asyncio-event-loop-is-running/24775107#24775107](url)

**Comment by cortesi** [comment]
Good catch! We need someone on Windows to actually test the behaviour here. The StackOverflow question you included refers to a patch implementing add_signal_handler for the Windows event loops from 3.5 years ago which (sigh) appears never to have been merged.

Step one is to catch the `NotImplementedError` around that call and ignore it.

**Comment by CorTal** [comment]
I am on Windows and I pulled the commit from 2 days ago and since then, mitmdump and mitmweb weren't working anymore : 
![commit_error](https://user-images.githubusercontent.com/15815157/38795371-4bd90854-4158-11e8-9b13-906b4f70c5fe.JPG)
I thought it was because of some modifications I made so I didn't makean issue of that and I searched by myself without success.
But I just tested your solution of putting a try to catch the "NotImplementedError" : 
`try:
loop.add_signal_handler(getattr(signal, signame), master.shutdown)
except NotImplementedError as e:
print("ERROR : Method not implemented in Windows.")`
and then: 
![notimplement_exception](https://user-images.githubusercontent.com/15815157/38795589-1345aac8-4159-11e8-9bd4-f451f7456a9b.JPG)

So the behaviour here is that mitmdump and mitmweb are not usable until the exception is catched.

**Comment by cortesi** [comment]
@cortal Thanks for looking at this. Once the exception is caught, does mitmdump exit on ctrl-C?

**Comment by CorTal** [comment]
Yes, mitmdump exits on CTRL-C. (I checked with tasklist)
