### ISSUE TITLE
getting curl command from mitmproxy web

### ISSUE THREAD

**Issue by Dauth** [mitmproxy/mitmproxy#3085]
##### Steps to reproduce the problem:

is there any way to extract post request as curl using mitmproxy web?

**Comment by kajojify** [comment]
@Dauth Hello! 
Focus on the flow with a request you need.
Press `e` -> choose `curl` -> input appropriate filepath.

**Comment by tecfu** [comment]
No solution is posted. Why was this closed?

**Comment by Joshfindit** [comment]
This is an old request, but has not been filled as far as I can tell.

I would like to add my name to the list: being able to get curl strings from mitmproxy web would be very handy.

**Comment by bertrandp** [comment]
> This is an old request, but has not been filled as far as I can tell.
> 
> I would like to add my name to the list: being able to get curl strings from mitmproxy web would be very handy.

Click `Export` then select `cURL`

**Comment by etekweb** [comment]
This is now an even older request, but you no longer need to press "e" - instead, simply select "Flow" in the ribbon at the top of the page (if it isn't already selected - also if you don't see "Flow", make sure a request is selected first). From there, you'll see the "Export" option.

Also, as of now this has been changed to "Copy as cURL", so you can simply copy-paste the command instead of needing to save to a file first.
