### ISSUE TITLE
Write API Documentation

### ISSUE THREAD

**Issue by p-baum** [mitmproxy/mitmproxy#3141]
I'm raising this issue because its not listed in https://github.com/mitmproxy/mitmproxy/issues/2895

There is practically no API documentation.  I am currently studying machine generated diagrams to try to understand how this works.  Its no fun.

Somebody wrote "You can either run mitmdump as a regular process and send it a Ctrl+C when you are finished (importing mitmdump from mitmproxy.tools.main would work as well), or you instantiate your own DumpMaster and thenn call master.shutdown() when you are finished." at https://discourse.mitmproxy.org/t/start-and-stop-mitmproxy-from-python-script/677.

The homepage boasts a screenshot showing this:
```
from mitmproxy import http

def request(flow: http.HTTPFlow):
    # redirect to different host
    if flow.request.pretty_host == "example.com":
        flow.request.host = "mitmproxy.org"
    # answer from proxy
    elif flow.request.path.endswith("/brew"):
    	flow.response = http.HTTPResponse.make(
            418, b"I'm a teapot",
        )`
```
Its not much to go on.

**Comment by Kriechi** [comment]
What you are looking for is listed as `Addon development docs, mentioning hot reload and testing`.
Yes, we are lacking decent docs!

Let me give you a few pointers that might help you:
Generally speaking, in most cases you want to write an "addon".
https://docs.mitmproxy.org/stable/addons-overview/

This is was we provide as a single script to start with mitmproxy (or mitmdump), and can react to certain events in the lifecycle of your traffic going through the proxy.
https://docs.mitmproxy.org/stable/addons-events/
https://docs.mitmproxy.org/stable/addons-scripting/

**Comment by p-baum** [comment]
I understand that I should write addons.  What I'm not happy with is launching mitmproxy via a python subprocess to pass the paths of my addons.  If that is what is meant by API then it should be made clear.   In order to avoid this fugly "API" a have so far come up with this:
```
from mitmproxy import proxy, options
from mitmproxy.tools.dump import DumpMaster

class AddHeader:
    def __init__(self):
        self.num = 0

    def response(self, flow):
        self.num = self.num + 1
        flow.response.headers["count"] = str(self.num)

addons = [
    AddHeader()
]

opts = options.Options(listen_host='127.0.0.1', listen_port=3337)

m = DumpMaster(None)

pconf = proxy.config.ProxyConfig(opts)
m.server = proxy.server.ProxyServer(pconf)
m.addons.add(addons)

m.run()
```
What do you think?  Personally I dont like it much but its a tossup sofar between this and subprocess.

**Comment by Kriechi** [comment]
"Addon development docs, mentioning hot reload and testing" <- thats the list item in our Todo list, that you also referenced.

Regarding your code: I would be much simpler to launch mitmdump with your addon:
`$ mitmdump -s fancy_addon.py --set listen_port=3337 --set listen_host=127.0.0.1`

**Comment by p-baum** [comment]
OK.  So its on the todo already.  Great.  But hear me out here...

Regarding your simpler code: I dont think I have made myself clear. You simpler solution still involves launching the mitmdump from the command line.  To be clear, mitmproxy will be a single part of a larger application I am creating.  The application needs to start and stop the proxy. Thats why my code does it using python and not the commandline.  But like I said my program could also use a python subprocess and thread to lauch mitmdump.  At the end of the day I want to run my program which implements yours like a library.

The fact that this seems to be so difficult gives me the feeling its not what was intended by design.  If this is the case, please tell me and I will give up the hack and go ahead with a threaded subprocess (a less worse hack)

Thankyou for your help.

**Comment by cortesi** [comment]
@p-baum A bunch of things seem to be mixed up in this discussion. 

There's been a change in mitmproxy's strategy in the last year. In the past, sophisticated apps **had** to instantiate their own mitmproxy master to do sophisticated things, and this was a default path for many use cases. Now, we have an addon mechanism that is powerful enough to express almost all of mitmproxy's own core functionality, while providing proper isolation from the core, and a host of other conveniences and improvements. No matter what your core functionality or distribution model is, if you can express it as an addon you should. If you can't, then tell us, and we'll see if we are missing functionality that can help.

Regarding your particular use case, if your project makes it possible, just invoke mitmdump in a subprocess. If you can't do that, look at the code here to build your own master:

    https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/dump.py

Note how short that class is - that's because **all** the functionality for mitmdump is in addons. Your functionality should also be in addons, regardless of how you choose to invoke mitmproxy.

Now, regarding documentation. On our TODO list is better docs for addon development, and API docs for addon development. Not currently on the list is examples and an explicit description of how to instantiate your own master. I'm not against this latter step, and would accept a PR for this.

**Comment by p-baum** [comment]
Thankyou cortesi.  I'll have a crack at building my own master.

**Comment by cortesi** [comment]
@p-baum Great! Let us know how you go. We do want to support your use case as well as we can.

**Comment by q2dg** [comment]
I miss HTTPFlow, HTTPResponse and HTTPRequest API doc listing public methods and properties a lot, as it was in https://mitmproxy.readthedocs.io/en/v2.0.2/scripting/api.html#http

**Comment by jenniejj** [comment]
> Thankyou cortesi. I'll have a crack at building my own master.

Have you managed to build your own master?

**Comment by droope** [comment]
I asked on slack and was told the docs will hit stable soon, in the meantime they can be accessed at https://docs.mitmproxy.org/dev/api/mitmproxy/http.html

**Comment by mhils** [comment]
Ah, thanks @droope! Yes we have new API docs, I think this issue can be closed. They currently only live on https://docs.mitmproxy.org/dev/api/events.html, but we'll have them in the stable docs with the release of mitmproxy 7. 😃
