### ISSUE TITLE
Documentation lacks basic usage examples

### ISSUE THREAD

**Issue by stellarpower** [mitmproxy/mitmproxy#3142]
Hi,

mitmproxy looks like a really useful tool but I feel it is really let down by a lack of decent basic documentation. It's great that you go into detail on filter expressions, different modes of operation, and all that, but every section is lacking just a basic introduction and there's no basic user guide on how to use the software. 

For example, the manual page on mitmproxy is just a guide on the keybindings. When I first start using a program, learning how to change the default keybindings is not on my mind. I would just want to see a basic example of how to create a simple setup and perform basic tasks in that setup. So a beginner's guide into starting up the proxy, filtering some content, intercepting and replaying, etc. would be a lot more useful. Similarly, the mitmweb documentation is just a screenshot, and the filter expressions page doesn't even explain how to use them, I'm just presented with a list of flows and no idea how to do anything with them. I'd been using the web interface but atm it's running so slowly on a very powerful laptop that I'm going back to the cli tool.

I know you're pressed for developer time but I really think ten hours spent on documenting how to use the tool for beginners would go a lot further than ten hours of improvements in the codebase at this time.

Thanks

**Comment by cortesi** [comment]
Hi there. Thanks for your feedback - we need to hear this sort of thing to keep improving. I think your critique boils down to a lack of basic tutorials and tool usage in our docs. This is a fair, and something we're thinking about. The type of detailed usage documentation you describe hard to write and maintain. User interfaces change constantly, and whenever you put a screenshot or specific step-by-step instructions into a document, you can expect to have to update it every few releases. So there's a balance to find - ideally we would have just enough information to get people bootstrapped to the point where the technical documentation make sense to them, and where they can begin to rely on the (very complete) built-in documentation for commands, options and the like.

Regarding mitmweb - it's still in beta, and for anything complicated you should still be using the console application. 

I know this is an irritating response to receive to a bug report - but we're always looking for contributors, and we'd be very happy to accept PRs that address some of the specific shortcomings here. 

I've edited the title to this report to be more specific.

**Comment by stellarpower** [comment]
Hi,

Don't worry, it's not irritating, even a basic introduction would be good if everything else is changing so quickly. It's just I feel I'm dropped in and don't know where to begin, I think once you know the basics you can work the rest out. I understand the web interface is still new, I'm just curious as to why it's so slow as I'm running it on a very fast machine. But now I've worked out how to do the basics in the CLI I can use that instead. 

As an aside, do you know if I can get the pydoc documentation out of the binaries? I installed from the website for Linux which provided me with three binareis so I don't have a pip package for the API reference. I tried `pip install mitmproxy` too but it can't find it and is complaining about a cert error even though I've turned off the proxy.

Thanks

**Comment by stellarpower** [comment]
Okay, got there in the end. Might be worth mentioning in the docs that it seems I need Python 3.6 for variable annotations.

**Comment by thclark** [comment]
I wholeheartedly agree with this, unfortunately the docs so far assume that I already know how to do 50% of it.

Of course you can't be expected to provide a tutorial that's like "First, switch your computer on, there's probably a button on the front to do so"... But the tutorials and instructions should cover the whole product, not just the advanced bits. Perhaps a "getting started" section that handholds developers through getting something running in the first place.

### Example weaknesses

- I'm coming over from Locust.replay, trying to use this so I can record a session for use in load testing. Finding a basic tutorial starting with "To do this, just start mitmproxy and configure your target device with the correct proxy settings" makes me feel like a total idiot. Because thats what I'm reading the docs to find out how to do!

- The intro says "mitmdump is the command-line version of mitmproxy. Think tcpdump for HTTP." Hmm. if I knew what tcpdump was, would I really be reading the introduction line of the docs, or would I have already assumed it was like tcpdump, because it's named the same, and moved on?

### Can I contribute? Hmm.

I kinda hate moaning on posts like this (usually have a hard rule of only posting if I can be constructive or contribute) so I'm sorry. I do OSS dev too, and know your time is valuable. I hope these couple of examples help rather than hinder.

I can't (right now!) contribute, because of course I'm at step 0. But maybe if one of the devs wants to spend 30 mins or an hour handholding me on Skype, I'd be happy to contribute by writing (say) a medium post or a chunk of a getting started section in return!

**Comment by mplattner** [comment]
I'm working on this issue and need your feedback. :)
We came up with a couple of ideas to improve onboarding/guiding new users:

1. **improve the docs** by adding the basics of how to use mitmproxy
2. **add a tutorial addon** to mitmproxy that interactively guides the user through common use cases (view flows, modify/intercept/replay requests)
3. **create a video tutorial** that helps getting started with mitmproxy

Personally, I'm for a combination of 1 and 2.
While a video (3) might be helpful as well, videos tend to age quickly and are hard to update.
You can't update minor bits as the software changes, but probably have to re-record the whole video.

I'm happy to hear your feedback. Below are some more details for 1 and 2.

---

Ad 1)
I plan to add more basics, e.g., explain the UI, nagivating the UI, basic features etc.

random concrete ideas:
* annotate [the mitmproxy screenshot](https://docs.mitmproxy.org/stable/tools-mitmproxy/) with "flows", "focussed flow", "command bar" etc.
* *your ideas are welcome*

Ad 2)
We want to have a `Tutorial` addon that (locally) serves a simple web app that allows to test the basic features of mitmproxy.
Here's a rough mockup what the user sees when browsing to http://tutorial.mitm.it

![tutorial_app_mockup](https://user-images.githubusercontent.com/1025800/88782856-5cc1fe00-d18e-11ea-8013-ea2548040a39.png)

**Comment by mhils** [comment]
cc @Prinzhorn @Kriechi, @mitmproxy/devs - do you folks have opinions on https://github.com/mitmproxy/mitmproxy/issues/3142#issuecomment-665552828?

**Comment by Kriechi** [comment]
yep - 1+2 sounds like a great step forward!
A few sample dump files might be nice to have, along with the tutorial steps so new users can easily replicate a certain analysis or task.

**Comment by Prinzhorn** [comment]
I don't like 3 either. Not only do videos age quickly they also force a fixed pace on the viewer and are not searchable. The other options allow me to quickly check out what I'm interested in at my own pace.

I like the idea of a simple tutorial app that teaches the basic things with minimal user effort. It also works offline wherever you run mitmproxy.

**Comment by mplattner** [comment]
Thanks @Kriechi and @Prinzhorn for your feedback, I agree that 1 and 2 is a great first step! 👍
I've just created PR #4127 with an early draft (tutorial page layout and sample app). More to come in the following days :)

**Comment by mplattner** [comment]
I created some interactive tutorials for the docs that should improve the onboarding of new users.
See https://plattner.me/mp-docs/mitmproxytutorial-userinterface/ for a preview, details are at #4194 
Feedback is welcome 😄

**Comment by sliceofdanny** [comment]
Hello. I'm new to this product and to Python. 
Thanks to your awesome documentation I was able to get this working in minutes on Windows 10. 

I have a specific request which might not be the intended use for this application: How can I take a saved flow and export just the URL's and timestamps?

Is that something I can do via script in Windows or would I need to spin up a Linux VM? Is there some example code that can do this?

Thank you, and kudos to the team. I saw @cortesi's AU Linux's presentation from 2012 and that was great breakdown.

**Comment by ComputerRoger** [comment]
FYI, HTTP verb OPTIONS does appear in mitmproxy.

**Comment by bizmate** [comment]
Hi, I can see this issue is closed, i can open a new one if necessary. I tried starsting the proxy with this docker compose setting

```
  proxy:
    image: mitmproxy/mitmproxy:10.4.2
    command: "mitmdump --mode upstream:${UPSTREAM_PROXY}"
```
    
  the UPSTREAM_PROXY gets a value of _http://{user}:{password}@host:port_ (also tried without the schema http) but i keep getting 
  
`  /usr/local/bin/mitmdump: Invalid proxy mode specification: upstream:BLABLAUSER:PASS@gate.superproxy.com:7000 (Invalid server specification: BLABLAUSER:PASS)`
  
  I cannot see these examples in the docs in order to correctly specify the authentication info. Can someone point to the right way of specifying the configuration?
