### ISSUE TITLE
How to configure the external viewer?

### ISSUE THREAD

**Issue by gajus** [mitmproxy/mitmproxy#3165]
mitmproxy v4 has key binding `v` ("View flow body in an external viewer").

It appears to open the content of the response in nano. How do I change this to, e.g. Atom or browser?

**Comment by kajojify** [comment]
@gajus Hello! 
Mitmproxy lets you:
- edit request/response body of the flow;
- edit the content of grideditor cell;
- view request/response of the flow.
 in the **external editor**.

Mitmproxy uses environment variables in order to choose appropriate external editor/viewer:
- for editing:
https://github.com/mitmproxy/mitmproxy/blob/69aa5a0d2f799cc91ab5a7d5d75c55aa40ae58b8/mitmproxy/tools/console/master.py#L123

- for viewing:
https://github.com/mitmproxy/mitmproxy/blob/69aa5a0d2f799cc91ab5a7d5d75c55aa40ae58b8/mitmproxy/tools/console/master.py#L162

So, as you can see, in order to change standard editor you should change environment variable PAGER or EDITOR from your terminal.

All the best!

**Comment by gajus** [comment]
> So, as you can see, in order to change standard editor you should change environment variable PAGER or EDITOR from your terminal.

Is this documented anywhere?

I could not find this anywhere in the docs.

**Comment by mhils** [comment]
That sounds reasonable, we can make it `os.environ.get("MITMPROXY_EDITOR") or os.environ.get("EDITOR") or "vi"`.

This should also be in the docs, not sure where a good place would be.

**Comment by ffe4** [comment]
@mhils can this issue be closed after #3425 ? Is it only about adding docs now?

**Comment by q2dg** [comment]
The existence of MITMPROXY_EDITOR variable isn't added in docs yet :-(

**Comment by mhils** [comment]
Please feel free to add it!
