### ISSUE TITLE
Confusing confdir argument

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#3266]
My tests are messy cause I used mitmproxy and mitmdump, both of them in 4.0.1 and 4.0.3 and now I mixed all cases.

At some point, I think I had an error saying that --confdir was deprecated and had to use "--set confdir=" (I can't reproduce this case though with mitmproxy or mitmdump...)

I spent some time to try to make "--set confdir=" work in a weird bash script and arguments with quotes and maybe it failed due to me.
But I realized --confdir was still working eventually for mitmdump in 4.0.3.

Question to sum up:
Is it attended to have both "--confdir" and "--set confdir=" working at the same time for mitmproxy & mitmdump?
If yes, help (-h) should specify it clearly with something like: "--confdir PATH, --set confdir=PATH"
If not, one of them should be deleted.

**Comment by kajojify** [comment]
@tomlabaude Hello! 
I checked your case for both mitmproxy and mitmdump (latest version from the master branch). `--confdir` is deprecated for newest mitmproxy as well as for newest mitmdump and only `--set confdir=` is available.
You can read more about mitmproxy options here -> https://docs.mitmproxy.org/stable/concepts-options/

In response to your question. Since deprecation list has `confdir` inside (https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/utils/arg_check.py#L4), then no, it isn't meant to have both "--confdir" and "--set confdir=" - only `--set confdir`.
And yes, we should delete `--confdir` from `--help` output. Thanks :)
