### ISSUE TITLE
Regex BUG?

### ISSUE THREAD

**Issue by zhuscat** [mitmproxy/mitmproxy#3332]
##### Steps to reproduce the problem:

1. run `mitmproxy`
2. press `f` key to filter. For an instance, I want to enter `google\.com`. However, after I enter `.`, the `\` disappear.

##### System information

Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.0.2p  14 Aug 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit

**Comment by kajojify** [comment]
Hello there! Thanks for the report. 
Sorry for not responding you for a long time.
Our command line string gets into parse_partial method
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/command.py#L153-L156
Then we break the command string into tokens with help of shlex lexer in POSIX mode -> https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/command.py#L25

I think, that disappearance of '\\' is intentional behaviour of shlex lexer in POSIX mode - https://docs.python.org/3/library/shlex.html#parsing-rules

**Comment by kajojify** [comment]
If you still have any questions or suggestions, please reopen :)
