### ISSUE TITLE
Initiating HTTP/2 connections with prior knowledge are currently not supported

### ISSUE THREAD

**Issue by raulsiles** [mitmproxy/mitmproxy#3362]
##### Steps to reproduce the problem:

1. Run mitmproxy in transparent mode:
```
mitmproxy --mode transparent [--showhost]
```
2. Generate traffic through the transparent proxy (traffic is redirected to mitmproxy via iptables in Linux) from an Android client. The Android client tries multiple HTTP/2 connections to various Google servers, typically in the 216.58.x.y & 172.217.w.z IP address ranges.
3. All these connections appear in the Flows list as shown, followed by a "Connection killed" error message (in red color):
```
PRI https://216.58.x.y HTTP/2.0
```
4. The log generates a related warning ("warn:", in orange color): "Initiating HTTP/2 connections with prior knowledge are currently not supported".
5. All these connections and error messages overload the Flows list with garbage, making difficult to complete the analysis over the interesting flows. 

Questions and recommendations:
a)- May I suggest the creation of a global (not just for specific IP address ranges) temporary workaround or command line switch to be able to disable displaying these flows until HTTP/2 connections with prior knowledge is supported in mitmproxy? Current workaround:
```
 mitmproxy --mode transparent [--showhost] --ignore-hosts 172\.217\.\d+\.\d+ --ignore-hosts 216\.58\.\d+\.\d+
```
b)- Are there any plans to support HTTP/2 connections with prior knowledge in the mitmproxy roadmap? ETA?

##### Any other comments? What have you tried so far?

Disabling HTTP/2 support in mitmproxy via the "--no-http2" option does not solve the issue, as it seems the Android client keeps trying these connections as HTTP/2, with no prior negotiation.

##### System information

Kali Linux: mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.6.5rc1
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling

**Comment by raulsiles** [comment]
For the record: The suggested workaround (item "a)" above) does not always work (although initially it seemed to work), as there are scenarios where the "PRI" and "Connection killed" entries (with the same IP address ranges) still appear in the Flows list, although they have been ignored (and mitmproxy reflects "Ignore:2") :(

**Comment by seunlanlege** [comment]
currently facing this issue, would be happy to contribute in anyway i can.

**Comment by HasBert** [comment]
@raulsiles Do you have any updates on this?
I'm using the "regular http proxy" and your first solution with the ignore host `--ignore-hosts 172\.217\.\d+\.\d+` is indeed not working, but I think in my setup this is because I should use the hostname instead of the ip, as mentioned [here](https://docs.mitmproxy.org/stable/concepts-options/). 
BUT the `--no-http2` option is working for me! thank you for that one! Maybe the option is not applicable for a transparent proxy?

I want to change my setup to transparent mode too, so it would be nice if there is any progress, or any idea how to solve this.

**Comment by raulsiles** [comment]
@HasBert I do not have any update on this. My testing setup is based on using transparent mode, therefore my initial description in this issue still applies (unless someone tells me there are new capabilities to fix it).

**Comment by HasBert** [comment]
Hey @raulsiles 
My "solution" was posted too early, the error occured right after I wrote my answer. So it was not working. This is the same error you noted in your description:
> 3. All these connections appear in the Flows list as shown, followed by a "Connection killed" error message (in red color):
> `PRI https://216.58.x.y HTTP/2.0`

However, as you can see The HTTP Method is always `PRI` and the domain `https://216.58.x.y` or `https://172.217.x.y`.
I never saw a PRI http-method before, and read that it is a http2 specific method. It is mentiod in this [thread](https://stackoverflow.com/questions/50434269/pri-method-in-http2-implementation-causing-issue). 
The `http2=boolean` option does not solve this specific problem, the flows are the same. maybe that's because it's not supported yet? @mhils

Anyways if you [filter](https://docs.mitmproxy.org/stable/concepts-filters/) your flows on http-method (PRI) with the [options](https://docs.mitmproxy.org/stable/concepts-options/) `view_filter` for mitmproxy and mitmweb, or `dumper_filter` for mitmdump, then you can dismiss this problem. 

_**config.yml**_
```yaml
view_filter: "!(~m PRI)" 
#or
dumper_filter: "!(~m PRI)" 
```
This options show every request with http-method NOT matching PRI. So you'll maybe miss some PRI request that would've worked on other URLs, if they work on other URLs.
I'm currently trying to get your regex `172\.217\.\d+\.\d+` to work with the `~d` filter expression.
```yaml
view_filter: "!(~d 172\.217\.\d+\.\d+)" 
```
I'll let you know, if I get it to work. I have problems with the regex inside the config.yaml file. ;)

**Comment by normanr** [comment]
ahh, what about this as a root cause: HTTP2 clients are supposed to send: `PRI * HTTP/2.0` as part of their connection preface. If there's a transparent proxy (or badly behaved client) that doesn't understand HTTP2, then normally it would transform `GET /foo HTTP/1.0` (send via TLS) to `GET https://1.2.3.4/foo HTTP/1.0` (to send via proxy). It applies the same transform to the HTTP2 request to get: `PRI https://1.2.3.4* HTTP/2.0` (this is what I see from the Android emulator when it has a manual proxy configured)

So I'd guess that for these style of requests: mitmproxy should parse out the IP address, and use that as the upstream address.

**Comment by corford** [comment]
Is this a limitation with hyper-h2 or MITM itself? Would be great if it could be solved as we have the same problem as @raulsiles : Iptables based transparent intercept and an Android app that uses Google's Firebase which makes use of prior knowledge HTTP/2 connections. Workaround for us is excluding the firebase API domains but then we lose intercept capability for these.

**Comment by normanr** [comment]
mitmproxy has a DisableH2C addon that specifically kills these connections (it's where the log message is coming from). From what I can figure out http2 handling is supposed to trigger from the TLS ALPN negotiation, so I wonder if that's happening correctly for these connections. Is the ALPN not negotiated correctly, or does something in the transparent proxying mode break it?

**Comment by corford** [comment]
Looking at the code (https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/disable_h2c.py), the `DisableH2C` method seems to be doing two separate things (stripping the upgrade headers for h2c connections; and killing prior knowledge connections - regardless if they are h2 or h2c).

Given the method is called DisableH2C, I wonder if killing all prior knowledge connections was the intent or if killing the flow should only happen for h2c connections.

**Comment by normanr** [comment]
I believe that if http2 connections are made via TLS ALPN, then , then the connection preface (which has the PRI prefix) will be consumed and never interpreted as part of a request. So these connections are either not doing ALPN correctly, or not using TLS.

https://github.com/mitmproxy/mitmproxy/blob/93f9e30728300cc5379fd90171818f642d8f24aa/pathod/pathod.py#L271-L273

https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/pathod/protocols/http2.py#L225-L227

**Comment by Kriechi** [comment]
pathod code (which @normanr cites above) is only used for testing - none of these code paths are used in the actual proxy.

Yes, mitmproxy currently only support the most common way of establishing an HTTP/2 connection: a TCP socket + TLS ClientHello that includes the `h2` ALPN, and then the server needs to accept it, then the client sends the `PRI ` prefix to initiate the HTTP/2 connection.

The `DisableH2C` addon was primarily a simple way of clearly marking unsupported features - so far nobody has implemented cleartext h2 or prior-knowledge connections, so I thought disabling them in a clean way is the most pragmatic way of "documenting" these missing features.

I would be happy to review and accept PRs that add support for h2c or prior-knowledge h2 connections - same goes for PRs in hyper-h2, if we are missing feature in there as well.

**Comment by corford** [comment]
Thanks for the extra details. Not 100% sure I have the necessary time (and more importantly, knowledge!) to submit a PR but I might try at some point if no one else beats me to it.

**Comment by Kriechi** [comment]
Not in scope for us - but happy to review a PR.
