### ISSUE TITLE
400 No required SSL certificate was sent

### ISSUE THREAD

**Issue by yilingsj** [mitmproxy/mitmproxy#3497]
fiddler，charles and mitmproxy They all failed!
eg:https://img.alicdn.com/imgextra/i1/759415648/O1CN016k9Bvh1rapU9jcmu0_!!759415648.png

我正在抓soul app，结果发现无法抓取https的数据，但是有些https是可以正确返回数据的

**Comment by MatthewShao** [comment]
Quick Translate the question:
> I'm intercepting packet for an Android App, it turns out a 400 error code, but it works for some domain.

Answer:
I think it is because the App is employed with [Certificate Pinning](https://docs.mitmproxy.org/stable/concepts-certificates/#certificate-pinning), if fiddler, charles and mitmproxy all failed, that's not a bug of mitmproxy. Please read instructions from the above link for a possible workaround.

**Comment by yilingsj** [comment]
> Quick Translate the question:
> 
> > I'm intercepting packet for an Android App, it turns out a 400 error code, but it works for some domain.
> 
> Answer:
> I think it is because the App is employed with [Certificate Pinning](https://docs.mitmproxy.org/stable/concepts-certificates/#certificate-pinning), if fiddler, charles and mitmproxy all failed, that's not a bug of mitmproxy. Please read instructions from the above link for a possible workaround.

谢谢，后来在一个逆向大神的帮助下，用证书密钥才获取到数据。
