### ISSUE TITLE
What's going on planning?

### ISSUE THREAD

**Issue by q2dg** [mitmproxy/mitmproxy#3507]
Last update was one year ago and development seems a bit stalled from since.
Is there any problems?
Is this project healthy?
Thanks!

**Comment by kajojify** [comment]
@q2dg Hello! :) 
Thank you for the interest to **Mitmproxy**.

As you can see the last release was on _Jul 31, 2018_,
the last commit to the master branch was on _Jan 31, 2019_.
So yes, we are a bit inactive. Unfortunately, main contributors don't have enough time to work on mitmproxy. Everybody is busy with jobs/studies/personal stuff.

> Is there any problems?
Everything is ok. Contributors just haven't enough time :(

> Is this project healthy?
It is healthy. We remember about it, just waiting for the free time in our schedules.

**Comment by q2dg** [comment]
Thanks a lot.
I'll close the issue, then.
Wish you had a little more time to enjoy.

**Comment by redNixon** [comment]
Not to be overly negative, but on topic the limits of the core developers time and the benefits of having a larger pool, I recently implemented support for a couple of new protocols, one that needed layers all the way to the wire and one that sat next to websocket in terms of layer level(all part of an internal proprietary tool unfortunately).


Figuring out where to start and how traffic gets routed through the layers was a non-trivial process; adding replay and webui support was another step that took a lot of effort to get right because of some unknown unknowns from the proxy implementation phase causing issues.  The current documentation useful if you are a user of mitmproxy  but there is a lack of documentation that new developers realistically need in order to quickly get going.


I don't have any real suggestions, a lot of the decisions made in the code look strange/not efficient coming in fresh which leads to a strong desire to do things differently and it isn't until understanding how all the programs and pieces work together did it become obvious.  Outside of API documentation which isn't too helpful at very beginning, trying to document all of this in an ingestible way would be a large amount of work.  Maybe implementing a new protocol and documenting the process in tutorial form would be the best way to make the process more approachable for new devs.
