### ISSUE TITLE
Simple addon doesn't work

### ISSUE THREAD

**Issue by moldis** [mitmproxy/mitmproxy#3589]
##### Steps to reproduce the problem:

1. sudo apt-get install mitmproxy (debian)
2. mitmproxy -s ./myaddon.py

##### Any other comments? What have you tried so far?
Code for addon:

from mitmproxy import ctx

class AdsResponse:
    def request(self, flow):
        flow.request.host = "mitmproxy.org"

addons = [
    AdsResponse()
]

##### System information

mitmproxy --version 0.18.2

**Comment by ylmrx** [comment]
Hello !

You're using a _very_ outdated version of mitmproxy. The addons API changed a lot since. 
You need to use the old way : https://mitmproxy.readthedocs.io/en/v0.18.2/scripting/overview.html

Specifically : replace `addons=[yourCustom(), cLasses()]`

with:
```python
def start():
    return AdsResponse()
```

I still recommend you switch to a newer version.
