### ISSUE TITLE
New Table UI has no replay indicator

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3704]
#### Problem Description

The new table UI doesn't show that a flow has been replayed:

![image](https://user-images.githubusercontent.com/1019198/68954563-90a5f080-07c4-11ea-9d73-3abf9ce674b3.png)

The two-line UI still has an indicator - `[r]` in my case as my terminal is detected to not support UTF8:

![image](https://user-images.githubusercontent.com/1019198/68954680-cb0f8d80-07c4-11ea-91d0-af110277d143.png)

#### Steps to reproduce the behavior:
1. Add a flow, e.g. by pressing `n` `enter`
2. Press `r` to replay.

#### System Information
Mitmproxy: 5.0.0.dev (+356, commit a5412ab)
Python:    3.8.0
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.27

**Comment by mhils** [comment]
@Jessonsotoventura: You are the expert here - would you mind taking a look? 😊

**Comment by Jessonsotoventura** [comment]
Yes - I'll take a look at this issue

**Comment by typoon** [comment]
The issue seems to be here:

<https://github.com/mitmproxy/mitmproxy/blob/ac22aee2f512cefd298fe0d9563a5de0ef7e42ee/mitmproxy/tools/console/common.py#L371-L380>

2 things that caught my attention:

```python
    cursor = [' ', 'focus']
    if f.get('resp_is_replay', False):
        cursor[0] = SYMBOL_REPLAY
        cursor[1] = 'replay'
    if f['marked']:
        if cursor[0] == ' ':
            cursor[0] = SYMBOL_MARK
        cursor[1] = 'mark'
    if f['focus']:
        cursor[0] = '>'
```

The line ` if f.get('resp_is_replay', False):` should probably be ` if f.get('req_is_replay', False):`

And even if that is true, the last if there `if f['focus']:` overwrites the cursor with a `>` if there is only 1 flow in the table (after all you will be focusing it).

The replay symbol should be drawn on the second column, not the first.

Hopefully this is helpful
