### ISSUE TITLE
Generalize to handle generic SSL-encrypted TCP traffic

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#374]
mitmproxy is fantastic for intercepting and modifying HTTP/HTTPS traffic.  However, not all network traffic of interest fits into this category.  For example, XMPP is a protocol which is XML based and does not rely on HTTP.   In order to be able to handle traffic for these cases, we want to be able to support the capture of generalized TCP traffic which is SSL'ed.  
- [x] Test and merge [SOCKS support](https://github.com/mitmproxy/mitmproxy/pull/305)
- [ ] Add --tcp switch and add checks for such around check_ignore_address/establish_ssl

The following are some slightly cleaned up comments from @mhils on IRC:

TL;DR: --ignore is checked before any call to establish_ssl() (which does the MITM stuff). If you want to intercept non-HTTP TLS connections, you probably want to  do something similar, but after establish_ssl() has been called.

generalized tcp proxy: if your traffic isn't encrypted using SSL, just use mitmdump -v --ignore regex-for-your-host (0.11 only) ignore patterns are documented [here](https://github.com/mitmproxy/mitmproxy/blob/master/doc-src/features/passthrough.html)

We currently have a couple of places where we call check_ignore_address() and may go over to TCP mode then. usually, check_ignore_address is closely followed by establish_ssl().  We'd need to add a --tcp switch which uses the same hostname pattern, but just gets executed after establish_ssl(), not before.

well, we have a "generalized tcp proxy". which is  "-v --ignore hostname", but if your traffic is protected using SSL, you probably want to strip that off before. By default, mitmproxy opens a SSL connection to the client and a separate SSL connection to the server. pretending to the client to actually be the server... Using --ignore, we don't event do anything SSL related, we take the raw TCP stream and forward it which means the client negotiates SSL with the real server.

In other words, --ignore can be used to see what passes through, but if that communication is protected using SSL, you'll just see garbage.  Now, you may ask: Why don't we do the SSL-MITM stuff and then pass through the cleartext, now readable for us?

 Answer: --ignore serves a different purpose. Some apps, most notably the apple store on iOS, cannot be intercepted, because they hardcoded a target cert we don't have a key for. --ignore makes it possible to debug an app while just letting this stuff pass through.

e.g. you want to test an app which at some point makes an cert-pinned in-app purchase.
So, that's the primary use case for --ignore.

If you want to peek into non-HTTP SSL connections, you'd do our SSL MITM stuff first and then delegate it to the passthrough thingy.

**Comment by bazzinotti** [comment]
first, thank you, contributors of mitmproxy. I have a bit of problem, I would like to take this feature a step further; but first let me establish to you my background in using this feature. Please bear in mind that I am new to mitmproxy.

I am currently successfully performing a TCP SSL mitm session with a client cert. I want to record the decrypted stream as direct binary. handshaking info is good auxiliary debug info, but ultimately I want a sole dump of only the decrypted ssl conversation. Not knowing how to do this directly in mitmproxy, I instead had mitmproxy output a pre master secret file which I configured Wireshark to use. this method was successful until I realized that I am suffering from packet loss due to the high volume high frequency of packets... I did try playing around with Wireshark settings, but it is too clear to me that if I only knew how to get mitmproxy to simply share the decrypted information with me in the style I prefer,I would be golden. This is because mitmproxy is in the direct path of the packets, unlike Wireshark, which is only an observer.

So, I ask one of you to please educate me on two points. Can mitmproxy already do what I seek? If so, please provide some detail in enabling the functionality. If it is not yet available, but you know what file(s) or function(s) are the key locations to modify with additional logging functionality, please let me know. Thank you.

**Comment by bazzinotti** [comment]
Hi, I come with an update to my previous question (see above). I have discovered several things, some spawning further questions.

* I am using `--raw-tcp` instead of `--tcp` -- and I've become curious whether one is preferred over the other? --raw-tcp works for me, but given the description of --tcp here, it sounds like it would also perform the exact same duties (SSL Mitm w/ decryption). Please correct me if I'm wrong.
* I discovered how to have mitmproxy dump the decrypted SSL conversation to file (in the context of --raw-tcp).. Since my experience is with --raw-tcp and not --tcp, I filed a new issue on this (https://github.com/mitmproxy/mitmproxy/issues/866). 

I look forward to your correspondence.

Sincerely,
bazz
