### ISSUE TITLE
Routing Question

### ISSUE THREAD

**Issue by abmyii** [mitmproxy/mitmproxy#3803]
Hi! I am trying to implement routing in this manner:

```
																    no
client --> mitmproxy --> (check if hostname is in list of accepted) --> upstream response
										   |
										   |  yes
										   |
							intercept and return custom response
						    + don't allow to propagate upstream
```

Is this possible simply by overriding `request` and `response`, and also how would I go about implementing this?

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/send_reply_from_proxy.py

Can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all further support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!

**Comment by abmyii** [comment]
> Can I please ask you to use StackOverflow for all further support and how-to questions? You can post the link to your question here so that people can follow up.

Will do, thank you very much! I've a follow up question regarding this issue which I'll also post there.

**Comment by abmyii** [comment]
https://stackoverflow.com/questions/60030385/passing-response-to-upstream-proxy-only-in-certain-cases
