### ISSUE TITLE
Using application certificates for mitmproxy error 403

### ISSUE THREAD

**Issue by Egyras** [mitmproxy/mitmproxy#3807]
#### Problem Description
I'am checking IOT device websocket data stream to Cloud and get 403 error doing this mitmproxy.

#### Steps to reproduce the behavior:
1.  IOT application has 3 pem files: cacert.pem, newcert.pem, newkey.pem
2.  launch mitmproxy --mode transparent --showhost --ssl-insecure --cert *=/tmp/ssl/cert.pem
(cert.pem has both newcert.pem and newkey.pem inside)
3.  Error:
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>

#### System Information
Mitmproxy: 5.0.1
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.10-cosmic

**Comment by mhils** [comment]
Not sure, could be that your device is using client certificates. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
