### ISSUE TITLE
incomplete certificate generated by mitmproxy

### ISSUE THREAD

**Issue by sebster** [mitmproxy/mitmproxy#3981]
#### Problem Description

When using mitm proxy to fetch the following resource:

> https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs

I get the following exception:

```
Caused by: java.security.cert.CertificateParsingException: X.509 Certificate is incomplete: SubjectAlternativeName extension MUST be marked critical when subject field is empty
        at java.base/sun.security.x509.X509CertInfo.verifyCert(X509CertInfo.java:751)
```
 
I don't know why, but the Subject of the certificate generated by mitmproxy does not get set to anything in this case.

If I force the SubjectAlternativeName extension to be critical by changing the source code as follows, the problem disappears and the certificate is accepted by Java:

```diff
(venv) sebster@eeyore:~/Work/mitmproxy$ git diff
diff --git a/mitmproxy/certs.py b/mitmproxy/certs.py
index a37d29bc..cbedc1fd 100644
--- a/mitmproxy/certs.py
+++ b/mitmproxy/certs.py
@@ -114,7 +114,7 @@ def dummy_cert(privkey, cacert, commonname, sans, organization):
     if ss:
         cert.set_version(2)
         cert.add_extensions(
-            [OpenSSL.crypto.X509Extension(b"subjectAltName", False, ss)])
+            [OpenSSL.crypto.X509Extension(b"subjectAltName", True, ss)])
     cert.add_extensions([
         OpenSSL.crypto.X509Extension(
             b"extendedKeyUsage",
```

#### Steps to reproduce the behavior:
1. Attempt to fetch the above resource with mitmproxy from a Java client (OpenJDK 11.0.1) 

#### System Information
Mitmproxy: 6.0.0.dev (+44, commit 7fdcbb0)
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.3.0-51-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
Ha, interesting edge case. :)
If mitmproxy's `upstream_cert` setting is false, mitmproxy wants to set `document-storage-production-dot-remarkable-production.appspot.com` as the certificate subject (because that's all we know without looking at the upstream cert). However, that domain is exactly 65 characters long, whereas the CN field is limited to 64 characters. Hence we don't set a subject and only a SubjectAltName. The Java client is right to point out that we need to set this extension as critical then (see https://stackoverflow.com/a/56169246/934719).

Could you verify that the PR linked below fixes your issue properly? 😃

**Comment by sebster** [comment]
Wow, quick response and fix! :) I tested it and the issue is indeed resolved.

**Comment by rajaie-algorithmia** [comment]
We also ran into this issue and the change in the PR fixed the issue 👍
