### ISSUE TITLE
Please please please compile for Windows 32-bit like 4.0.4

### ISSUE THREAD

**Issue by alexalwks** [mitmproxy/mitmproxy#4035]
I'm always frustrated when I have to install on Win32 bit.

Version 4.0.4 installs correctly on both 32 bit / 64 bit Windows 7 / 10.

Can we get a built of 5.1.1 ( or latest ) to get to be installed normally on 32 bit and 64 bit Windows?

**Comment by mhils** [comment]
I don't see a convincing use case for 32 bit builds, sorry. It's not worth the effort for us.

**Comment by alexalwks** [comment]
I hate windows as much. But still, is it possible to have the compilation source available?

**Comment by 0-0eth0** [comment]
Hey @mhils ,

Hope you are doing well!

I know it’s not a priority of you for build of 32 Bit binary. I was just looking for some documentation/guide on how to cross compile it fo r 32 Bit rather than requesting for a directly binary. I would like to build it on my own but if there is any guide/documentation that would help is highly appreciated!

Thanks for your contribution towards community!

Best Regards,
Jinay

**Comment by mhils** [comment]
AFAIK you cannot (easily) cross-compile PyInstaller binaries. I have no further insights on this, sorry.
