### ISSUE TITLE
Limit memory usage

### ISSUE THREAD

**Issue by cavias** [mitmproxy/mitmproxy#4129]
Is there a way to setup a max memory usage for mitmproxy? Because right now it just seems to build in memory until it runs out, if I am correct.

It would be great if I could, for limited machines, define max memory usage. When the limit is reached, it will throw away old flows and such until it is within limit again.

**Comment by rugk** [comment]
Clever idea, combined with `--save-stream-file` this may then save the whole stream to disk, so it can be retrieved if needed, later. So the memory limit should only apply to the running mitmproxy instance – and not discard already saved flows.

**Comment by mhils** [comment]
Thanks for the suggestion! You can currently use one of the following workarounds:

1. You can run mitmdump, which discards flows once they are processed completely.
2. You can press `z` to clear all flows.
3. You can write a custom addon that automatically clears up flows.

I think the proper way to solve this is #2175: We don't want to discard flows, we just want to decrease memory consumption and move stuff to a temporary file instead. I'm closing this issue here in favor of that!
