### ISSUE TITLE
View response in Firefox gives file not found

### ISSUE THREAD

**Issue by wchasekelley** [mitmproxy/mitmproxy#4152]
#### Problem Description
Hitting `v` on a flow opens up firefox pointing to a temp mitmproxy file but the file doesn't exist

#### Steps to reproduce the behavior:
1. Capture a request 
2. Press v in the flow view of request and 2 for viewing response
3. Firefox opens up to view the response html page but only displays file not found e.g. `Firefox can’t find the file at /tmp/mproxynqb8uytn.html`. (Hitting `e` and editing the response works correctly and opens up the response as a tmp file in my editor)

#### System Information
Mitmproxy: 5.1.1
Python:    3.8.3
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.6.19-2-MANJARO-x86_64-with-glibc2.2.5

**Comment by mhils** [comment]
Thanks! The problem is likely in https://github.com/mitmproxy/mitmproxy/blob/408bd7fd4c5ed147ce2951428bfdd6206e1eb8b8/mitmproxy/tools/console/master.py#L139-L174. I'd guess that the process we're calling exits before your Firefox renders and we've then already unlinked. Not sure what the best approach is, but I guess moving the unlink to a thread with a timeout should fix this main issue.
