### ISSUE TITLE
WebSockets streams are always forwarded and invisible?

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4165]
#### Problem Description
You do describe the option `stream-websockets`, which defaults to `false`.

My interpretation is: This will thus _not_ forward WebSockets stream by default. Thus, it will block them.
And, __if enabled__ it says "Messages are captured", i.e. I expect to see it at least in the CLI version or so… :thinking: 

What happens:
* if `stream_websockets=false` (default) .-> WebSockets are forwarded and I do not see them
* if `stream_websockets=true` .-> WebSockets are forwarded and I do not see them :thinking: 

#### Steps to reproduce the behavior:
`$FLOWSAVE` is a file.
1. Start `mitmweb --anticomp --anticache --mode transparent --web-port 1234 --save-stream-file "+$FLOWSAVE" --web-host 0.0.0.0` (optionally with ` --set stream_websockets=true`)
2. Go to https://www.websocket.org/echo.html in your browser. You see it works and you get your message back.
3. Read `mitmproxy -n -r $FLOWSAVE` – no WebSockets streams visible. You only see the WebSocket upgrade message last.

A simple `grep -C 10 -a "rocks" $FLOWSAVE` also shows no indication of the requests. (only JS files appear)

#### System Information
Paste the output of "mitmproxy --version" here.

#### More

Related options:
* `websocket` is true by default, so I don't care about this
* `flow_detail` talks about WebSocket but is only for `mitmdump`, so… :shrug: 

I **suspect** your WebSocket support is in an early stage and you don't have any CLI/viewing method implemented? Am I right?
If so, then at least, do state that somewhere please. It's perfectly fine to write in your docs "This feature is in beta and viewing XY is not implemented yet. We do not advise you to use it.", but giving such options like I see above implies this feature does work somehow (either block WebSockets or show them). Instead, I only see them being forwarded.

**Comment by Kriechi** [comment]
*Streaming* in the context mitmproxy means that large messages will not be buffered & sent to the other endpoint, instead each received data packet will be streamed directly to the other endpoint.

This originates from our HTTP implementation - imagine a 10GiB file download. mitmproxy should not buffer this in memory - and basically make your machine unusable. For HTTP the size limit when this behaviour triggers is controlled by the `stream_large_bodies` option. For WebSockets, we use a simple yes/no option `stream_websockets`, because Websocket messages usually are smaller.

mitmdump, one of the three mitmproxy tools, fully supports WebSockets, dumping their message type and content. WebSocket messages and their content can be made visible with the `flow_detail=3` option.
See our CLI option reference for additional information: https://docs.mitmproxy.org/stable/concepts-options/

mitmproxy and mitmweb currently do not support displaying Websocket (in a meaningful way at least...). This is a known open ticket: https://github.com/mitmproxy/mitmproxy/issues/1020 and has been requested / mentioned in a few duplicate tickets already.

Our scripting and addon event hooks fully expose websocket lifecycle events so you can make use of all events with your custom addons: https://docs.mitmproxy.org/stable/addons-events/#websocket-events

These events even allow you to intercept, modify, inject or otherwise manipulate WebSocket messages:
https://docs.mitmproxy.org/stable/addons-examples/#websocket-inject-message
and
https://docs.mitmproxy.org/stable/addons-examples/#websocket-simple

Does this address your questions - or is anything missing for your (except the known missing integration in mitmproxy & mitmweb, which we have an open ticket for already)?

**Comment by rugk** [comment]
Ok, thanks for detailed your explanation. Yeah, it would be great if I did not need to open this issue to get to know this, but this would be stated in the docs.
As you can see, I interpreted the `stream_websockets` option in a totally different way.

So maybe use this issue here for doc improvements. E.g. instead of the ambiguous term _streaming_, the term _buffering_ is technically more exact and if that had be mentioned in the docs, I would have known that mitmproxy always forwards the connection and this is just a technical detail.

**Comment by rugk** [comment]
Also:
> mitmdump, one of the three mitmproxy tools, fully supports WebSockets, dumping their message type and content. WebSocket messages and their content can be made visible with the flow_detail=3 option.

This is bad. Because when I use `--save-stream-file` I also want all that being saved. Virtually, there should be no difference between what is saved in a flow file depending on the CLI tool – it may depend on an option, but not on the tool you use.
Compare that with Wireshark: It does not happen whether I record a stream with the GUI version or a CLI version (`tshark` or so), it always saves the same data.

As such, do make `flow_detail` available for mitmproxy and mitmweb. After all, it can also configure what is shown in the UI – everything which is collected may be shown.
BTW the parameters for `flow_detail` in it's current way are confusing? As far as I see, if we'd translate the current behaviour of `mitmweb` and `mitmproxy` to these options, it is something between 2 and 3, i.e. currently it saves 
> full request URL with response status code(1) + HTTP headers (2) + full response content (part of 3, except WebSockets)

So if #1020 is implemented, that would basically be level 3 by default then.
Seeing this, I also don't understand why the current level for `mitmdump` by default is 1 – that dumps nearly nothing useful. And it's different than for the other tools.
So if you want to unify that, of course you should change to one default for all CLI tools.

**Comment by mhils** [comment]
> This is bad. Because when I use `--save-stream-file` I also want all that being saved. Virtually, there should be no difference between what is saved in a flow file depending on the CLI tool – it may depend on an option, but not on the tool you use.

It always saves the same data, @Kriechi's "dumping" refers to "printing out visibly on the console". The data is there, it just needs to be exposed on in the user interface.

> As such, do make `flow_detail` available for mitmproxy and mitmweb. After all, it can also configure what is shown in the UI – everything which is collected may be shown.
> BTW the parameters for `flow_detail` in it's current way are confusing? As far as I see, if we'd translate the current behaviour of `mitmweb` and `mitmproxy` to these options, it is something between 2 and 3, i.e. currently it saves

Again, it has nothing to do with _saving_, this only affects display. Broadly speaking, we want the interactive tools to display everything if requested by the user (i.e. by selecting a flow). For mitmdump, we need a single setting that governs the level of display for all flows.
