### ISSUE TITLE
async events in addons

### ISSUE THREAD

**Issue by iTosun** [mitmproxy/mitmproxy#4207]
#### Is your feature request related to a problem? Please describe.
It would be a nice feature if the mitm event's can be run as async functions, this will enable developers of addon's to use async methods. 

#### Describe the solution you'd like
Make the event's async!

#### Describe alternatives you've considered
I've tried to schedule futures in the current running eventloop but it seems that it doesn't apply changes to the HTTP flow object. 

#### Additional context
Would love to see async possibilities, that can make some advanced addons more efficient and extensible

**Comment by lionel126** [comment]
extremely look forward to

**Comment by rachmadaniHaryono** [comment]
```python
import asyncio
import signal

from mitmproxy.tools import console, main
from mitmproxy import ctx


class Addons:

    async def f1(self):
        count = 0
        while True:
            await asyncio.sleep(1)
            count += 1
            ctx.log.info('count: {}'.format(count))


opts = main.options.Options()
master = console.master.ConsoleMaster(opts)
pconf = main.proxy.config.ProxyConfig(opts)
master.server = main.proxy.server.ProxyServer(pconf)
ao_obj = Addons()
master.addons.add(ao_obj)
loop = asyncio.get_event_loop()
loop.add_signal_handler(
    signal.SIGINT, getattr(master, "prompt_for_exit", master.shutdown))
loop.add_signal_handler(signal.SIGTERM, master.shutdown)
loop.create_task(ao_obj.f1())
master.run()
```
above example is based on https://github.com/mitmproxy/mitmproxy/issues/4259

**Comment by roniemartinez** [comment]
+1

**Comment by Prinzhorn** [comment]
One thing I'm concerned about are race conditions. They exist with `@concurrent` and maybe we can get rid of them with async events.

I just switched to `@concurrent` to see how things are going. I just ran into a race condition where `server_connected` was racing `request`. This crashed my app because of the assumption that the connection exists when the request arrives (a SQL constraint failed).

`websocket_message` seems to behave as expected, that means multiple messages from different connections are processed concurrently but on the same connection message B will only be processed when message A is done. That's perfect. I'd love to see **connection-wide serialization** in all of mitmproxy. That means the `request` event cannot happen after `server_connected` is done and so on. Is this feasible?
