### ISSUE TITLE
Where is the event log location in Mac?

### ISSUE THREAD

**Issue by ZanXusV** [mitmproxy/mitmproxy#4212]
OS: macOS Catalina 10.15
Pyhon:3.8.5
Run Env: venv
I cloned mitmproxy project and run mitmproxy  in venv with python3.8, but I can't find where the log file is, there is no introduction specified and no related information in mitmproxy --help, can anyone help me

**Comment by rbdixon** [comment]
After starting `mitmproxy` hit the `?` key to show the keybindings:

`E      View event log`

The `q` to get back to the main screen. `E` to see event log. `q` takes you back to main.

The event log is not saved to a file.

Since this is a question about how to use mitmproxy you should probably consider Stack Overflow. Here is an example of someone asking a similar question and getting an answer:

https://stackoverflow.com/questions/51836971/display-mitmproxys-events-log-on-linux 

I'm not a developer so I can't close your issue on Github but you might consider doing so to clean up the issue list.

**Comment by mhils** [comment]
Thanks @rbdixon! ❤️

**Comment by ZanXusV** [comment]
Thanks for ur reply, I am wondering will the feature that event log save to a file for further analysis will be developed in the future

**Comment by mhils** [comment]
@ZanXusV: mitmdump echoes events to stdout, you can save that if you need to. That being said, the mitmdump dump file _should_ contain all important data.

**Comment by ZanXusV** [comment]
> @ZanXusV: mitmdump echoes events to stdout, you can save that if you need to. That being said, the mitmdump dump file _should_ contain all important data.

OK, got it, very thanks
