### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by gfrench17** [mitmproxy/mitmproxy#427]
Hi there,

today, I came across https://whiteout.io -> when trying to access the website through mitmdump, I get

"SSL handshake error: The client may not trust the proxy's certificate." from the mitmdump output, and Firefox tells me "(Error code: ssl_error_rx_record_too_long)"

I have installed the mitmproxy certificate in Firefox, and other https websites like google.com or github.com work fine. What could be the problem with whiteout.io?

Further information:
$ python --version
Python 2.7.6
$ mitmproxy --version
mitmproxy 0.11.1

The error is well reproducable on another Linux box as well. Help is well appreciated.

Kind regards
Gordon

**Comment by rvaneijk** [comment]
Hi Max, 

I am experiencing similar problems.  Use I Python 2.7.8, mitmproxy 0.11.3 on a Ubuntu 14.10 server (3.17.1-031701-generic). The client, firefox 36.0.1 runs on Windows 8.1 Pro.

An example mitmdump with "SSL handshake error: The client may not trust the proxy's certificate." messages is here: http://www.blaeu.com/uploads/1303

Do you think this is this due to the SNI problem you described above? The number of clients not trusting the proxy's certificate seems to increase, but I have not investigated that in detail.

Regards,
Rob

**Comment by mhils** [comment]
@rvaneijk, there are a couple of explanations for said error message.

1. Certificate not installed on the client's machine. (That doesn't seem to be true in your case)
2. Websites with HSTS Certificate Pinning

Usually, it turns out to be one of these reasons. If you believe it's a bug, I need a reproducible test case over here.

Cheers,
Max

**Comment by rvaneijk** [comment]
@mhils,  

>>If you believe it's a bug, I need a reproducible test case over here.
It looks to be the case due to certificate pinning.
In order to provide a reproducible test case, what files would you need? (eg mitmdump and/or wireshark capture?)

**Comment by mhils** [comment]
@rvaneijk, I'd need steps how I can reproduce that behaviour locally. A Wireshark dump may help, but it's probably not possible to identifiy the root cause out of this. See our bug report template in CONTRIBUTING.md

Cheers,
Max

**Comment by Funcan** [comment]
The hipchat client trying to connect to their server exhibits this issue. Reproducer (with the proxy running on localhost):

$ nc localhost 8080
CONNECT 168.87.243.152:5222 HTTP/1.1
Proxy-Connection: keep-alive
Host: 168.87.243.152
User-Agent: Mozilla/5.0


HTTP/1.1 200 Connection established
Content-Length: 0
Proxy-agent: mitmproxy 0.13

HTTP/1.1 502 Bad Gateway
Server: mitmproxy 0.13
Content-type: text/html
Content-Length: 342
Connection: close


            <html>
                <head>
                    <title>502 Bad Gateway</title>
                </head>
                <body>SSL handshake error: The client may not trust the proxy's certificate.<pre>ProxyError('NetLibError("SSL handshake error: SysCallError(104, \'ECONNRESET\')",)',)</pre></body>
            </html>

**Comment by Funcan** [comment]
$ mitmproxy --version
mitmproxy 0.13

**Comment by medyagh** [comment]
I have the same problem and I am using the version 0.15

**Comment by ThurnisH41ey** [comment]
Bump, same issue in 0.16.

**Comment by mhils** [comment]
This issue here has been fixed - if you encounter something similar, please open a new one.

**Comment by medyagh** [comment]
I get it for snapchat 
```192.168.1.108:42015: clientdisconnect
192.168.1.108:42016: Client Handshake failed. The client may not trust the proxy's certificate for app.snapchat.com.```
