### ISSUE TITLE
confdir option can not directly set to the directory name under current directory

### ISSUE THREAD

**Issue by v3470** [mitmproxy/mitmproxy#4274]
#### Problem Description
The code at `proxy/config.py#L59` has a logic problem. If the `confidir` directly set to a folder name, it will raise the exception.

 https://github.com/mitmproxy/mitmproxy/blob/f97826f62434f064ad12a5fb559ab82eaaa4cc8d/mitmproxy/proxy/config.py#L58-L63

#### Steps to reproduce the behavior:
1. create a folder named `config` at the current working directory
2. run `mitmdump --set confdir=config`
3. program exit and output: `Certificate Authority parent directory does not exist: `

The reason is that `os.path.dirname` only do the path split at the string, so 'config' -> ['','config'] and return '' as the result, and finally `os.path.exists('')` return False. This condition is wrong because if we set `confdir` to `foo\bar`, the certs will be generated under the `bar` folder not the `foo` folder, and also it will notice that CA doesn't exist in `foo` not `foo\bar`.

As a result, if you need to set `config` as `confdir`, you need to set `confdir` to `./config`.

A better method to check whether the dirctory exist is `os.path.exists(path) and os.path.isdir(path)`.

#### System Information
mitmdump --version
Mitmproxy: 5.2
Python: 3.8.5
OpenSSL: OpenSSL 1.1.1g 21 Apr 2020
Platform: Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
Thanks - please keep pointing out options that currently don't work properly!

I actually came across this same issue a few days ago as well. It piqued my curiosity because `~/.mitmproxy` never exists on the first run, so how is this code actually working at all? Well, turns out it works precisely because that check is flawed and only checks for the existence of `~` and then creates a new `.mitmproxy` directory at some other place. 😄 

This should be fixed with sans-io (#1775), the relevant commit is https://github.com/mitmproxy/mitmproxy/commit/a19a5c96f3f8191468ebce30a80060073a00f003#diff-e914533a2f6956d11df7615b5467c21a167837c34ef0be44b0bea14d9a25ddecL188-L191. I just removed the check (and we just generate directories where necessary). Let's keep this issue open for now until it's landed on master. 😃

**Comment by mhils** [comment]
This is fixed now, but #4358 appeared. 😄
