### ISSUE TITLE
Generic server for testing intercepting proxies - somewhat related to pathod

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4276]
This is tangentially related to #4273

I wanted to post this for quite some time and #4273 reminded me of it. I am working on a product that integrates mitmproxy and basically turns it into a desktop application (this is a gross oversimplification). I will join Slack later and might share some details.

Anyway, I want to write full end-to-end integration tests. By that I mean launching some apps (e.g. WordPress in a Docker container) and then running the application and automating all the interface interactions (like editing a flow etc.).

To cover all the edge cases I plan on writing a server specifically designed for integration tests of intercepting proxies (or HTTP clients in general I guess). And I thought maybe this is something the mitmproxy team would be interested in joining forces?

The server would basically have routes for all things I want to test, e.g. something likes this (I haven't really looked into all the things I actually want and need to test in detail)

```
/encoding/utf-8
/encoding/gb18030

/websockets/text # These would serve an HTML page that starts communicating using WebSockets
/websockets/binary
/websockets/mixed

/status/200 # Maybe these things could also be parameters of the other routes
/status/404

/chunked
```

So I'm hitting `/encoding/gb18030` with my HTTP client (e.g. headless Chrome) that's using the proxy and once I get the response I verify that weird characters are correctly rendered in the UI. Or that my replacement pattern correctly matched.

I personally would write this in Go, but I wouldn't mind Python (although it'd slow me down I guess).

Is this something you are interested in? How are you planning on doing integration tests? Does something like this already exist (how are others doing that?)? Could parts of pathod be reused?

**Comment by mhils** [comment]
> I wanted to post this for quite some time and #4273 reminded me of it. I am working on a product that integrates mitmproxy and basically turns it into a desktop application (this is a gross oversimplification). I will join Slack later and might share some details.

Cool stuff! 😃 

> To cover all the edge cases I plan on writing a server specifically designed for integration tests of intercepting proxies (or HTTP clients in general I guess). And I thought maybe this is something the mitmproxy team would be interested in joining forces?

That pretty much sounds like what pathod is doing currently (or maybe also httpbin if you are looking more at the application layer).  For example, if you just start pathod and then open `http://localhost:9999/p/200:b@100`, you get served a 200 status code and 100 random bytes.

IMO there's really nothing wrong with this approach. The reason we are moving away from this is that our sans-io unit tests are switching to a plain specification of the bytes on the wire, which doesn't depend on a custom DSL, is a bit faster, and allows for more fine-grained control of the timings (see e.g. [this test for response streaming](https://github.com/mitmproxy/mitmproxy/blob/a19a5c96f3f8191468ebce30a80060073a00f003/test/mitmproxy/proxy2/layers/http/test_http.py#L227-L247)). For unit-testing the UI, we can manually construct flows and go from there. Looking at integration tests, we really don't plan to test down to the same level of detail - any simple HTTP server on the other end would probably suffice. 

That being said - maybe you want to take a closer look at pathod and see if it fits your needs. Keeping it around isn't too much work for us, but there's no point in maintaining it if we don't use it anymore and have very little adoption otherwise. :)

**Comment by Prinzhorn** [comment]
I've looked into pathod once some time ago but didn't want to learn a new DSL. pathod works on a different abstraction layer then what I'm looking for (that's what it's designed for).

But I think you've pointed me in the right direction, I might just contribute to https://github.com/mccutchen/go-httpbin (the original is inactive anyway).

I'll close this for now and might post an update once I actually start writing the tests. Thanks!
