### ISSUE TITLE
Problems about Cannot establish TLS with client

### ISSUE THREAD

**Issue by thanhtan27081998** [mitmproxy/mitmproxy#4354]
I implemented an application with a herokuapp host domain. When I started verifying my herokuapp domain by 
``` 
heroku certs:info
```
I received the message
```
[domain name] has no SSL certificates.
```
However, when I used mitmproxy to call http requests to my domain, it sent back an error
```
Cannot establish TLS with client (sni: ******): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')])")
```
Then I generated a certificate pinning from my android_key_store and ran the command again
```
mitmdump --cert *******=outcert.pem
```
I got this error
```
Cannot establish TLS with client (sni: ******): TlsException("SSL handshake error: Error([('SSL routines', 'tls_post_process_client_hello', 'no shared cipher')])")
```
I'm wondering why I cannot connect to my domain even it does not have a SSL certificate. How can we set up for that?

**Comment by mhils** [comment]
1. It's a bit disrespectful that you actively ignore the "Support" option when creating an issue, and then additionally go on and delete the issue template so that useful information such as your mitmproxy version are missing.
2. Not a mitmproxy bug, maybe just read the error message. TLS establishment between client and mitmproxy failed, the server is not involved.
