### ISSUE TITLE
Dumper Addon: make the number of printed lines configurable when using `flow_detail = 3`

### ISSUE THREAD

**Issue by Zio-Seppio** [mitmproxy/mitmproxy#4476]
I try to dump full traffic on stdout using mitmdump, but when response body has more than about 80 or 90 lines on stdout appear (cut off) and all other lines are lost,

I use this command:
*mitmdump  --set flow_detail=3 --set content_view_lines_cutoff=2000* <br><br>

The exact behavior is described [here](https://discourse.mitmproxy.org/t/mitmdump-cutting-off-responses/1714) on old mitmproxy forum: unfortunately there was no response

@debian-10:~$ Scaricati/mitmdump --version
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-4.19.0-14-amd64-x86_64-with-glibc2.28

**Comment by Prinzhorn** [comment]
I'm not sure why it's that way, but it happens here

https://github.com/mitmproxy/mitmproxy/blob/8178f6c77b715cd342f8be161d5ca5da8938645c/mitmproxy/addons/dumper.py#L110-L113

but all calls to `_echo_message` are already guarded with `if ctx.options.flow_detail >= 3:` so the `else` will _never_ be reached.

It's been this way since the beginning https://github.com/mitmproxy/mitmproxy/commit/b0b3b19ad644afeb353cf6e02bd4aac61f2774c8

`content_view_lines_cutoff` is only for mitmweb, I guess we need to introduce a new option for the dumper and default to `0` (dump everything) I guess?

In either case `70` is currently a magic number. Magic number bad. Make programmer angry.

**Comment by Prinzhorn** [comment]
I changed my mind, sort of.

`flow_detail = 4` is simply undocumented :thinking: . You can use it as a workaround :+1:

**Comment by Prinzhorn** [comment]
I've made a PR for the docs and updated this to be a feature request to make the `70` configurable when using flow_detail 3

**Comment by mhils** [comment]
> `content_view_lines_cutoff` is only for mitmproxy ui, I guess we need to introduce a new option for the dumper and default to `0` (dump everything) I guess?

We should make it an option for all tools then and reuse it in mitmdump. :)
