### ISSUE TITLE
@command.command doesn't introduct any new commands to CMD

### ISSUE THREAD

**Issue by hash3liZer** [mitmproxy/mitmproxy#4540]
#### Problem Description
Tested on `Windows 8.1`
Mitmproxy: `6.0.2`
Python: `3.8.0`

The @command.command function doesn't introduce any plugin command to the command interface. I've the following addon code on the go: 

```python
class intercept:
    def __init__(self):
        self.incoming = 0
        self.outgoing = 0

    @command.command("intercept.inc")
    def incoming(self):
        print(f"Incoming {self.incoming}")

    @command.command("intercept.out")
    def outgoing(self):
        print(f"Outgoing {self.outgoing}")

    def request(self, flow):
        self.outgoing += 1

    def response(self, flow):
        self.incoming += 1

addons = [
    intercept()
]
```

The program starts as normal. But when i type `:intercept.inc` on cmd, i get nothing.

**Comment by mhils** [comment]
There are three distinct problems here:

1. Executing this shows `error: in script foo.py: name 'command' is not defined` in mitmproxy's event log.
This can be fixed by adding  `from mitmproxy import command`.
2. Next up, I get `AddonManagerError: An addon called 'intercept' already exists.` This can be fixed by renaming the addon to something else. There just happens to exist a builtin "intercept" addon.
3. The commands don't show up. This is because `intercept.incoming` is overridden in the constructor:
```python
class Intercept2:

    def __init__(self):
        self.incoming = 0  # <- overrides function on construction

    @command.command("intercept.inc")
    def incoming(self):    # <- this also is self.incoming!
        print(f"Incoming {self.incoming}")
```
