### ISSUE TITLE
UX: Clarify "no content" message.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#459]
If a user opens a flow, he will often be greeted with a message stating "no content". We should rephrase that to "No request content" or "No request content (press tab to view response)".

**Comment by gajus** [comment]
When you become familiar with the concept of "tab" allowing to switch between request and response, it is clear that "no content" is referring to the request body. Instead, I suggest adding "tab:toggle between request and response" guide, next to "?:help q:back [*:8080]", because these guides are the first thing I look as a novice user.

**Comment by mhils** [comment]
If you can fit `"tab:toggle between request and response"` into <10 chars, I'm all in. For now, we'll display 
`No request content (press tab to view response)` in the UI if there's no request content.

Cheers,
Max
