### ISSUE TITLE
Client TLS handshake failed. The client may not trust the proxy's certificate for static-assets.highwebmedia.com (connection closed)

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4678]
#### Problem Description

v6 does not log these errors. The thing is that directly connecting to these hosts works too without error. And it seems like everything is working, so what's going on here? Does it actually fail?

```
Client TLS handshake failed. The client may not trust the proxy's certificate for static-assets.highwebmedia.com (connection closed)
Client TLS handshake failed. The client may not trust the proxy's certificate for roomimg.stream.highwebmedia.com (connection closed)
```

#### Steps to reproduce the behavior:
1. `mitmproxy`
2. Open Chromium via proxy
3. Visit https://chaturbate.com (obligatory https://hackerone.com/chaturbate)

You'll instantly see the error.

Here's `-set proxy_debug -vvv` for v6 and v7

[v6.log](https://github.com/mitmproxy/mitmproxy/files/6814791/v6.log)
[v7.log](https://github.com/mitmproxy/mitmproxy/files/6814792/v7.log)

#### System Information

main, does not happen on 6.0.2

**Comment by Prinzhorn** [comment]
I might look into this some more later, I'll assign the issue to myself if I do so.

**Comment by mhils** [comment]
Thanks, this is useful. Tracking this down:

1. I first grep the log for "The client may not trust the proxy's certificate" to see that the connection with source port 58954 is affected.
2. Next, I run `test/helper_tools/loggrep.py 58954 v7.log` to only see events relating to that connection.
3. Refine with `test/helper_tools/loggrep.py 58954 v7.log | rg "SendData|ConnectionClosed" -C 1000` to highlight specific keywords.

Using that approach we see that the client unexpectedly disconnects while mitmproxy is negotiating TLS with the server. The error by itself is not wrong, but in this particular setting we can be more precise: We haven't presented a cert yet, so we can be sure that it's not because the CA is untrusted. The general problem is that some TLS clients just hang up after being presented with an untrusted cert, so we can't entirely avoid false-positives here.
