### ISSUE TITLE
Setup GitHub Discussions?

### ISSUE THREAD

**Issue by suntong** [mitmproxy/mitmproxy#4778]
#### Problem Description

I know current plocy is to 

- ask questions on StackOverflow and 
- report bugs on GitHub

but somehow I have a feeling that StackOverflow is hostile to `mitmproxy` related questions, they are either down-voted, or closed directly:

![image](https://user-images.githubusercontent.com/422244/130536391-0926d249-f5a4-416c-a8f3-2e2bdbc74b21.png)

#### Proposal

I don't know why the https://discourse.mitmproxy.org/ is now in sun-set mode, but how about enabling the discussion feature within mitmproxy on GH?

**Comment by mhils** [comment]
Thanks for the suggestion! I was thinking about this the other day as well. Some background:

#### 2011–2016: GitHub Issues

Initially we used GitHub issues only. That turned out to be somewhat painful over time due to the volume of low-effort issues that got opened.

#### 2016–2019: Discourse

In 2016 we started discourse.mitmproxy.org as an attempt to fix this and build more of a community. This worked okay, except that I was doing almost all the work of answering support questions. There are a few notable exceptions (I recall @Gigiarum helping out quite a bit 🍰), but overall this was super demotivating for me because I was essentially fighting an endless stream of low-effort questions.

#### 2019–today: GitHub/StackOverflow

In 2019 we closed the Discourse instance and now ask people to post questions on StackOverflow instead. I am personally _much_ happier with this approach: 

 - We have more people helping out with good answers (for example @rob-X1 does this regularly 🍰)
 - Our issue tracker here remains relatively productive (in particular thanks to @Prinzhorn et al helping out 🍰)
 - Low-effort/off-topic questions on SO are usually flagged before I see them.
 - I'm still answering the majority of questions, but I do not feel responsible to reply to everything.

There are of course some minor problems with the current approach. The vast majority of mitmproxy questions are a good fit for StackOverflow (addon development, ...), but some questions should probably be on their superuser sister site. This is tricky for us because we can't send people to two different places at the same time. There are a few trigger-happy moderators that are very eager to downvote and close questions, which can feel a bit unwelcoming. Then again, for some of the questions this may just be the right course of action.

#### Github Discussions?

Now coming back to GitHub discussions... I'm generally open to try this out, but I'm also wary of changing the current approach. I do like that this means we'd have everything in one place, I think there's also an opportunity for more community-building. At the same time my understanding of community is not "@mhils patiently explains how computers work to more random strangers".

Oh, and some final words: If you are reading this and wondering whether you belong into that group that annoys me... that level of self-reflection shows that you certainly don't. :)

@mitmproxy/devs, any thoughts?

**Comment by Prinzhorn** [comment]
@mhils I suggested using discussions before, but I don't have any experience with how good discussions work in other projects. You didn't mention Slack, which I'm not a fan of at all. All discussion that happens in Slack and all the knowledge is just lost and buried there behind a signup-wall. I stopped using StackOverflow heavily a few years ago and only rarely answer questions and not once have I looked at the mitmproxy tag (shame on me).

I'm pro trying it out. It would also allow moving issues over to discussions without closing the issue with a "please use StackOverflow". I'll probably look into the discussions tab more than StackOverflow (`> 0`).

> "@mhils patiently explains how computers work to more random strangers".

That sounds like a YouTube series where you walk up to random strangers on the street and tell them about TLS handshakes :smile:

**Comment by suntong** [comment]
> I do like that this means we'd have everything in one place

I was thinking about suggesting on tracking the superuser sister site as well, but I tends to agree more on keeping everything in one place too. 

Anyway, just throwing my 2c here, and all my intention was try to build a better community. After all, we have over 300 mitmproxy contributors, and I have a feeling that not every one of them closely watch StackOverflow. 

PS, I strongly agree with Prinzhorn that Slack is the worst of the worst, :)

**Comment by mhils** [comment]
I won't have time to set this up properly and foster some initial friendly atmosphere in the next two months. If someone wants to get this started, please ping me and I'll equip you with the necessary GitHub permissions. 😃

**Comment by mhils** [comment]
I've just set up GitHub Discussions over at https://github.com/mitmproxy/mitmproxy/discussions, let's see how that works out. 😃
