### ISSUE TITLE
Add support for spoofing DNS

### ISSUE THREAD

**Issue by bramp** [mitmproxy/mitmproxy#4886]
#### Problem Description

I would like mitmproxy to receive A and AAAA DNS requests and return its own IP address, or otherwise forward on the DNS request if it's an ignored host.

This is to trick clients into using mitmproxy to proxy future HTTP requests to those domains.  It could also get smart and match DNS requests to future HTTPS requests which do not contain SNI information.

#### Proposal
Add a new mode to mitmproxy to accept UDP (port 53), DNS-over-TLS (port 853), and DNS-over-HTTPS (port 443).

#### Alternatives

Run a tool such as [dns-mitm](https://github.com/SySS-Research/dns-mitm) to redirect all DNS queries to the mitmproxy.

**Comment by Prinzhorn** [comment]
I'm not sure if this is in-scope for mitmproxy since it doesn't actually need to proxy anything and there are already tools you can use as fake DNS. I personally think we need to draw a line _somewhere_.

This also looks a lot like https://github.com/mitmproxy/mitmproxy/issues/3844, since mitmproxy doesn't support UDP at all. I'm closing this as duplicate, feel free to re-open if I'm missing something.

For DNS-over-HTTPS this should already works with an addon that responds to DNS queries. But would of course be more usable if you could listen on multiple ports with a single instance.

**Comment by Prinzhorn** [comment]
More to read https://github.com/mitmproxy/mitmproxy/issues/4122

**Comment by mhils** [comment]
For the record, I think DNS needs to be in scope for us, but we first need to figure out UDP. :)

**Comment by Kriechi** [comment]
Some time ago I built a DNS addon for the most basic use cases:
* Replace replies with predefined responses
* Blackhole incoming requests

docs here: https://github.com/Kriechi/mitmproxy/blob/dns-addon/docs/src/content/overview-features.md#dns-manipulation
code on this branch: https://github.com/Kriechi/mitmproxy/commits/dns-addon
