### ISSUE TITLE
HTTPS proxy not getting Piped/Invidious/Youtube links

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#4915]
#### Problem Description
I'm trying to intercept and record links that flow through my browser. However, when I click on a Piped link (a frontend to Youtube), ex. piped.kavinrocks.com/watch?v=qwerty, I don't see that request: I only see the JS, CSS, etc. 

#### Steps to reproduce the behavior:
1. Set up mitmproxy to record all requests
2. Go to Piped, and click on a video. 
3. See that the url is not in the logs

#### System Information
Paste the output of "mitmproxy --version" here.

```
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.15.1-1-ARCH-aarch64-with-glibc2.32
```

**Comment by Prinzhorn** [comment]
I cannot reproduce this, because `piped.kavinrocks.com` appear to not exist

![Selection_1007](https://user-images.githubusercontent.com/679144/142455433-bd5babbe-8452-4b1e-9fcb-0ab15ef96140.png)
![Selection_1008](https://user-images.githubusercontent.com/679144/142455476-2333cf23-da54-4a4f-a5eb-144abbe386bd.png)

**Comment by DUOLabs333** [comment]
Whoops, it's `piped.kavin.rocks`

**Comment by Prinzhorn** [comment]
>     3\. See that the url is not in the logs

Can you be more specific? The website uses client side routing, you won't see a classic GET to the URL when clicking on a link. There are only API calls happening via JavaScript.

**Comment by DUOLabs333** [comment]
Doesn't the browser make a GET request? If I type in a URL and press Enter, Firefox will show that a GET request was made.

**Comment by Prinzhorn** [comment]
Your second step says

> Go to Piped, and click on a video.

So I assumed you are missing the GET request from clicking on a video

> Doesn't the browser make a GET request? If I type in a URL and press Enter, Firefox will show that a GET request was made.

There's a service worker (which can be used to make apps work offline and cache shit). If you remove it, you'll see the first GET again and after that the service worker will intercept them.

![Selection_1010](https://user-images.githubusercontent.com/679144/142464524-c76baf98-a0ee-4598-9bdc-bb4d2d43e985.png)

**Comment by DUOLabs333** [comment]
I did a bit more digging, and it turns out that Invidious and co. is making a CONNECT request, which is then used to make an encrypted GET request, which even though I have installed a CA, can't intercept.

**Comment by DUOLabs333** [comment]
Ok,  a clear example: If you go to `https://piped.kavin.rocks/watch?v=dQw4w9WgXcQ`, you will see in the network tab a `GET https://piped.kavin.rocks/watch?v=dQw4w9WgXcQ`. You do not see this in mitmproxy (you do see other requests for css and js though).

**Comment by Prinzhorn** [comment]
These are far from clear steps, anyway:

My answer above still holds, cannot reproduce. First time I see it, second time it comes from the service worker (and never passes the proxy, because no networking is involved).

First request (new incognito instance with new browser profile), shown in both mitmproxy and network tab:
![Selection_1012](https://user-images.githubusercontent.com/679144/142859104-2203584a-0b37-4b60-a5d5-5cd0c79ec5c2.png)

Second time:

![Selection_1011](https://user-images.githubusercontent.com/679144/142858728-34e4003e-cc64-448d-8ba1-f1378d59ac25.png)

Try disabling service workers in your browser. Or block the service worker scripts via mitmproxy.

**Comment by DUOLabs333** [comment]
You're right, I see it now.

**Comment by DUOLabs333** [comment]
Just two questions: can MITMProxy also get text anchors -- like `example.org/#text`, and can it get the name of the wepage (I don't know if it's transferred in the webpage headers).

**Comment by mhils** [comment]
I think you can answer these questions easily using Google. For example "HTTP how to get anchor" gives me a proper result for your first question. I'm not sure what the "name of the webpage" is, but assuming it's the HTML title attribute, you can parse that from the response content.

**Comment by DUOLabs333** [comment]
Ok, so I'm trying to use BeautifulSoup to extract the titles. This works for most sites, but for Piped, I get just `piped`. Looking at the response.content shows me this at the bottom: `We're sorry but piped doesn't work properly without JavaScript enabled. Please enable it to continue`. Also, Discord similarly shows nothing (and there's no service workers to disabled)

**Comment by DUOLabs333** [comment]
It seems that it needs Javascript to load the rest of the page, so I guess this isn't the fault of mitmproxy. Thank you for your help.
