### ISSUE TITLE
Uncaught Error: Cannot find module 'react'

### ISSUE THREAD

**Issue by taylorlennon** [mitmproxy/mitmproxy#4973]
When i download latest packages from https://mitmproxy.org/downloads/#branches/main/ or clone the main branch and install it on my MacOSX Big Sur, i get below error message while opening mitmweb.

```
app.js:1 Uncaught Error: Cannot find module 'react'
    at s (app.js:1)
    at app.js:1
    at Object.1../backends/static (app.js:2)
    at s (app.js:1)
    at e (app.js:1)
    at app.js:1
s	@	app.js:1
(anonymous)	@	app.js:1
1../backends/static	@	app.js:2
s	@	app.js:1
e	@	app.js:1
(anonymous)	@	app.js:1
```

Mitmproxy: 8.0.0.dev (+190, commit 6997129)
Python:    3.9.9
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.6-x86_64-i386-64bit

**Comment by Prinzhorn** [comment]
I can't reproduce this on Ubuntu (I tried the main branch). I can access http://127.0.0.1:8081/ in both Firefox and Chromium and don't see an error in the console. Are there any additional steps required or is it just opening the mitmweb interface?

**Comment by juanriaza** [comment]
I'm reproducing this one as well

**Comment by juanriaza** [comment]
I reproduced this one, but got it fixed cleaning the browser cache

**Comment by Prinzhorn** [comment]
> but got it fixed cleaning the browser cache

That sounds plausible, does that fix it @taylorlennon? If so then that's still confusing, because we send an `Etag` header and I can see that Chromium sends `If-None-Match`. So caching should already be taken care of.

We could also update our frontend bundling. Modern tooling usually has cache busting integrated (e.g. by generating dist files that include a hash in their name) and we could reference something like `app-542a6b40.js` instead of `app.js` to make sure every new mitmweb release is always in a consistent state. It shouldn't be too hard to update `index.html` during the build (there's most definitely a Gulp plugin out there).
But that would only be an option if you can confirm that this issue is related to caching.

**Comment by sr-ota** [comment]
Had the same issue with the newest mitmproxy version available on chocolatey (8.1.0), cleared the cache and fixed it.

**Comment by nafanz** [comment]
mitmproxy 9.0.1
Python 3.9.7
Ubuntu 21.10

Also faced this problem. Clearing the cache solved the problem, but
```
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/app.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/vendor.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by mhils** [comment]
> ```
> DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/app.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/static/vendor.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> ```

You can safely ignore those, we don't ship sourcemaps in releases to not increase file size.

**Comment by Prinzhorn** [comment]
This should be solved for future releases via https://github.com/mitmproxy/mitmproxy/pull/7386
