### ISSUE TITLE
Improving mitmproxy’s Documentation

### ISSUE THREAD

**Issue by elitest** [mitmproxy/mitmproxy#516]
I have some suggestions and want to work on mitmproxy’s documentation.  I wanted to throw my thoughts out to the community so that I could gather some feedback and ideas before doing a bunch of work and dropping in with some PRs.  This is a great project, but I feel like it needs better docs!   If it would be better I can get these split out into different issues, so that they can be discussed and worked on separately separately.
#### 1. Spruce up the installation instructions.

The Ubuntu instructions need to be fleshed out a bit as I think there are steps missing that even a technical person might not think are obvious.  Been a while since I used  OS X, and even when I did use it, I’m not familiar with how python works on it(homebrew vs. XCode).  Perhaps we could have a pros and cons of why you would install from homebrew vs use the python that comes with XCode.  I assume it boils down to a “Do you mind old python vs more setup” thing.  I may need some help from someone more familiar with mitmproxy on OS X on this one.  Or perhaps make the decision to document one of the methods say, homebrew over XCode.
#### 2. Developer docs

Related to this but somewhat separate I think we should also create developer installation docs so that people know how to get set up to help contribute.  Explain what Countershape is and how to write documentation.
#### 3. Command line options in one place

I think we need to have a page that lists all of the command line options for each tool rather than having them scattered throughout the features/examples.  I’m aware that you could make the argument “just specify --help at the command line”.  The purpose of the command line options page would give someone who hasn’t even installed mitmproxy yet a one-pager on what you can do with mitmproxy, I know this because it was the first page I looked for when I found mitmproxy.  I think that it is important that this page be short and sweet and to the point, perhaps linking to related examples.
#### 4. Introduction docs

I would like to hear some feedback on how people feel about the “[How mitmproxy works](https://mitmproxy.org/doc/howmitmproxy.html)” page vs the “[Modes of Operation](https://mitmproxy.org/doc/modes.html)” page, I feel like this is probably amongst the most polished documentation within this project, but perhaps there is a bit of duplication between the two pages.  Maybe we can re-work these two pages by splitting each of mitmproxy’s modes into its own page, and then take the section related to that mode of operation from the “how mitmproxy works” page and put it on that page.
#### 5. Navigation

As features are added to mitmproxy(I think mitmweb is going to require a decent number of docs) the navigation of the documentation pages is going to become more unwieldy.  Do we actually need to have every documentation page have it’s own line in the navigation?  The [Installing Certificates](https://mitmproxy.org/doc/ssl.html) section, for example, could condense the navigation for these into 1-3 lines, rather than 9, in the navigation and then link to installing the cert for each OS off of one of those pages.
#### 6. Tutorials vs Features vs Examples

I think a lot of the things that are listed as “Features” could be subsumed by the previously mentioned “command line options” page.  Some of these features have tutorials associated with them and I suggest we split them out and link to them from the related command line option, as well as them being in the navigation.  I think the briefer we can be on the theory behind a feature, focusing on not repeating ourselves, and having more examples the better off we will be.
#### 7. Tutorials focusing on the means not the end

Perhaps we should focus the tutorials on what it is you are actually doing rather than the result.  For example, the “[Setting highscores on Apple's GameCenter](https://mitmproxy.org/doc/tutorials/gamecenter.html)” tutorial is a fun way to demonstrate replaying a request, but I don’t know that before I click on and read through the page.  Perhaps it would be better to have a tutorial page that is about “Replaying requests” and “here is an example(or examples) of how to do that”.
#### 8. Countershape

Lastly I wanted to discuss Countershape(I know it is @cortesi’s baby :)).  Using  [Countershape](https://github.com/cortesi/countershape) is a relatively simple and efficient way of generating  good looking documentation, once it is set up.  I feel like the set up part is a bit of an obstacle to new contributor’s, to wrap their minds around, and possibly even regular contributors, that may be preventing people from doing something that is already a maintenance task.  I think the idea behind countershape is that you shouldn’t have to need to set it up in order to contribute documentation, but I find myself wanting to test just to be sure.  Maybe I’m too type A.

I took a look around at how other Open Source projects do documentation I took a look at [Sphinx](http://sphinx-doc.org/).  I think it is what the python docs are written in.  Ultimately it is  overkill for this project, and would be more complex to setup and “learn” as it has its own syntax.

I saw some suggestions about using LaTeX as it works well with version control, and could be used to generate HTML.  Ultimately this is probably in the same category as sphinx.

I think the best potential alternative is to use Github markdown pages.  They don’t look as nice, but they might be easier to contribute to.  Maybe we have a working set of docs in master that is written in markdown and then each release we convert those working copies to Countershape.  There is also [MkDocs](http://www.mkdocs.org/), which lets you convert markdown in a similar way that Countershape does HTML.

Maybe we just keep using Countershape and need to have a section of the documentation that  helps people through the process of setting up Countershape and explaining how it works?  ”How to document mitmproxy” or some such?  Or maybe have a way for people to throw together a quick Word/Open Office doc and then give that to someone in the project who can convert it into something that is going to make sense to Countershape?
#### Conclusion

I'm going to start with the least controversial stuff sometime this weekend hopefully and also prioritize other issues that are open and tagged "docs" as many of them slot nicely into the "command line options page" for example.  Let me know what you all think.

Thanks!
Jim

**Comment by cortesi** [comment]
Hi Jim,

First, thanks for taking the time to think deeply about our documentation situation. The directions you outline would definitely improve things - I look forward to merging the patches! Below are a few point-form comments/expansions/additional considerations:

## Spruce up the installation instructions.

- I'd like us to distinguish more clearly between our developer installation instructions, and our end-user installation instruction, with the developer instructions in the git repo README (or somewhere similar), and the end-user instructions in the documentation proper. See some recent commits from me along these lines.
- It's sad to say, but for end users a straight "pip install mitmproxy" will often be a sub-optimal experience. Pip's package management is incredibly weak, and we have a particularly complicated set of dependencies. For an end-user on OSX, just using the pre-compiled packages will almost always be a better experience. Soon, we'll have similar packages for Windows. I'm open to ideas about what to do on Linux - pre-compiled packages are not very culturally accepted, distro packages lag well behind on our releases, and explaining how to do a virtualenv install that addresses some of the dependency issues might be too complex.
- I'm afraid of over-specifying the installation process, because that can become a significant maintenance burden. Things change rapidly, our release cycle doesn't necessarily match the OS release cycles, and the only thing that sucks more than installation docs that are incomplete is installation docs that are incorrect. The trick here is a light but firm touch - specify what needs to be specified unambigously, refer to external docs when possible, don't over-specify in a way that means we have to redraft too frequently.

# Command line options in one place

I agree that all the command-line options can be moved to one page, probably keeping the side-menu entries and using anchor tags to jump to the right section. However, I also think that duplicating --help in the HTML documentation is probably not the way to go. The features section in the docs is really there to explain the features in an expanded way, not to define the command-line interface rigorously. I'd be concerned about things getting out of sync, and muddying the conceptual work we need to do in the docs with too much command-line detail. Being able to generate nice command-line documentation automatically to keep things in sync would change my mind on that. The docs used to include an auto-generated copy of essentially just the --help output, but I removed it because I didn't feel it was helpful.

# Tutorials vs Features vs Examples

Duplicating the above a bit, but I feel that the features explanations are necessary, and that merging them with the command-line options is not the way to go. The features are accessible by other means that just command-line options - the console and web interfaces, the API - so I feel their explanations should stand free. I'm also not convinced that a complete compendium of the command-line options should go in the HTML docs, and I definitely feel that it won't be sustainable unless we can auto-generate them from the argparse specifications (which should be totally do-able). 

# Countershape

I'm not emotionally attached to countershape - it used to be an internal project at my company, and pre-dated nearly all the other static generators out there. It's not a project that I've ever promoted or tried to polish for release. However, replacing it entirely would be a LOT of work. It's used to render both the website and the docs, two things that inter-relate non-trivially. My gut feeling is that we should leave it in place - if we're going to spend a few weeks of labour, we should use it to polish the docs and add features instead. Making countershape easier to install and documenting it a bit is probably the right way to go. 

As an aside, I think we ALSO need developer API docs. We have two constituencies there - people who want to hack on mitmproxy, and people who want to use the libmproxy API. Generating docs using something like Sphinx (though perhaps not Sphinx itself - I'm told it's horrible) and working on defining our APIs more clearly internally would be a great step forward.

**Comment by mhils** [comment]
Thanks for the excellent post - this is super great feedback from a user's perspective.

> #### 1. Spruce up the installation instructions.

Yes, definitely a pain point for inexperienced users.

**For Linux,** I feel we should copy the approach of https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
**For OSX,** ask @cortesi!
**For Windows**, we only have `mitmdump` at the moment, but a simple `pip install mitmproxy` is sufficient for installation. (Once mitmweb is in shape, we will provide binaries as well)

> #### 2. Developer docs

Developer installation instructions are currently at https://github.com/mitmproxy/mitmproxy#hacking
What's more, we should have code documentation for inline script developers. It's not a top priority, but I feel we don't convey how powerful they are yet. This is actually a really strong argument for Sphinx or something along those lines, which would allow us to re-use code documentation.

> #### 3. Command line options in one place

We have *many* command line switches - most of them are probably not very relevant for the average user. I see your point that we should have a feature overview kind of thing, but not sure whether documenting the command line switches is the best way to do so. Grouping our features into a few distinct pages might be more viable (see 5).

> #### 4. Introduction docs

@cortesi already complained after I wrote "Modes of Operation" - there's certainly a lot of overlap with other parts of the docs. While "Modes of Operation" contrasts different network configurations (and their implications), "How mitmproxy works" details what mitmproxy does in each scenario.
I personally believe that "How mitmproxy works" is certainly the most interesting part of the docs - nonetheless, you're not much wiser how to use mitmproxy after reading it. These two pages serve very different audiences - "How mitmproxy works" details mitmproxy's technical point of view, "Modes of Operation" shows a user which proxy mode he should choose.

> #### 5. Navigation

We don't need much docs for mitmweb I feel - the features are more or less the same ones. Whatsoever, the menu items have grown organically, so to speak. "Installing Certificates" certainly needs to be condensed. I strongly believe this is one of the points where we should start working: We need to define an ideal document structure / toctree.

> #### 6. Tutorials vs Features vs Examples

Not sure whether I get your point here. Generally speaking, each feature should be accompanied with an example. If we have a more detailed tutorial, we should link to it.

> #### 7. Tutorials focusing on the means not the end

 “Setting highscores on Apple's GameCenter” is the best click-bait title we have :stuck_out_tongue: . More seriously, we should have tutorials by use case, not by feature:

- Debug an API
- Inspect my smartphone
- Pentesting

> #### 8. Countershape

See @cortesi's answer. I'd welcome a move from countershape to something with a larger ecosystem, but we should see whether it's worth the effort. I had the pleasure to work with Sphinx for a few days last week - it's not ideal, but kinda ok :wink:

##### Next steps

Before we start anything else, I feel we should define the structure/sections of the docs. This will most likely help us with many of the other changes/decisions. I'll give it an initial shot. :-)

**Comment by mhils** [comment]
A quick draft how we could restructure the docs: 
https://github.com/mitmproxy/mitmproxy/wiki/Docs-Structure - opinions?

**Comment by cortesi** [comment]
I broadly agree with this structure. A few comments:

- We do need a section that introduces the tools, how they differ, and what they do. 
- We have a terminological issue here - "mitmproxy" is both the project and the console tool. I think we should consider renaming the console tool (mitmterm?) to make this clearer. That way "Using mitmproxy" is properly generic.
- Lets save the word "Configuration" for the persistent config, and use "Options" as a generic term.
- If the tutorials are good, they should be near the top of the docs. They illustrate use cases, show what can be done, etc.

**Comment by mhils** [comment]
Good points. Can we put *Configuration* into *Using mitmproxy*?

**Comment by erikringsmuth** [comment]
Could you elaborate more on the expression filters?

One example looks like this.

```
URL containing "google.com":

google\.com
```

What would the expression statement look like? This doesn't seem to work.

```
~u google\.com
```

**Comment by elitest** [comment]
I'm hoping to pick back up on finishing some of these off  in few weeks-month.  I'm moving to another country atm, so my time is limited.

**Comment by mhils** [comment]
Good stuff. Take your time :wink:
