### ISSUE TITLE
Required protobuf version range is too strict

### ISSUE THREAD

**Issue by ngg** [mitmproxy/mitmproxy#5160]
#### Problem Description

The latest released mitmproxy `7.0.4` version depends on `protobuf>=3.14,<3.19`, which is incompatible with the latest protobuf `3.19.4` release. In my project, I have a strict dependency on `protobuf>=3.19` and I cannot downgrade, thus I cannot use the latest released mitmproxy, only a forked version or the main branch.

The main branch currently depends on `protobuf>=3.14,<3.20`, so even if a new mitmproxy version will be released, this issue will reappear when protobuf `3.20.0` is released.

I think this upper bound is too strict and not necessary as protobuf always kept backwards compatibility within a major version.

#### Proposal
Mitmproxy should depend on `protobuf>=3.14,<4`.

**Comment by mhils** [comment]
AFAIK protobuf does not define a public versioning policy at the moment. The best I could find is a comment from 20 days ago stating that they are about to update their strategy: https://github.com/protocolbuffers/protobuf/issues/9487#issuecomment-1034919068.

We're in this weird in between state where some folks use mitmproxy as a library and most use it as an app. To cut a long story short, we don't want to rush emergency releases because one of our dependencies decides to ship a breaking release which would immediately break `pip install mitmproxy` as well. The current ranges are already a concession to make life easier for people who embed mitmproxy. I don't mind extending the permissible range if the dependency does specify a clear versioning policy, but that's not the case for protobuf.

For your specific case, I'd recommend pinning to a specific commit hash or tracking main - pip should handle Git dependencies just fine. Alternatively, we should see a new mitmproxy release in the coming weeks. :)

**Comment by ngg** [comment]
Do you have an ETA for the 8.0.0 release? Or would it be possible to release a 7.0.5 version that accepts the current latest protobuf? (With a <3.20 range, just like the main branch has)

**Comment by mhils** [comment]
My best ETA is "in the coming weeks". I'd rather spend my time on that than pushing a 7.0.5. release, sorry.

**Comment by ngg** [comment]
Tis issue because this is causing a problem for us yet again. The protobuf dependency was updated in https://github.com/mitmproxy/mitmproxy/commit/85e57a91e0cc96affc282d511ce606782ea2047b 25 days ago, but there were no releases since, so we can't update our project to use protobuf 3.21 while using a released version of mitmproxy.

I've opened an issue with Protobuf whether they can guarantee backward compatibility between minor version bumps: https://github.com/protocolbuffers/protobuf/issues/9872

**Comment by matthew16550** [comment]
@ngg  FYI the protobuf dependency was removed in #7327
