### ISSUE TITLE
Support for non-standard HTTP versions (Shoutcast)

### ISSUE THREAD

**Issue by epitron** [mitmproxy/mitmproxy#527]
I noticed an odd bug in mitmproxy: if I try to connect to a shoutcast stream, the client receives a 502 error, and the mitmproxy curses UI prints `HttpError("Invalid HTTP version in line: 'ICY'",)` in red with no HTTP code. However, if I look at my network connections, mitmproxy **has** connected to the shoutcast stream and is downloading it.

It also doesn't write any of the data that it's streaming to the flows file when I use the `-w` option.

It's like there's zombie connection that mitmproxy has forgotten about.

Example:

```
$ http_proxy=localhost:8080 curl http://xstream1.somafm.com:8002
            <html>
                <head>
                    <title>502 Bad Gateway</title>
                </head>
                <body>HttpError("Invalid HTTP version in line: 'ICY'",)</body>
            </html>
```

When I check my network traffic, mitmproxy is still streaming the audio from somafm.com. If I connect multiple times, it'll have multiple downloading streams. They won't stop until I kill the process.

(This happens on the latest git checkout.)

**Comment by cortesi** [comment]
Hi there. There are two things going on here. First, by default mitmproxy tries to spool an entire response in memory before relaying it to the client. This is necessary if we're going to allow you to intercept and modify the response before it is relayed, and unfortunately there's no generic way to tell if a response is an infinite stream. To cope with this, we have the --tcp option that lets you specify hosts that are forwarded with a generic TCP proxy - that is, the data is handed to the client as it arrives.

So, the real issue here is how we're handling the non-standard HTTP version error. First, we need to make sure we correctly terminate the upstream connection if we see an error we can't handle. Second, we need to consider whether we want to simply pass invalid HTTP versions down to the client. My inclination is to to be as permissive as possible - if we see it in the wild, however non-standard, we should be able to relay it.

**Comment by epitron** [comment]
Hi! Thanks for the response!

Good to know about the --tcp option. That may come in handy! I'm currently using mitmproxy as an adblocking proxy for my phone, that also lets me spy on what it's doing: https://github.com/epitron/mitm-adblock

So, once the ICY HTTP version issue is resolved, would setting `--stream SIZE` cause mitmproxy to start streaming the response after it received `SIZE` amount of data, instead of buffering it up forever?

**Comment by mhils** [comment]
I tracked this issue down today - the error we're seeing is acually a problem that occurs while closing the socket.

Here's how this issue was made possible:

1. On Windows, `test_server.TestTransparentResolveError` failed. This should have happened:
  1. Resolving the target address fails.
  2. We return a 502 error [here](https://github.com/mitmproxy/mitmproxy/blob/7abaf3c3626a68a23233c3dc759ade32068f0462/libmproxy/proxy/server.py#L105).
  3. The client receives a 502 error page.
2. This actually happened:
  1. Resolving the target address fails.
  2. We return a 502 error [here](https://github.com/mitmproxy/mitmproxy/blob/7abaf3c3626a68a23233c3dc759ade32068f0462/libmproxy/proxy/server.py#L105).
  3. We directly close the connection afterwards.
  4. Closing a connection with pending readable data issues a `RST` on Windows, which arrived at the client before the HTML messages was transferred completely.
  5. The client did not receive a 502 message but a disconnect instead.

To counter this, we started to read all data from the socket before closing it ([here](https://github.com/mitmproxy/netlib/blob/c53d89fd7fad6c46458ab3d0140528e344de605f/netlib/tcp.py#L266)). Now, this fixes the issue mentioned above, but introduces a new one: If the remote endpoint continues sending data infinitely (as in a shoutcast stream), we're stuck in a loop here.

I see two ways how we can fix this:

1. Just sleep for a second after sending an error message (which is, as I see it, the only case where the still-data-on-the-socket-close-gracefully case applies)
2. Read a maximum on N bytes from the socket.

The close-socket topic comes up again and again because it's apparently very hard to fix (the current workaround survived more than half a year). @cortesi, do we want to attempt a fix before the next point release or do we want to play the safe ball here?

**Comment by mhils** [comment]
Ok, we agreed to make an attempt to fix the infinite read immediately, which is now commited to netlib and should be part of the next major release. This doesn't fix invalid HTTP versions though. My concern would be that just allowing any kind of HTTP version may yield to obscure error messages for non-HTTP protocols. How about just treating the HTTP version as an arbitrary string, but checking it against a whitelist: `.startswith("HTTP/") or .startswith("ICY")`?

**Comment by epitron** [comment]
Nice! Thanks for looking into this. The Windows TCP stack sounds delightful. :)

**Comment by cortesi** [comment]
I'm in two minds about this. On the one had, whitelisting custom HTTP version specifiers seems over-specific to me. On the other hand, the Shoutcast protocol is NOT HTTP, just one that looks a lot like it.  The clincher for me is that many of the "real world" tools out there do interpret the version spec liberally - Shoutcast passes through many proxies (including Squid, with the right settings), and tools like CURL and so forth will happily do the same. I think this is a strong argument for relaxing the strictness here. I suggest we expand pathod and netlib to allow fiddling with the version to mimic this, and then wash that through into the tooling.

**Comment by mhils** [comment]
The first step has been completed: We do not attempt to parse the version string anymore but store it as plain bytes.

**Comment by ericlaw1979** [comment]
FWIW, in Fiddler I simply hacked this such that if the server's HTTPVersion value string starts with ICY, it is treated as HTTP/1.0 with streaming enabled and response bodies dropped as they are read. This seemed to placate the userbase.
