### ISSUE TITLE
mailcap deprecated for Python 3.11 removed for Python 3.13

### ISSUE THREAD

**Issue by notatallshaw** [mitmproxy/mitmproxy#5297]
I've been following this Python dev mailing thread which proposed to deprecate `mailcap` from the standard library: https://mail.python.org/archives/list/python-dev@python.org/thread/EB2BS4DBWSTBIOPQL5QTBSIOBORWSCMJ/

After a code search I noticed that you were the only library I recognized which used this module: 
https://grep.app/search?q=import%20mailcap
https://github.com/mitmproxy/mitmproxy/blob/4f7f64c516341c586c9f8cb6593217ff3e359351/mitmproxy/tools/console/master.py#L2

Please be aware the Steering Council just accepted this deprecation proposal meaning the module will be deprecated for Python 3.11 removed for Python 3.13.

(I don't have any affiliation with this decision, I am just trying to proactively raise awareness)

**Comment by KORraNpl** [comment]
@mhils Are you aware of any library that could substitute `mailcap`, what's your idea here? I poked around this, and it seems that it is used in only one place for opening a request/response in default application (if content type is correctly recognized), but it works only on Unix-compatible OSes as `mailcap` uses `*/etc/*` files for detection:

https://github.com/python/cpython/blob/f6656163de483003697d510031827b7512056d55/Lib/mailcap.py#L51-L65

So on macOS (which I use) and Windows mitmproxy falls back to `less` or other editor:

https://github.com/mitmproxy/mitmproxy/blob/9d1821e920d6225578a0b65881d203a537186298/mitmproxy/tools/console/master.py#L160-L175

The easiest solution would be to just have `less` or other pager open a file, but I'm not sure if you want to kind of degrade the feature on Unix OSes.

**Comment by merwok** [comment]
There are OS-specific ways of opening a file with the registered default application:
- `xdg-open` program on OSes that have `xdg-utils` package installed
- `open` program on mac
- `os.startfile` on window (this one might execute files that are detected as programs, so security implications)

**Comment by mhils** [comment]
@KORraNpl: I had not heard about/used mailcap before this issue was opened, so I naturally have no idea. I traced it back to https://github.com/mitmproxy/mitmproxy/commit/cb0e3287090786fad566feb67ac07b8ef361b2c3 though (Feb 2010), so that was quite fun. 😄 

Honestly I feel like there isn't much harm done if we just remove that part. 

There's of course opportunity to improve things, maybe `xdg-open` on Linux or `os.startfile(..., "edit")` on Windows? We do need to think critically about whether we want to essentially enable code execution here, so maybe just removing it is good enough.
