### ISSUE TITLE
Server playback mode doesn't use certificates from the saved response file

### ISSUE THREAD

**Issue by macmantrl** [mitmproxy/mitmproxy#533]
Certificates are being stored in the saved response file when initial recording traffic, but during server playback these certificates are not used (although they are loaded into the flow object).

I ran into this issue because a rogue server was sending back the wrong certificate, and thus I was getting the bad certificate even though I thought the certificates were being pulled from my saved response file.

--no-upstream-cert works around the issue, but I don't get the same altnames as the saved certificate.

I can't find exactly where in the code this is going wrong, but I did notice in libmproxy/proxy/server.py that find_cert() is always using the upstream cert even for server playback, since it seems to have a connection to the upstream server. That's unexpected too, I don't want my server playbacks to be connecting upstream, they should only be communicating with the client by returning responses from the saved response file.

**Comment by mhils** [comment]
Hi @macmantrl,

thanks for the report! A server replay may contain flows from multiple sources (served with different certs). The issue is that we can't look into the request to determine the correct cert to serve before establishing TLS. Thus, we need to rely on SNI (which may not be present), the upstream certificate (if not disabled) and possibly the server name from a `CONNECT` request (not in transparent mode). 
One could of course connect the SSL layer with the HTTP protocol layer within mitmproxy and search for matching certificates - I wouldn't be too keen to interconnect these layers though. As a workaround, you can always use `--cert` and specify custom certificates for selected domains. Alternatively, I'd be happy to accept a patch that adds a inline script hook for find_cert.

Cheers,
Max
