### ISSUE TITLE
HTTP/2 protocol error: Received header value surrounded by whitespace b'1.mxp _dca '

### ISSUE THREAD

**Issue by gg4u** [mitmproxy/mitmproxy#5480]
Hi, 

I have learnt about mitmproxy here:

https://blog.ouseful.info/2019/08/28/intercepting-json-http-responses-to-web-browser-page-requests-using-mitmproxy/

now that I was able to set it up to work, if I browse this site I got error:

HTTP/2 protocol error: Received header value surrounded by whitespace b'1.mxp _dca '

I don't know what it is and if peculiar to this very domain - can it be useful  to improve  ?

using binary 8.1.1 for OS X

**Comment by mhils** [comment]
You can disable inbound header validation by setting the corresponding option: https://docs.mitmproxy.org/dev/concepts-options/#validate_inbound_headers

We don't allow malformed HTTP by default because that technically enables HTTP smuggling attacks, but that's not much of a concern for almost all users.

**Comment by gg4u** [comment]
Thank you @mhils !

**Comment by r00t-** [comment]
it's creepy that a huge site like http://wordpress.com/ (and any blog they host!) triggers this.

**Comment by r00t-** [comment]
(this is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/4836 which has more information)
