### ISSUE TITLE
Move flow list header (>>>) to lastest request as new ones get added

### ISSUE THREAD

**Issue by kshitij86** [mitmproxy/mitmproxy#5490]
#### Problem Description

In mitmproxy, the flow header (>>>) remains on whatever request was last accessed, making it difficult to navigate to the end/latest one as a bunch of flows are created at once.

#### Proposal
The flow list header always points to the latest request in the list

#### Additional context
Before feature: 
![image](https://user-images.githubusercontent.com/26821140/180951626-248f785e-c72d-48c3-9721-fda48317eebd.png)
After feature:
![image](https://user-images.githubusercontent.com/26821140/180951753-d0325432-134c-4ced-94a0-9c25cd5bd6c4.png)

**Comment by Prinzhorn** [comment]
In other words, you want a feature to _optionally_ scroll the view to the bottom as new flows arrive? Optional because the current behavior is the most sensible because how else would you open the current flow if there is a risk of the `>>` jumping between you making the decision to hit Enter and actually hitting Enter? That would be a human<->PC race condition :smile: 

> making it difficult to navigate to the end/latest one as a bunch of flows are created at once.

You can use Home/End key on your keyboard just like on any other scrollable interface to jump to the top/bottom of the list. Page up/down will also scroll in bigger increments.

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/issues/678
