### ISSUE TITLE
how to make the mitmproxy root CA certificate work with Chrome / Chromium on Linux / Ubuntu

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#551]
I'm on Ubuntu 14.04

Took me a while to figure this out (I was not able to find any information on this when searching with the "mitmproxy" keyword). It's working out-of-the box with Firefox but not at all with Chrome.

**The certificate downloaded from mitm.it needs to be added using `certutil`** (https://code.google.com/p/chromium/wiki/LinuxCertManagement)

```
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n <certificate nickname> -i <certificate filename>
```

I don't know where the best place to document this is. Starting now people searching for it will at least find this entry.

**Comment by mhils** [comment]
Thanks for the report!

refs #549

**Comment by elitest** [comment]
Thanks @Prinzhorn. When you say "out-of-the box" with Firefox, I assume you mean it allows you to add the CA certificate through the GUI?  Interesting, even though I know Chrome uses NSS I had always assumed that it used the system "ca-certificates", just like it gets certificates from the system on other platforms.  But according to [this](https://code.google.com/p/chromium/wiki/LinuxCertManagement) it looks like you are right.  From that page:
> Rather than reinvent the wheel and create another certificate configuration tool, we are going to wait for a system certificate configuration utility to be created and launch that. In the mean time, you can configure certificates with the NSS command line tools.

It also links to [this](https://wiki.mozilla.org/NSS_Shared_DB_And_LINUX) which indicates that the user nssdb is ~/.pki/nssdb and the system one is /etc/pki/nssdb.  Both articles refer to ~/.pki/nssdb, so they must both use it.  Did you restart Chrome after adding it using the Firefox GUI?

I have actually been working on the SSL documentation over in #549.  [This](http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861) is what I have proposed for the docs for Ubuntu, which I thought would have the advantage of catching most things as well as being system-wide. Unfortunately there isn't really a canonical(if you will excuse the pun) location that CA certs are stored on Linux.  I'll see if I can do some testing on Linux this week.

**Comment by Prinzhorn** [comment]
> When you say "out-of-the box" with Firefox, I assume you mean it allows you to add the CA certificate through the GUI?

Yes, see screenshot

![screenshot from 2015-04-09 07 47 54](https://cloud.githubusercontent.com/assets/679144/7061080/cea4e096-de8c-11e4-8d5e-84750aa36315.png)

It works immediately after closing the dialog.

> Did you restart Chrome after adding it using the Firefox GUI?

Yes. I installed mitmproxy some months ago and used it with Firefox because of the Chrome issues. But yesterday I had to use Chrome and tried to find a way to make it work.

Doesn't Firefox use it's own cert store? Which means I basically only added it to FF using this dialog?

If I download the cert and use the OS dialog (see screenshot) it still doesn't work with Chrome.

![screenshot from 2015-04-09 07 51 47](https://cloud.githubusercontent.com/assets/679144/7061113/4a54ce4a-de8d-11e4-932f-a5d6ac2820d6.png)

**Comment by elitest** [comment]
I did some testing.  It turns out that Chrome and Firefox both use an NSS database, unfortunately they both use separate databases.  This is what [Chrome's ~/.pki/nssdb](https://gist.github.com/elitest/081d25a4c1cae0d77560) looks like when you add the certificate as documented [here](https://code.google.com/p/chromium/wiki/LinuxCertManagement) while  this is what [Firefox's  ~/.mozilla/firefox/#randomstring#.default/](https://gist.github.com/elitest/f188a5bc2cf176668527) looks like after adding it through the GUI.  Neither use each others, nor do they use /etc/pki/nssdb(a.k.a. the system-wide one).  They also don't use the system ca-certificates package.

**Comment by slhck** [comment]
For completeness' sake, this is what I had to do:

```bash
sudo apt-get install libnss3-tools
certutil -d sql:$HOME/.pki/nssdb -A -t C -n mitmproxy -i ~/.mitmproxy/mitmproxy-ca-cert.pem
```

Then, restart Chrom[e|ium] with the command line argument `--proxy-server=http://127.0.0.1:8080`

Is there a difference between that and [this approach](http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861) you mentioned?

**Comment by Prinzhorn** [comment]
AFAIR I did http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861 back when I just installed mitmproxy. But it didn't affect Chromium at all.

**Comment by slhck** [comment]
Hmm, ok, then apparently we need a separate instruction for installing the certs for Chrome to be added to the docs.

(Actually I was confused since the docs mention just about every platform except for Linux in general and Chrome in particular.)

**Comment by elitest** [comment]
So since #549 has been merged, I consider this closed.  For future google people who may arrive, `chrome://settings/search#ssl` is how you import certs in a gui in Chome(even on Linux).  For our use case it is less convenient than having an "install certificate" button on the certificate information window, but I understand chrome's desire to dissuade people from installing random certs.  I'm going to see if I can get that Chrome documentation updated to mentoin the GUI.

**Comment by cortesi** [comment]
@elitest Cheers.

**Comment by timdp** [comment]
I think the `certutil` command should really be in the Linux/Ubuntu docs. The link to Stack Overflow doesn't help as none of the comments there mention it.

**Comment by CarterPape** [comment]
@Prinzhorn @slhck bless your souls where is the tip jar

**Comment by baptx** [comment]
For information, the certutil command did not work for me on Ubuntu 20.04 (it looks like other people had the problem also: https://askubuntu.com/questions/1187097/how-to-import-ca-cert-for-chromium-in-ubuntu-18-04).
In addition, the URL `chrome://settings/search#ssl` mentioned by @elitest did not work for me with Chromium 86 from the Ubuntu package. I had to use the URL `chrome://settings/certificates` instead and go to the "Authorities" tab. Without the URL, it can also be found in the browser settings in "Privacy & Security -> Security -> Manage certificates".
The documentation at mitm.it still does not mention Chromium / Chrome configuration (tested with latest mitmproxy 5.3.0).
I recommend to create a separate browser profile for more security (since you don't need a MITM certificate when not using a tool like mitmproxy). It can be done with a command like `chromium --user-data-dir=chromium-dev-profile`.
