### ISSUE TITLE
libmproxy as WSGI middleware

### ISSUE THREAD

**Issue by jpic** [mitmproxy/mitmproxy#560]
With libmproxy as a WSGI middleware, it would be pretty easy to use it with tools like gunicorn or uwsgi which are made to scale.

**Comment by mhils** [comment]
This is currently not on our roadmap, but we welcome external contributions. :smiley:

**Comment by ikreymer** [comment]
Hi, I just wanted to mention, in case this is useful to someone, I recently built such a WSGI middleware: [wsgiprox](https://github.com/webrecorder/wsgiprox)

The approach here is to enable any WSGI application to accept HTTP/S proxy connections and route them to the WSGI app. Note that middleware does not do any upstream connections, it is up to the underlying WSGI app to handle that.

The approach is sort of the reverse, rather than adding WSGI support to a proxy (as mitmproxy) does, the idea is to add a lightweight proxy support to WSGI.

Let me know if this tool may be useful to you. (I've also used mitmproxy as well and am a big fan of the project!)
