### ISSUE TITLE
mitmweb: Add support for syntax highlighting / coloring

### ISSUE THREAD

**Issue by SapiensAnatis** [mitmproxy/mitmproxy#5623]
#### Problem Description
When selecting "View: msgpack" on a msgpack request or response, the resultant JSON is displayed using single-quotes (`'`), which is not valid. It should use double-quotes (`"`) instead.

#### Steps to reproduce the behavior:
1. Have a request/response in `mitmweb` and click Replace and use the file contained in this archive: [get_resource_version.zip](https://github.com/mitmproxy/mitmproxy/files/9692381/get_resource_version.zip)
2. Select "View: msgpack" next to the Replace button
3. Notice that the resultant JSON contains single-quoted properties and strings:
```json
{
    'data_headers': {
        'result_code': 1
    },
    'data': {
        'resource_version': 'y2XM6giU6zz56wCm'
    }
}
```

I am not an expert on the JSON standard, but pasting the output into a [JSON validator](https://duckduckgo.com/?q=json+validator&t=ffab&ia=answer) throws up errors which can be fixed by using double quotes (and I assume that's what the red highlighting means, since the above code block starts with ```json)

#### System Information
```
>mitmproxy --version
Mitmproxy: 8.1.1
Python:    3.10.6
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.22622-SP0
```

#### P.S.
I know a bit of Python but am unfamiliar with this codebase, however I would be happy to try fixing this myself and submitting a PR if that would be easier? It seems like something that would be simple enough for a first time contributor to attempt.

**Comment by Prinzhorn** [comment]
I don't know if this is _supposed_ to be valid JSON. First and foremost this is a human readable version of msgpack that happens to look somewhat like JSON.

The code is here

https://github.com/mitmproxy/mitmproxy/blob/a1631154d722ea4c82dcb72e0c84ad38c6991de5/mitmproxy/contentviews/msgpack.py#L18-L30

I don't know if everything that msgpack does _can_ be represented in JSON. If so, then this code could basically just use `json.dumps`.

@tasn can you comment on that please?

**Comment by Prinzhorn** [comment]
So yeah, msgpack is _not_ JSON compatible. E.g. map keys can have _any_ type. I'm closing, feel free to re-open if I'm missing something.

**Comment by SapiensAnatis** [comment]
Ah, that makes sense about them not being the same especially with the bytes. 

My use case was more pasting them into syntax highlighting things which expect the double quotes, rather than parsing the json (there are msgpack deserialisers for that). My msgpack data usually only used primitive types. This is fixed by a simple find-and-replace though

**Comment by Prinzhorn** [comment]
If you're interested in contributing, I'm sure adding coloring to the mspack view would be a great addition.

https://github.com/mitmproxy/mitmproxy/blob/a1631154d722ea4c82dcb72e0c84ad38c6991de5/mitmproxy/contentviews/msgpack.py#L18-L30

Here's how this works for JSON

https://github.com/mitmproxy/mitmproxy/blob/a1631154d722ea4c82dcb72e0c84ad38c6991de5/mitmproxy/contentviews/json.py#L20-L38

You essentially need to use `TViewLine` and mostly in the last else add tokens for the corresponding types instead of treating all the same:

https://github.com/mitmproxy/mitmproxy/blob/a1631154d722ea4c82dcb72e0c84ad38c6991de5/mitmproxy/contentviews/msgpack.py#L29-L30

But mitmweb is currently missing the colors that the terminal uses https://github.com/mitmproxy/mitmproxy/blob/cd4a74fae7cbd8119afc3900597f798ec1604db7/mitmproxy/tools/console/palettes.py#L149-L225
That should be somewhat easy to add as well, but it can be a separate step.

I'm going to re-open this but as a feature request to add syntax highlighting support to mitmweb. Everything is already there (e.g. it adds things like `class="json_string"`) but it doesn't do anything yet. So if the classes/colors where there it would already work for JSON. For msgpack it lacks it in the contentview.

**Comment by tasn** [comment]
@Prinzhorn, yeah, adding coloring would indeed be a great addition!

As for JSON: yeah, msgpack is more complex than JSON and you can't represent it as valid json.

**Comment by SapiensAnatis** [comment]
I’m happy to contribute syntax highlighting as described. Thank you for taking the time to provide the relevant code snippets. I have a fair bit on my plate right now so it might be a while before I have a chance to look at it. 

I think I understand roughly what needs to be done, but one question I had was how this would be tested — can you actually get data from the content view with colour information inside of it? Or would it be a screenshot test?

**Comment by SapiensAnatis** [comment]
I've been taking a look at this, and I've managed to get JSON syntax highlighting added. This was as straightforward as adding some CSS for the existing JSON token classes, and adding additional logic to detect keys apart from normal strings:
![image](https://user-images.githubusercontent.com/5047192/195723967-be550dff-845f-44e5-b4a3-b8ded4d5b100.png)

Adding highlighting to msgpack is a bit more tricky: the JSON is easily tokenized by serializing it, but this is a luxury we dont have with msgpack. I am probably going to try and tokenize it using a Regex for each possible token in a series of capture groups split by 'or', and then a greedy any-character 'fallback' group which should match things like byte arrays. I'm open to any suggestions, however.

**Comment by Prinzhorn** [comment]
Nice!

> I am probably going to try and tokenize it using a regex for each possible token in a series of capture groups split by 'or', and then a greedy any-character 'fallback' group which should match things like byte arrays. I'm open to any suggestions, however.

As I suggested above, the current msgpack formatter already does most of the work, doesn't it? The first two branches unroll maps/lists and the last branch handles the different types

https://github.com/mitmproxy/mitmproxy/blob/a1631154d722ea4c82dcb72e0c84ad38c6991de5/mitmproxy/contentviews/msgpack.py#L29-L30

So can't you have some if/else inside that branch to check the type of `value` and apply the according tokens (number, string, boolean, etc)?

**Comment by SapiensAnatis** [comment]
I did consider that, however the formatted must be an iterator over TViewLine because each line then gets its own div in the contentview. The pretty() function is recursive so this is tricky… but I’ll have a think about it. It might be possible to generate the whole list using the recursive function and then loop through it afterwards to make the iterator?

**Comment by Prinzhorn** [comment]
I see. I'd definitely strongly prefer not trying to approximate this with regular expressions when a parser exist. Given that the current implementation already keeps everything in memory, I don't think it would be an issue if your implementation does so as well (instead of using an iterator directly). So you should be able to collect all tokens recursively by passing a list to each recursive call that collects all `TViewLine` (a new list parameter to `pretty` that is based through all calls). And then, as you said, expose this list in a second step. So the new `pretty` actually just wraps the internal recursive function and uses it to collect the list, which is then exposed. I don't know much Python, does a simple `list()` implement `Iterator`? Then the outer function can just return the collected results of the recursive one.
