### ISSUE TITLE
Response streaming, last chunk is not passed to modifier

### ISSUE THREAD

**Issue by cxagit** [mitmproxy/mitmproxy#570]
I'm using the response streaming to modify response data seamless and everything works fine so far.
But libmproxy seems to embezzle the last chunk, if the the response data is not an exact multiple of 4096.

For example, I'm downloading a 2224640 bytes file. libmproxy will pass the chunks 0-4096, 4096-8192, ..., 222031 - 2224128 though the generator to the modifier. But the last 512 byte part 2224128-2224640 isn't passed. (But It's passed to the client, it's just not passed to the modifier)

If the file size is 2228224 bytes (a multiple of 4096) also the last chunk is passed.

**Comment by mhils** [comment]
Hi there,

can you provide us with a reproducible test case? 
Works fine for me. Looking at the [code](https://github.com/mitmproxy/mitmproxy/blob/90dff4a8a15580cf3e86d29c6aba1f97410a0b89/libmproxy/protocol/http.py#L1343-L1357), we treat all chunks equally.

**Comment by cxagit** [comment]
If done some more testing now and the initial description was wrong, the last chunk is passed to the modifier, I'm sorry. 
The bug is that if the size of the last chunk is changed, this change it is not transmitted. Changing the size of another chunk (in the middle of the stream) is no problem at all.

The size of the transmitted file should be 2225152, but the last 512 bytes are missing.
![2015-04-28_14-17-47](https://cloud.githubusercontent.com/assets/9060772/7369324/76d4ab88-edb1-11e4-8c0d-5d464408f2a0.png)

**Comment by mhils** [comment]
Modifying streamed responses is a difficult thing to get right. First, if you don't use chunked transfer encoding, you must specify the complete size of the request in the initial Content-Length header (or resort to some HTTP1.0 read-until-eof workarounds - not sure how good that works). Depending on your setup, this may be very difficult to do. Alternatively, if you use `transfer-encoding: chunked`, you need to adjust the prefix so that it contains the actual length of your chunk.
