### ISSUE TITLE
Include EventLog when saving flow file

### ISSUE THREAD

**Issue by daMatz** [mitmproxy/mitmproxy#5729]
#### Proposal
Additionally include the EventLog when saving a session / exporting it to a `flows` file.

This way we would have all the information to reconstruct a session and no important information is getting lost.

**Comment by mhils** [comment]
There shouldn't be any important information in the event log that's not in the flows. Is there anything in particular you're thinking of here?

**Comment by daMatz** [comment]
Yes, in the first place all the output of `ctx.log`.

**Comment by daMatz** [comment]
Mostly custom logging from scripts, but also if e.g. mitmproxy is started in verbose mode etc. it is nice to have the log output later in combination with the flow file for debugging in my point of view.

**Comment by mhils** [comment]
For that use case there's `mitmdump > eventlog.txt` :) This is a wontfix for me as fundamentally all aspects of the communication should be in the flows, and if that's not the case, that's a separate bug.

**Comment by daMatz** [comment]
Alright thanks for looking into it. Would still find it useful e.g. when not using `mitmdump` but `mitmweb`, but I get your point :)

**Comment by DmitryFrolovTri** [comment]
@mhils actually the event log contains information on attempted but failed communications in addition to other things. e.g. when the SSL session was not setup for example because client refused the provided certificate - there will be nothing in flows. So observer would not know that some communication was attempted and failed. IF the flow log is shared to others this information would be lacking. Knowing of successful and unsuccessful transactions is vital for any delayed review of the flows.  Unfortunately unsuccessful transactions would only be in the events which are not saved.  Therefore I thumb up the request to save events log together with flows and ask to add this feature - without any special command line option specification. Now Important information on not successful transactions is lost once the session is closed.

**Comment by mhils** [comment]
I stand by my previous point: This is a wontfix for me. I'd much rather have support for "meta" flows to indicate TLS handshake errors, ignored flows, etc.

**Comment by DmitryFrolovTri** [comment]
Well "meta" flows would be great. Alternatively (if it's simpler) just an option to save events on the events screen would also solve this issue. Person would save flows and would save events separately as text file. what do you think about this one? Should be much simpler to implement.

**Comment by mhils** [comment]
`mitmdump > eventlog.txt` already does that. For mitmproxy, I'd be willing to accept a PR that adds a command to save the event log to disk.
