### ISSUE TITLE
Don't "break" SSL-mode?

### ISSUE THREAD

**Issue by raymontag** [mitmproxy/mitmproxy#589]
Hey,

is there the possibility to tell mitmproxy that it should not touch SSL-traffic at all but show the encrypted traffic? I know that there's the way with the -I flag, however I would like to see the "ignored" flows with headers (and encrytped data if it's available).

**Comment by mhils** [comment]
What kind of headers do you want to see? SSL Headers?
`-I` and `--tcp` are the intended ways. We're looking to have a representation of `--tcp` in the UI hopefully soon.

**Comment by raymontag** [comment]
Yep, I want to see the headers of the ignored SSL-traffic :) Looking forward to this feature.

**Comment by cortesi** [comment]
Just to be clear, due to the nature of the protocols we can't inspect the HTTP headers of SSL traffic unless we're actively intercepting the traffic (it's all encrypted). We can show some information about the SSL protocol negotiation, but it's very limited and not likely to be what you actually need.
