### ISSUE TITLE
Map remote should include port in Host header (mitmweb)

### ISSUE THREAD

**Issue by jochenseeber** [mitmproxy/mitmproxy#5907]
#### Problem Description

When using `--map-remote` in `mitmweb`, the request URL gets replaced, and the `Host` gets updated. However, the port is not added to the Host header, leading to problems when using non-standard ports.

#### Steps to reproduce the behavior:

1. `mitmweb --map-remote '|http://[^/]+|http://portquiz.net:4444' --listen-port 9090'`
2. `curl --proxy http://127.0.0.1:9090 http://github.com`
3. Host header does not contain port
4. It should: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

#### System Information

```
Mitmproxy: 9.0.1
Python:    3.11.1
OpenSSL:   OpenSSL 1.1.1s  1 Nov 2022
Platform:  macOS-13.2-arm64-arm-64bit
``

**Comment by mhils** [comment]
The map remote addon just sets a new URL [here](https://github.com/mitmproxy/mitmproxy/blob/dfeddcf4add66a6ebab1d508c47256185ef6ddb7/mitmproxy/addons/mapremote.py#L68), which seems like the right thing to do. Seems like the bug is in [`mitmproxy.http.Request.host` and `mitmproxy.http.Request.port`](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/http.py) then, contributions welcome!
