### ISSUE TITLE
Upgrade wheel >0.37.1 to mitigate CVEs

### ISSUE THREAD

**Issue by jhaxon** [mitmproxy/mitmproxy#5969]
#### Problem Description
The latest docker image of mitmproxy (v9.0.1) includes wheel 0.37.1 as part of `python:3.11-slim-bullseye`. [Source](https://github.com/mitmproxy/mitmproxy/blob/c7de03bc3679a8c3a90ad4d5767f450558908341/release/docker/Dockerfile#LL7C6-L7C31) 

This version of wheel contains known CVEs as documented in this advisory: [GHSA-c2vw-wggw-v283](https://github.com/mitmproxy/mitmproxy/security/advisories/GHSA-c2vw-wggw-v283)

#### Steps to reproduce the behavior:
1. `docker run -it --privileged mitmproxy/mitmproxy:9.0.1 /bin/sh`
2. `wheel version`
3. observe `wheel 0.37.1`

#### System Information
```
Mitmproxy: 9.0.1
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
```

**Comment by mhils** [comment]
As I mentioned in the original report: I don't think this affects our users. If you think this assessment is wrong, please provide an actual proof-of-concept.

It's ReDoS in a build dependency. Please don't run automated scanners against FOSS dependencies and then make us do your triaging work.

**Comment by cb-axon** [comment]
@mhils - What report are you talking about? The Original GHSA that scanners are picking up are not accessible anymore to the public, and due to government regulations, we do not get a choice on what level we can scan to. Some scanners get all packages/dependencies here, and we need justification/proof if we are going to say this vulnerability does not affect this package/image. 
Can you please share any justification here about why you don't think this affects mitmproxy users?

**Comment by mhils** [comment]
@cb-axon: I've provided a brief assessment in my previous comment. I'd be happy to set up a commercial support contract with you folks if you would like a more detailed explanation or patched Docker images.

We are taking our users' security seriously. In this case this means we won't ship an "security" patch release that does nothing but create security fatigue. This approach is also documented [in the docs](https://docs.mitmproxy.org/stable/overview-installation/#security-considerations-for-binary-packages). Again, I'm happy to provide you with paid enterprise support if the environment you operate in requires this.
