### ISSUE TITLE
cannot select text from UI for copy/paste

### ISSUE THREAD

**Issue by majewsky** [mitmproxy/mitmproxy#597]
Using the mitmproxy-0.12.0-2 package provided by Arch Linux, I cannot select and copy text from the terminal window where mitmproxy is running.

Since I remember this to work in the past, I downgraded to mitmproxy-0.11.3-2, and there the text selection and copying works as expected.

**Comment by cortesi** [comment]
Hi Stefan. Since our last release, Urwid has started enabling mouse capture by default. To select text for cutting and pasting, you need to hold down a modifier key (ctrl on my system). 

It's an awkward in-between state of affairs. In the next release, we'll have proper mouse interaction to justify this, and we'll be able to detect an attempt to select and give the user a hint in most circumstances.

**Comment by majewsky** [comment]
Thanks for the hint. Using that knowledge, I found out by trying the correct modifier key is Shift in Konsole.

Shall we leave this issue open then?

**Comment by cortesi** [comment]
Let's leave this issue open to remind me to resolve the mouse interaction situation.

**Comment by osterman** [comment]
On my system (El Capitan) all that worked is `Fn+Option`

**Comment by liruqi** [comment]
On my macOS Sierra, `fn` would work.

**Comment by sryze** [comment]
How do you scroll while selecting the text (if body occupies more space than the screen hight)? Mouse wheel doesn't seem to work for me.

I know that there is C shortcut to copy body but I wanted to copy only a part of it and couldn't find how to do that.
