### ISSUE TITLE
Add pre-commit hook to run tests and formatting scripts

### ISSUE THREAD

**Issue by RG7279805** [mitmproxy/mitmproxy#6015]
#### Problem Description
Every time I make a commit I forget to perform tests and apply the proper formatting

#### Proposal
A pre-commit git hook that will run all the tests and formatters
I am ready to make a PR if it's ok

**Comment by mhils** [comment]
Code-formatting is automatically enforced by @autofix-ci, so forgetting that is not a problem you need to worry about. We typically squash PRs so that it does not clutter the Git history.

I personally dislike pre-commit hooks because they get in the way of my workflow. As long as we don't have a major contributor championing this, this won't happen.

**Comment by RG7279805** [comment]
React/TS code doesn't get formatted via autofix-ci
Any plan to add that ?

**Comment by mhils** [comment]
#5986 should have fixed that.

**Comment by RG7279805** [comment]
> #5986 should have fixed that.

Ahh my bad just saw it thanks for the update
