### ISSUE TITLE
Can't clone Git repository over `mitmproxy`

### ISSUE THREAD

**Issue by NiklasRosenstein** [mitmproxy/mitmproxy#6237]
#### Problem Description
When cloning a Git repository via HTTP over `mitmproxy`, it just hangs. Works for small repositories but seems not to work for bigger repositories. The entry in the `mitmproxy` UI shows "content missing".

<table><tr><td>

![image](https://github.com/mitmproxy/mitmproxy/assets/1318438/3de32110-9e2c-4902-8c01-51988ab1756a)

</td><td>

![image](https://github.com/mitmproxy/mitmproxy/assets/1318438/724f1bf6-08d9-4f18-a83e-d3e75ad9b257)

</td><td>

![image](https://github.com/mitmproxy/mitmproxy/assets/1318438/5bb9805f-cca7-4ab2-91bd-1c632aadb5e6)

</td><td>

![image](https://github.com/mitmproxy/mitmproxy/assets/1318438/90f6b004-b80e-4fdd-9042-9823902c6020)

</tr></tr></table>

<p align="center">

![image](https://github.com/mitmproxy/mitmproxy/assets/1318438/48255fae-b98c-48c5-8d9c-b130ff0d5da8)

</p>

#### Steps to reproduce the behavior:
1. `mitmproxy`
2. `git config --global http.proxy=http://localhost:8080 && git config --global http.sslCAInfo=$HOME/.mitmproxy/mitmproxy-ca-cert.cer`
3. `git clone https://gitlab.freedesktop.org/gstreamer/gstreamer-rs.git`

#### System Information

```
Mitmproxy: 9.0.1
Python:    3.11.4
OpenSSL:   OpenSSL 3.1.1 30 May 2023
Platform:  macOS-13.4.1-arm64-arm-64bit
```

**Comment by mhils** [comment]
mitmproxy by default buffers the entire response before sending it to the client. This is necessary to make sure that interception filters etc. have all information available before making a decision. You can a) set the [`stream_large_bodies`](https://docs.mitmproxy.org/stable/concepts-options/#stream_large_bodies) option, or increase timeouts so that mitmproxy has enough time to buffer the entire body.

From a practical perspective, we should maybe look into providing progress updates within the UI...

**Comment by Prinzhorn** [comment]
> From a practical perspective, we should maybe look into providing progress updates within the UI...

https://github.com/mitmproxy/mitmproxy/issues/6126

**Comment by mhils** [comment]
Thanks @Prinzhorn, closing this as a duplicate then! 😃
