### ISSUE TITLE
New version of mitm not able to replay server-side recordings made on previous version

### ISSUE THREAD

**Issue by jpkrause** [mitmproxy/mitmproxy#625]
Hello,
I use mitmproxy a lot to execute automated tests against an Android client application in which the device receives pre-recorded responses to requests from mitmproxy using the server-side playback feature. This has been extremely useful to the automated testing efforts, however I am unable to use these recordings on a newer version because of a serialization version mismatch:

"Incompatible serialized data version: 0.11.3"

I reverted to v0.11.3 in order to continue using the recordings I have made, but would love to be able to use the latest version. Is there any way to port these recordings over to the newest version? I have quite a few recordings that involved a good bit of manual modification and cleanup to get them to work as I desired. It would be very frustrating and time consuming to have to redo all of them.

Thanks,
John

**Comment by cortesi** [comment]
Unfortunately, this is by design. Until we reach 1.0, we're not maintaining compatibility in the serialisation format between major revisions. While our format is still changing quickly, it's too time-consuming to maintain converters for all our historical formats. We also couldn't do a perfect job of this - i.e. when we add new fields we'd have to synthesise them when converting.

**Comment by jpkrause** [comment]
Gotcha, thanks. I'll just wait for a while before I redo them all, then. It's working fine with the older version for now.
