### ISSUE TITLE
Regarding #626 - Foxtel Go and Play URL's

### ISSUE THREAD

**Issue by JPS46225** [mitmproxy/mitmproxy#627]
![image](https://cloud.githubusercontent.com/assets/12774655/8123331/d9162ebc-110a-11e5-9d3b-ec9576b51212.jpg)

Ok, regarding Foxtel go and play, this is one of the URLs detected by mitmproxy, however I can't play it. I'm not sure whether this is an authentication issue or something else

**Comment by JPS46225** [comment]
I was expecting the stream to open, since I had the direct URL, also, when I tried to play it on my iPhone, I got the error message, 'The operation could not be completed'

**Comment by JPS46225** [comment]
How to reproduce the issue

Download Foxtel Go, analyse through mitmproxy and look for url's with Telstra in it's name

**Comment by JPS46225** [comment]
Platform is iOS

**Comment by JPS46225** [comment]
Will also work with Foxtel Play for Windows

**Comment by cortesi** [comment]
OK, we're getting there. ;) For the next ticket, please put all of this in one message, not multiple ones, and give us a more descriptive title - no references to closed tickets, and a description of the issue in the title. Say, "Foxtel Go and Play URLs do not stream". 

Now, the issue here is not a bug in mitmproxy. The way mitmproxy works by default is to buffer up an entire response in the proxy before relaying it downstream. This is meant to let you modify and tamper with the response. For very large responses (i.e. streaming responses), this means mitmproxy never receives the "complete" response, and nothing is ever relayed down tot he client. Please have a look at the response streaming documentation for some ideas of how to handle this in mitmproxy:

http://mitmproxy.org/doc/features/responsestreaming.html
