### ISSUE TITLE
 export websocket messages 

### ISSUE THREAD

**Issue by 3052** [mitmproxy/mitmproxy#6721]
#### Problem Description

cannot export websocket message, can only view them

#### Steps to reproduce the behavior:
1. view websocket messages
2. try to export
3. can only export HTTP response body, which is something different

#### System Information

mitmproxy 10.2.4

**Comment by thebigbone** [comment]
Can you give me an example? If I understand correctly, you are looking to export the websocket request body?

**Comment by 3052** [comment]
request and response

**Comment by thebigbone** [comment]
> request and response

Isn't response body exportable by selecting the request and then using ```b``` filter?

**Comment by thebigbone** [comment]
> > request and response
> 
> Isn't response body exportable by selecting the request and then using `b`?

**Comment by 3052** [comment]
@thebigbone the issue is not "is it possible to export websocket?" its not possible currently. stop this line of questioning now, this is your only warning.

also giving suggests without testing them is especially rude. if you had done so you would know that the result of your test is an empty file.

**Comment by mhils** [comment]
@3052: Your point is correct, but let's be nice and assume good intent.

**Comment by 3052** [comment]
@mhils sorry man, but I am old enough that I have seen this type of person over and over again. they throw out half baked suggestions without testing them, putting the question asker on a wild goose chase wasting their time. its incredibly rude and I will not stand for it any more. thanks for the feedback.

**Comment by txrp0x9** [comment]
Hi @3052 
I'd like to know if the below format works well for you as the saved file for websocket messages
```
[INCOMING] Hello client!
[OUTGOING] Hello server!
```
They will be in order as seen in the WebSocket Messages tab

**Comment by 3052** [comment]
yeah thats good

**Comment by txrp0x9** [comment]
So I've investigated and found the root to be the cut.save command keybinding
```
    km.add(
        "b", "console.command cut.save @focus response.content ",
        ["flowlist", "flowview"],
        "Save response body to file"
    )
```
This keybind hardcodes the body as `response.content` and websockets store the body in `websocket.messages` leaving the response.content empty, which in turn leaves an empty file when ws connections are saved.

I've thought of two approaches:
1. Change the cut.save command, and include a simple if statement to check if the flow is a websocket and then if response.content is being saved, we instead save a formatted version from websocket.messages in the format of the previous message. This however seems hacky
2. Another thing we could do is actually maintain the response.content variable and make it store the formatted websocket messages, adding a formatted message to response.content everytime we add to websocket.messages. This would not require us to modify cut.save command, but the memory usage is doubled for websocket messages.
This would also however cause the body to be show in the Response tab
![image](https://github.com/mitmproxy/mitmproxy/assets/41499871/5957961f-92ae-46e2-bfe2-a36b9a29b80e)
Instead of No content, it'd show the value of response.content. We'd need to add an exception to not show the response.content in case of ws connections

I'll start working on the message formatting code, in the meantime, I'd like to know which approach you suggest @mhils and if I've missed something obvious

**Comment by txrp0x9** [comment]
So I've gone ahead with approach 2 and it seems to fit in well with the current implementations. WebSocket messages are saved as expected in both multiflow and singleflow cut.save command parameters.

**Comment by 3052** [comment]
https://github.com/mitmproxy/mitmproxy/pull/6767

**Comment by mhils** [comment]
Without looking to closely into this: A more uncontroversial alternative would be to modify the _export_ addon - not the _cut_ addon - to include WebSocket messages in the full raw export.

For the cut addon (`b`) this is tricky - we're really stretching our mini language here, maybe let's focus on the export feature first.

**Comment by txrp0x9** [comment]
Websocket messages can now be saved with the b keybind (save body). You can also use the export command to save ws connections now @3052 [#6767]
Issue can be closed now.
