### ISSUE TITLE
flow.intercept() isn't working in inline scripts

### ISSUE THREAD

**Issue by ojab** [mitmproxy/mitmproxy#714]
Not sure if it's a bug or desired behavior, but it looks like an issue for me. Simple script like
```python
def request(context, flow):
    flow.intercept(context._master)
```
correctly sets "'intercepted': True", but flow is actually accepted by mitmproxy (I assume that if interception pattern is not set, intercepted is set to False somewhere).

**Comment by mhils** [comment]
This is more or less by design currently - you can only intercept flows programatically by setting an interception pattern. I realize there's a use case, so if you're interested, feel free to give it a spin (you'd need to suppress the `.reply` somehow) and send a PR! 

- You'd need to suppress `.reply()`, which gives control back to the main channel: https://github.com/mitmproxy/mitmproxy/blob/adf2877020c563fa9dc9a4df26bfd8b243e8e41a/libmproxy/console/__init__.py#L703
- Related: https://mitmproxy.org/doc/dev/architecture.html

**Comment by dufferzafar** [comment]
I guess this can be closed too.
