### ISSUE TITLE
"Address already in use" even when it's not

### ISSUE THREAD

**Issue by milesrichardson** [mitmproxy/mitmproxy#782]
Hi

I am running multiple mitmproxy instances on one machine.  Each instance has its own port between 49000 and 50000. All instances are listening on interface `0.0.0.0`. Instances stop and restart multiple times per hour. 

Most instances start fine. However, a few random ones will fail with the error that address is already in use:

```$ mitmproxy -p 49338
Error starting proxy server: error(98, 'Address already in use')```

However, netstat does not show any process using the port:

```$ sudo netstat -nlp | grep 49338```

I also do not see any zombie processes trying to start the same instance.

Any idea what's causing this? Is the problem that every instance is listening on 0.0.0.0? How does mitmproxy decide whether a port is "open"?

**Comment by mhils** [comment]
We just use plain Python sockets internally: https://github.com/mitmproxy/netlib/blob/9fbeac50ce3f6ae49b0f0270c508b6e81a1eaf17/netlib/tcp.py#L769-L771
This doesn't look like it's caused by mitmproxy, sorry.

**Comment by hynguyen2610** [comment]
I ran into this problem too an not found any solution yet. Someone said about `ps -f ax | grep mitm
`
I tried an kill the processes in ps command result but mitmproxy still can not be started. The error message is the same.

**Comment by dwfreed** [comment]
This is generally caused by sockets still having data to send after you've shut down mitmproxy (this includes closing the sockets).  You should check `netstat -Wplant` (drop the W if you're on RHEL 6 or CentOS 6 or older) and look for sockets in TIME_WAIT state with the local port set to the port mitmproxy was bound to.  Presently, you have to wait for all of those sockets to finish closing or time out (default timeout is 4 minutes) before you can start another mitmproxy instance on that port.

@mhils: a change that could be made that would solve this issue in the majority of cases is setting SO_REUSEADDR on the socket.  This is portable to all platforms, and the semantics are roughly the same (same enough for mitmproxy's uses, anyway)

**Comment by mhils** [comment]
@dwfreed, we do set SO_REUSEADDR on the socket. ;-)
