### ISSUE TITLE
mitmdump 0.14 on Windows 10 Does Nothing

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#826]
When I execute mitmdump 0.14 on Windows 10 (administrator mode), the program just waits. It's as if its not receiving any input. There's no errors reported. I've tried various command lines:

mitmdump
mitmdump --p 8888
mitmdump -T --host

Is there some other Windows installation step in addition to "pip install mitmproxy" and "pip install netlib"?

Can someone confirm that mitmdump works on Windows 10?

I previously had mitmdump 0.12 and 0.13 working. I think it was on Windows 10. I'm unable to drop back to a previous version of mitmdump because "pip install" keeps installing 0.14. I'm not sure how to build previous versions.

I'm running mitmproxy 0.14 on a Mac without issue.

**Comment by mhils** [comment]
mitmdump works perfectly fine for me on Windows - in fact, Windows 10 is my primary development OS. You should see `clientconnect` messages once a client connects to port 8080 - otherwise, there are not even incoming TCP connections from clients.

**Comment by BSalita** [comment]
Right. I was expecting client connects to begin immediately. That's what I was use to seeing on a Mac.

1. Why does Windows require a client connect to the port (default 8080) before reacting to incoming connections? I didn't see this behavior mentioned in the docs.

2. mitmdump on Windows doesn't seem as robust as a Mac. If I repeatedly hit F5 in the browser, mitmdump seems to get all chocked up, various errors start occurring such as client SSL errors. Chocking on mitmproxy on a Mac is rather difficult.

**Comment by mhils** [comment]
1. Without any command line switches, mitmproxy opens a proxy server listening on port 8080. This is the same behaviour on all OSes?
2. I can confirm this issue to some extent, but it's terribly hard to debug - any help and pointers are welcome. One known issue is that the Queue implementation on Python 2 is rather bad (which we use for inter-thread-communication). Since we are not on Python 3 yet, it's hard to say if that is the only problem.
3. Can you specify that better?
4. See (2).

**Comment by BSalita** [comment]
1. The command line is "mitmdump -T --host". Nothing happens, on any port, on any client, until 8080 is connected.

2 to 4. I'll defer more testing until Windows mitmdump for Python 3 is released.
