### ISSUE TITLE
Upstream Proxy mode to a socks proxy? 

### ISSUE THREAD

**Issue by XericZephyr** [mitmproxy/mitmproxy#830]
Is there a way to use mitmproxy to build up a transparent http proxy and then upstream to a socks5 server? Thanks.

**Comment by mhils** [comment]
Not yet. I believe the simplest way to accomplish that is using redsocks/proxychains nehind mitmproxy. Does this satisfy your needs?

**Comment by XericZephyr** [comment]
I tried proxychains with squid, which doesn't work. I guess the reason is that proxychains also need to proxy the inbound (to squid) request to socks proxy, which is not expected.

**Comment by mhils** [comment]
Getting these things right is tricky, sorry. :confused: 
We do not plan to add a mode that does transparent interception + redirect to an upstream proxy for now. Your best bet is doing that with proxychains/redsocks, at which point the mitmproxy in front of that is optional and should not really matter for the configuration.

**Comment by valentinradu** [comment]
Since this ranks high on Google I'll leave this info here for posterity:

`mitmproxy` actually works without any problem with `proxychains` on Linux. Simply:

`proxychains mitmproxy -T --host`

You might want to edit `/etc/proxychains.conf` and set `quiet_mode` to true so it doesn't interfere with `mitmproxy`'s output.

That being said, on macOS it fails because of segfault 11. Could be related to SIP, but not sure, didn't investigate.

**Comment by scruel** [comment]
> 
> 
> Getting these things right is tricky, sorry. 😕
> We do not plan to add a mode that does transparent interception + redirect to an upstream proxy for now. Your best bet is doing that with proxychains/redsocks, at which point the mitmproxy in front of that is optional and should not really matter for the configuration.

If the project need to change the proxy dynamically in code, proxychains is not an option, because it need to rewrite the configuration file then restart both the mitmproxy and proxychains...

**Comment by 3052** [comment]
https://github.com/mitmproxy/mitmproxy/issues/211
