### ISSUE TITLE
libmproxy proxy.ProxyConfig - ignore_hosts

### ISSUE THREAD

**Issue by garrylachman** [mitmproxy/mitmproxy#850]
its not possible to add only one host in proxy.ProxyConfig
```
libmproxy/proxy/config.py line 55:
ignore_hosts=tuple('.*')

libmproxy/proxy/config.py line 21:
HostMatcher
self.patterns = list(patterns)

when cast tuple to list
the result is ['.', '*'] 
instead ['.*']
```
workaround is set '.*' twice in ignore_hosts but its ugly...

**Comment by mhils** [comment]
Thanks for the report - this is an error on your end though:

```python
>>> tuple('.*')
('.', '*')
```
The correct way to specify this would be `('.*',)` or `tuple(['.*'])`.

[libmproxy/proxy/config.py#L55](https://github.com/mitmproxy/mitmproxy/blob/d1ce1aa993eb431a0db9048a42830c1234571c29/libmproxy/proxy/config.py#L55) currently contains an empty tuple, which works fine.
```
            ignore_hosts=tuple(),
```

Alternatively, you can just pass a list here, you just avoid that as a the default argument in Python because it's mutable (see http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments).
