### ISSUE TITLE
Support protocols where the server sends the first message (e.g. IMAP)

### ISSUE THREAD

**Issue by Kidlike** [mitmproxy/mitmproxy#910]
Is it possible?

I tried like this: `mitmproxy --tcp imap_host`, but no luck. Thunderbird was stuck in receiving emails for like 2 minutes. Usually it would take 10 seconds, so I didn't wait any longer.

So should I try some other mode? Or is it not possible at all ?

Thanks !

**Comment by mhils** [comment]
There are two issues here:
- Thunderbird always expects a SOCKS proxy, no matter what you configure. Passing `--socks` to mitmproxy is enough to overcome that.
- In IMAP, the server send the first message. However, we try to peek into the connection [here](https://github.com/mitmproxy/mitmproxy/blob/ae4a1dd6dec9d95e450837db8937e3fb7604c121/libmproxy/protocol/tls.py#L449) and [here](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/proxy/root_context.py#L53).

This is pretty tricky to fix, so I'm sorry to say that proxying IMAP (or other protocols where the server sends the first message) is not possible at the moment.

**Comment by Kidlike** [comment]
I see. Thank you ! Should we change this to a feature request and leave it open ? :)

**Comment by mhils** [comment]
Yes. To extend on my previous comment a bit: One feature mitmproxy supports is HTTP server replay, which works even if the target server is offline. To make this work, we establish a server connection in the latest possible moment, long after we have determined that the traffic is actual HTTP. For IMAP, we're now stuck at the protocol detection phase, because (1) we don't have a server connection and (2) the client doesn't send anything that indicates the protocol.  Making the right tradeoff here is difficult.

**Comment by Kidlike** [comment]
The client must send _something_ first right ? Otherwise the server doesn't know the client.
Maybe a combination of a mitmproxy parameter that will enable a functionality, and a functionality that will switch to a mode that all you are describing is possible ?

I don't know the internal mechanisms of mitmproxy so maybe I am way off... :)

**Comment by Kriechi** [comment]
I'm sorry, but this is not possible with the way mitmproxy currently works.
