### ISSUE TITLE
Check for expired CA certificate

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#939]
_From @mhils on November 4, 2015 10:37_

The mitmproxy CA certificate is generated on the first start of mitmproxy. Due to mitmproxy/mitmproxy/issues/815, the certificate is only valid for three years. `CertStore.from_store` should check if the CA certificate is still valid and raise an error if that is not the case (which we can then act on in mitmproxy).

_Copied from original issue: mitmproxy/netlib#101_

**Comment by mhils** [comment]
_From @tinius on January 14, 2016 1:47_

Seems to me that this would do it:

    ca = OpenSSL.crypto.load_certificate(
                OpenSSL.crypto.FILETYPE_PEM,
                raw)
    if ca.has_expired():
        raise CertExpiredException("mitmproxy's certificate has expired.")

That being said, is there a reason why we shouldn't just call create_store on the spot?

**Comment by mhils** [comment]
> That being said, is there a reason why we shouldn't just call create_store on the spot?

I'm not sure what's the best way, but silently replacing the CA (without user notification) is not really optimal. At the very least, we need some kind of notification that a new certificate has been generated.

**Comment by anchitjain1234** [comment]
@mhils I am a new contributor and would like to work on this 
> At the very least, we need some kind of notification that a new certificate has been generated.

What kind of notification? Like printing on screen that new certificate has been generated or taking user response to whether or not generate a new certificate?

**Comment by mhils** [comment]
Not sure yet. Let's start by adding a function in netlib that determines if the CA is outdated + tests? :smiley:

**Comment by anchitjain1234** [comment]
@mhils please review #995.

**Comment by dwfreed** [comment]
From reading the chromium issue, validity length checks only apply to leaf certificates, not CAs.  This means your CA can still be valid for 20 years (mine is), so long as mitmproxy's generated leaf certificates are only valid for 39 months or less.  Since mitmproxy always generates certs on the fly, and never caches them to disk, checking for expiration of them only matters in really long running instances (usually mitmdump).

**Comment by baptx** [comment]
@mhils This issue seems to be still present on the latest version of mitmproxy (6.0.2), my mitmproxy certificate is expired since 16 December and I got this error on Firefox when visiting a website with HSTS preload like Facebook, which does not allow exceptions:
```
Did Not Connect: Potential Security Issue

Firefox detected an issue and did not continue to www.facebook.com. The website is either misconfigured or your computer clock is set to the wrong time.

What can you do about it?

www.facebook.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

Your computer clock is set to 12/25/2020. Make sure your computer is set to the correct date, time, and time zone in your system settings, and then refresh www.facebook.com.

If your clock is already set to the right time, the website is likely misconfigured, and there is nothing you can do to resolve the issue. You can notify the website’s administrator about the problem.

Learn more…

www.facebook.com uses an invalid security certificate.
 
The certificate is not trusted because the issuer certificate has expired.
 
Error code: SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE
 
View Certificate
```

How can I renew the mitmproxy CA certificate instead of creating a new one by removing the .mitmproxy folder?
