### ISSUE TITLE
ImportError: No module named mitmproxy.flow

### ISSUE THREAD

**Issue by fbi007130** [mitmproxy/mitmproxy#997]
##### Steps to reproduce the problem:

1. I have already install mimproxy1.6
2. mitmdump -s "a.py aa bb"

3. 
mitmdump: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/script/script.py", line 66, in load
    execfile(self.args[0], self.ns, self.ns)
  File "a.py", line 4, in <module>
    from mitmproxy.flow import FlowWriter
ImportError: No module named mitmproxy.flow

cat a.py
import random
import sys

from mitmproxy.flow import FlowWriter

def start(context, argv):
    if len(argv) != 2:
        raise ValueError('Usage: -s "flowriter.py filename"')

    if argv[1] == "-":
        f = sys.stdout
    else:
        f = open(argv[1], "wb")
    context.flow_writer = FlowWriter(f)

def response(context, flow):
    if random.choice([True, False]):
        context.flow_writer.add(flow)

##### Any other comments?

---

Mitmproxy Version:1.6
Operating System:RaspberryPi@osmc

**Comment by dufferzafar** [comment]
I *think* your problem is a version mismatch, you have mitmproxy 0.16 but are looking at scripts (perhaps from the Github repo) that have now been modified!

We recently had a repo restructure (relevant commit: d95a1f9)

Just changing `from mitmproxy.flow import FlowWriter` to `from libmproxy.flow import FlowWriter` should be good, I guess.

**Comment by fbi007130** [comment]
https://github.com/mitmproxy/mitmproxy/tree/master/examples

there is something wrong
